### ISSUE TITLE
too long email address

### ISSUE THREAD

**Issue by jurii84** [JeremySkinner/FluentValidation#1036]
### System Details

- FluentValidation version: 8.1.3
- Web Framework version (ASP.NET Core 2.1):

### Issue Description
Build Email Validator not check is email is too long.

According to specification format of email addresses is local-part@domain where the local part may be up to 64 characters long and the domain may have a maximum of 255 characters.

**Comment by JeremySkinner** [comment]
Hi. The email address validator is intentionally fairly loose - it is not intended to fully implement the RFC (which is not practical due to complexity and performance), but to catch 'common' errors. It is also exactly the same behaviour as the `EmailAddressAttribute` in the .NET Framework (they use the same regex). For compatibility, the email validator will not be changed and will retain its current behaviour.
