### ISSUE TITLE
WebApi integration - problem with inheriting from FluentValidationModelValidator

### ISSUE THREAD

**Issue by semao** [JeremySkinner/FluentValidation#1042]
### System Details

- FluentValidation version: 8.1.3
- Web Framework version: 4.6.1, WebApi 2

### Issue Description

In order to customize validation results (push ErrorCode to ModelState) I've inherited from

```
public class MyVeryOwnFluentValidationModelValidator : FluentValidationModelValidator
    {
        public MyVeryOwnFluentValidationModelValidator(IEnumerable<ModelValidatorProvider> validatorProviders, IValidator validator) : base(validatorProviders, validator)
        { 
        }

        protected override IEnumerable<ModelValidationResult> ConvertValidationResultToModelValidationResults(ValidationResult result)
        {
            return result.Errors.Select(
                e => new ExtendedModelValidationResult()
                         {
                             ErrorCode = e.ErrorCode,
                             Message = e.ErrorMessage,
                             MemberName = e.PropertyName
                         });
        }
    }
```

Unfortunatelly, it seems that  CustomizeValidatorAttribute feature is making my validator useless as during validator customization each validatior is cloned (but also replaced with base implementation):

```
public class FluentValidationModelValidator : ModelValidator {
[...]
              public FluentValidationModelValidator CloneWithCustomizations(CustomizeValidatorAttribute customizations, HttpActionContext context) {
			return new FluentValidationModelValidator(ValidatorProviders, _validator) {
				ActionContext = context,
				Customizations = customizations
			};
		}
}
```

I wonder if simple fix would just be to make method CloneWithCustomizations virtual?

**Comment by JeremySkinner** [comment]
Hi, thanks for the feedback. The WebApi 2 integration with FluentValidation is actually considered legacy at this point, and isn't receiving any updates other than critical fixes going forward (for integration with web applications, I'd highly recommend using ASP.NET Core as the integration is much better for use with FluentValidation). 

That being said, you should still be able to do what you need. Rather than inheriting from the `FluentValidationModelValidator`, the usual/recommended way to do this is by using an [Interceptor](https://fluentvalidation.net/webapi#validator-interceptors). You'd need to implement `IValidatorInterceptor` either in your validator, or in a separate class (if you use a separate class you can wire up the interceptor using the `[CustomizeValidator]` attribute -  [see the docs](https://fluentvalidation.net/webapi#validator-interceptors))


Inside the interceptor's `AfterMvcValidation` method, you can rebuild the `ValidationResult` to contain the data that you want to pass to ModelState. For example, if you always wanted the error code to be output instead of the error message then your `AfterMvcValidation` method would look like this:

```csharp
public ValidationResult AfterMvcValidation(HttpActionContext actionContext, ValidationContext context, ValidationResult result) {
	var projection = result.Errors.Select(error => new ValidationFailure(error.PropertyName, error.ErrorCode));
	return new ValidationResult(projection);
}
```

Hope that helps, let me know if you'd like me to clarify anything.
