### ISSUE TITLE
Dropdown validation on the client side with Built-in Validators

### ISSUE THREAD

**Issue by Polloman12345** [JeremySkinner/FluentValidation#1047]
Hello!

FluentValidation version: 7.4.0
Web Framework version MVC 5

I am having problems when validating the selected element in a dropdown. When the request passes to the server side, there is no problem. But from the client side, I can not get the validation executed along with the rest of the ofligatory fields. the default value of the dropdown is -1 and I have tried to do the validation with equal / notequal / greatherthan without getting it to run on the client side in any of the cases.

Any help will be great. Thank you!

**Comment by JeremySkinner** [comment]
Hi, you're going to need to provide more details. What's the rule definition and the data type of the property?

**Comment by JeremySkinner** [comment]
Also: only a very small subset of rules will run on clientside, see: https://fluentvalidation.net/mvc5#clientside-validation

**Comment by Polloman12345** [comment]
Hello!

Here is my rule definition:
RuleFor(x => x.CarId).Equal(-1).WithMessage("aaaaaaaaaaaaaaaaaa");
Property definition:
public int CarId { get; set; }

Should I try better with Matches/ InclusiveBetween???

Thank you very much for the quick answer!!

**Comment by JeremySkinner** [comment]
Right, a call to Equal won’t be translated to the client as MVC does not provide any clientside validators out of the box to do this. 

Matches applies a regex to string properties so that won’t work here, and InclusiveBetwern is for defining ranges which isn’t right here either. Sounds like you might be better off writing some custom JavaScript or a custom rule with the clientside jquery.validate if you want clientside validation here.

**Comment by Polloman12345** [comment]
I have finally used InclusiveBetween with a range 0-int.MaxValue. In this way I keep the dropdown behavior in which the default values ​​are -1 and the rule correctly validates on the client side. This validation covers all my cases, thank you very much!
