### ISSUE TITLE
"Default" ruleset always executed

### ISSUE THREAD

**Issue by johnhwright** [JeremySkinner/FluentValidation#1048]
### System Details

- FluentValidation version: 8.1.3
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): WebApi 2

### Issue Description
Upgraded from 7.X to the latest version and now rulesets with the name "Default" are apparently now included even when calling `validator.Validate(object)` with no rulesets.

```
RuleSet("Default", () =>
{
    RuleFor(x => x.Id).Empty();
    RuleFor(x => x.LastName).NotEmpty();
}
```

If this is intended, probably should be noted in the docs or as a [breaking change](https://fluentvalidation.net/upgrading-to-8.html) in the upgrade notes. Definitely caught us off guard.

**Comment by JeremySkinner** [comment]
"default" has always been the shorthand for any rules not explicitly defined in a ruleset, so calling `RuleSet("Default")` actually has no affect, as these will also be treated as outside of a ruleset. I was under the impression that this had always been the behaviour, but I may be mis-remembering. I'll make sure it's added to the documentation.

**Comment by JeremySkinner** [comment]
Looks like this was actually introduced in 7.5.2 as a side affect of allowing a rule to be part of multiple rulesets (without having to duplicate the rule). It's intended so that you can say `RuleSet("MyRuleSet, Default", () => ...` to allow a group of rules to be executed as both the MyRuleSet as well as if no ruleset is specified. 

So yes this would've been a breaking change if you'd previously relied on "Default" as an explicit ruleset name. It hadn't occurred to me that anyone would use "Default", as a call to `Validate(ruleSet: "default")` has always meant "execute rules not in any ruleset".

I'll make it more prominent in the ruleset docs that Default has a special meaning.

**Comment by johnhwright** [comment]
Thanks Jeremy. We'll definitely be reviewing our current approach and see if we can't align it more with the original intention.

**Comment by JeremySkinner** [comment]
Closing as the documentation has now been updated.
