### ISSUE TITLE
Positive test case inconvenience - proposal of new extension method

### ISSUE THREAD

**Issue by kalkusa** [JeremySkinner/FluentValidation#1054]
### Issue Description

`ValidationTestExtension` contains methods for testing validation of particular fields of validated object:
- ShouldHaveValidationErrorFor
- ShouldNotHaveValidationErrorFor

In negative test scenario it's enough to use `ShouldHaveValidationErrorFor`. But if we want to have positive one we must either use `ShouldNotHaveValidationErrorFor` for all the fields of validated object or use workaround syntax (which by the way is not documented):

`ValidationTestExtension.ShouldNotHaveError(validator.TestValidate(validated));`

I would like to suggest to add method `ShouldNotHaveValidationError` working in similar way to `ShouldNotHaveValidationErrorFor` but for all fields.

**Comment by JeremySkinner** [comment]
Hi,  the `ValidationTestExtension.ShouldNotHaveError` method you're using is just a wrapper around the assertion methods that are on the TestValidationResult and is designed for use on a single property. If you want to assert that there are no errors on any properties, then you don't need to use this and you can just use the properties on the test result directly:

```csharp
validator.TestValidate(model).Which.ShouldNotHaveValidationError();
```

Actually, in this case you don't even need to do this. The test helper methods are intended to help with finding specific properies to assert against. If you just want to check that there are no errors on the result, just call `Validate` manually and check IsValid. 

````
Assert.True(validator.Validate(model).IsValid);
```

I don't really think there needs to be another method to do this as both these approaches are pretty simple.

And yes you're correct this isn't documented. [It is on the list to be documented](https://github.com/JeremySkinner/FluentValidation/issues/820) but I don't personally have time to work on this at the moment - I don't have much time to work on FluentValidation, and when I do most of the time ends up being spent on either answering support questions, or updating the ASP.NET core integration. If you think this should be higher proprity then please feel free to submit a pull request to update the docs, otherwise I'm afraid it'll have to wait until I get time.
