### ISSUE TITLE
ValidatorOptions.PropertyNameResolver doesn't work in ONE case

### ISSUE THREAD

**Issue by piotrkolodziej** [JeremySkinner/FluentValidation#1061]
Hey,

I am NOT new to FV, we've been using it successfully for over a year now. Today however I noticed a strange issue with camelCase property names that are returned. 

ALL properties of ALL models are properly camelCased (Amount becomes amount etc) except for one property name that is present in three of our models (RegistrationId). No matter what we do, RegistrationId ALWAYS becomes RegistrationId. I've debugged custom camelcase property resolver taken from JSON.NET and it properly returns registrationId.

I have no idea what's going on and it makes me worry––would surely appreciate your help.

ps: we do not do anything custom when it comes to the middleware and response formatting.
pps: sorry for invalid code formatting below but I can't make it work for some reason.

`ValidatorOptions.PropertyNameResolver = CamelCasePropertyNameResolver.ResolvePropertyName;`

```
namespace HotelManager.API
{
	public static class CamelCasePropertyNameResolver
	{
		public static string ResolvePropertyName(Type type, MemberInfo memberInfo, LambdaExpression expression)
		{
			var result =  ToCamelCase(DefaultPropertyNameResolver(memberInfo, expression));
			return result;
		}

		private static string DefaultPropertyNameResolver(MemberInfo memberInfo, LambdaExpression expression)
		{
			if (expression == null) return memberInfo != null ? memberInfo.Name : null;
			var chain = PropertyChain.FromExpression(expression);
			if (chain.Count > 0) return chain.ToString();

			return memberInfo != null ? memberInfo.Name : null;
		}

		private static string ToCamelCase(string s)
		{
			if (string.IsNullOrEmpty(s) || !char.IsUpper(s[0]))
			{
				return s;
			}

			var chars = s.ToCharArray();

			for (var i = 0; i < chars.Length; i++)
			{
				if (i == 1 && !char.IsUpper(chars[i]))
				{
					break;
				}

				var hasNext = (i + 1 < chars.Length);
				if (i > 0 && hasNext && !char.IsUpper(chars[i + 1]))
				{
					// if the next character is a space, which is not considered uppercase 
					// (otherwise we wouldn't be here...)
					// we want to ensure that the following:
					// 'FOO bar' is rewritten as 'foo bar', and not as 'foO bar'
					// The code was written in such a way that the first word in uppercase
					// ends when if finds an uppercase letter followed by a lowercase letter.
					// now a ' ' (space, (char)32) is considered not upper
					// but in that case we still want our current character to become lowercase
					if (char.IsSeparator(chars[i + 1]))
					{
						chars[i] = char.ToLower(chars[i], CultureInfo.InvariantCulture);
					}

					break;
				}

				chars[i] = char.ToLower(chars[i], CultureInfo.InvariantCulture);
			}

			return new string(chars);
		}
	}
}
```

### System Details

- FluentValidation version: 8.1.0
- Web Framework version: asp core webapi 2.2

**Comment by JeremySkinner** [comment]
Where are you seeing the RegistrationId show up? Is it in the `ValidationResult`, or somewhere else? 

Ps, just a tip, github uses 3 backticks for formatting multiline code blocks: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by piotrkolodziej** [comment]
> Where are you seeing the RegistrationId show up? 

I am using postman to query the backend. All other property names are correct but doesn't matter to what model I put 'RegistrationId' it is unchanged.

**Comment by JeremySkinner** [comment]
Sorry maybe I wasn't clear. If you invoke the validator manually (ie call the `Validate` method outside of any web application), is the property name correct in the validation result? If so, then the problem probably isn't related to FluentValidation.

**Comment by piotrkolodziej** [comment]
I will give it a go and come back with the result. Thank's for the suggestion––it's definitely the strangest thing I've seen in a while.

**Comment by piotrkolodziej** [comment]
@JeremySkinner I've figured out what is causing the problem but would LOVE to hear your comment on this. So basically the problem only occurs when one of the properties is being bind from the route instead of body.

```
[AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property)]
public class FromBodyAndRouteAttribute : Attribute, IBindingSourceMetadata
{
	public BindingSource BindingSource => BodyAndRouteBindingSource.BodyAndRoute;
}

[HttpPatch("checkin/{registrationId}")]
public IActionResult CheckIn(
    [FromBodyAndRoute] CheckInNextViewModel viewModel)
{
	// ...
}

public class CheckInNextViewModel
{
	// this is bind from ROUTE
    public int RegistrationId { get; set; }

    // other properties bind from BODY
}
```

**Comment by JeremySkinner** [comment]
The binding process can generate errors too, which don’t pass through the validation layer. For example, if there’s a data type mismatch (trying to bind a string value to an int property as an example), then this will generate a binding error. As these errors are generated internally by adp.net, not FluentValidation, none of the custom logic for property names is used. 

Does this sound like it might be what you’re encountering? If so there may be some workarounds

**Comment by piotrkolodziej** [comment]
@JeremySkinner it's not the case here. Binding went alright. I went ahead and created a small WebAPI Core project that reproduces the issue. 

([url](https://drive.google.com/file/d/1xmTLy1THKxbUqPPvEmHWQTt56o8l5yBO/view?usp=sharing))

NOTE:

- TestViewModel contains two properties, one of which (RegistrationId) goes through the route and the other (RoomDiscount) through the request body

- TestViewModelValidator fails when you provide values <= 0.

- Bindings folder contains FromBodyAndRoute attribute and related classes

Enabling the usage of the attribute causes the behaviour I reported in this issue––RegistrationId response JSON will be capitalised. 

```
.AddMvc(options =>
{
    var providers = options.ModelBinderProviders;
	var bodyProvider = providers.Single(provider => provider.GetType() == typeof(BodyModelBinderProvider)) as BodyModelBinderProvider;
	var complexProvider = providers.Single(provider => provider.GetType() == typeof(ComplexTypeModelBinderProvider)) as ComplexTypeModelBinderProvider;
	var bodyAndRouteProvider = new BodyAndRouteModelBinderProvider(bodyProvider, complexProvider);
	providers.Insert(0, bodyAndRouteProvider);
})
```

Request Copy (Postman):

```
POST /api/values/0 HTTP/1.1
Host: localhost:5000
Content-Type: application/json
cache-control: no-cache
Postman-Token: 2417b720-f1a6-4d58-8522-790a9af9bb09
{
	"RoomDiscount":2
}------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by JeremySkinner** [comment]
Ok I had a look at the application. It's not related to FluentValidation, but how ASP.NET deals with binding route parameters. 

When you call `_complexBinder.BindModelAsync(bindingContext)` inside your `BodyAndRouteModelBinder`, the recursive model-binding process kicks in and `ModelState` ends up being populated with the keys that are being bound from the route, which is always going to be "RegistrationId" with the capital R, as this is the name of the route parameter. This happens before validation kicks in.

When validation kicks in later in the pipeline, FluentValidation does the correct thing and returns "registrationId", but when MVC matches validation results to model binding keys this is to be done in a case-insentive way so error messages associated with "registrationId" end up being matched with the existing "RegistrationId" key that was generated during model-binding. as this is the actual name of the route parameter. This is all happening internally inside ASP.NET's binding and validation process.  

I can't think of any way around this - even calling `bindingContext.ModelState.Remove("RegistrationId");` inside your BodyAndRouteModelBinder doesn't help as a call to Remove on ModelState doesn't actually remove the node - "resets" it, but it remains in the collection. 

What you're trying to do doesn't really seem to be something MVC supports. It expects that the keys used for model binding will be the same keys that are sent back to the client. If you want to change this then you'll need to do it in a different place, as you need to affect the whole ModelState dictionary, not just what comes back from FluentValidation. 

One approach would be to change the default webapi behaviour of serializing ModelState directly to json and instead intercept this process, do the case conversions at the point before the response is sent. By default, the WebApi conventions use a `BadRequestObjectResult` in conjunction with `SerializableError` to do this serialization. You can provide your own class to handle the representation of the errors, rather than using the default. `SerializableError` is sealed, so you'll have to re-implement it's functionality:

```csharp
// In your app startup:
services.AddMvc()
    .ConfigureApiBehaviorOptions(options => {
        options.InvalidModelStateResponseFactory = actionContext => new BadRequestObjectResult(new MySerializableError(actionContext.ModelState));
    })
    .AddFluentValidation(...);

// Custom serializable error class that can do the conversion.
public class MySerializableError :  Dictionary<string, object>
{
    public MySerializableError()
        : base(StringComparer.OrdinalIgnoreCase)
    {
    }
    
    public MySerializableError(ModelStateDictionary modelState)
        : this()
    {
        foreach (var keyModelStatePair in modelState)
        {
            var key = keyModelStatePair.Key;
            // TODO Perform the case change on key here.
            
            var errors = keyModelStatePair.Value.Errors;
            if (errors != null && errors.Count > 0)
            {
                var errorMessages = errors.Select(error => error.ErrorMessage).ToArray();
                Add(key, errorMessages);
            }
        }
    }
}
```

I'm going to go ahead and close this issue as it's not a FluentValidation problem, but please feel free to post an update if you find a solution that you want to share.
