### ISSUE TITLE
Bubble warnings out through ASP.NET Core?

### ISSUE THREAD

**Issue by malachib** [JeremySkinner/FluentValidation#1083]
### Issue Description

Is there a way to propagate non-error severity errors (warnings, info) out to a WebAPI controller in ASP.NET Core and control it enough to spit out something other than a status 400 with `errors` json?

Thinking a 200 with a `warnings` or `info` JSON

**Comment by JeremySkinner** [comment]
Not really - this is a limitation of ASP.NET. The serialization to JSON and the generation of a 400 response [is part of web api](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#automatic-http-400-responses). It is not a feature of FluentValidation.  The only information that can be passed to ASP.NET from fluentvalidation is the property name and the error message. ASP.NET doesn't have the concept of different severeties.

Your only options are:
1) Turn off automatic validation and instead manually invoke the validator and manually serialize to JSON the validation result, rather than relying on ASP.NET to do this for you.
2) Hack the response so that the severity is included as part of the error message, which you could do by using an [interceptor](https://fluentvalidation.net/aspnet#validator-interceptors).

**Comment by malachib** [comment]
OK.  Thank you

I'm favoring the interceptor approach, will post my results here
