### ISSUE TITLE
Duplicate error messages in DataAnnotations attributes

### ISSUE THREAD

**Issue by gpufreak** [JeremySkinner/FluentValidation#1086]
My `WebApiConfig` looks like this:
```
public static void Register(HttpConfiguration config){

...

config.Routes.MapHttpRoute(
    name: "DefaultApi",
    routeTemplate: "{controller}/{id}",
    defaults: new { id = RouteParameter.Optional }
);

FluentValidationModelValidatorProvider.Configure(config);
```

My controller and model look like this:

```
public class Model
{
    [Range(0, 2)]
    public int Amount { get; set; }
}

[HttpPost]
public IHttpActionResult Create(Model model)
{
    return Ok(model);
}
```

When the validation is finished, I end up with two `Errors` in my `ModelState.Values` for the `Amount` property.  I have no any other custom validators, just FV enabled. Duplicate error messages also appear when using custom validation in a standard way (inheriting from `ValidationAttribute`).

Sorry if this issue is duplicated, but I cannot see anything related to it.

**Comment by JeremySkinner** [comment]
Hi, I don’t see how this is an issue with FluentValidation. If you remove FV from the project does the same thing happen?

Also please provide all the information requested in the issue template - which version of FV you’re using and which version of webapi

**Comment by gpufreak** [comment]
No, if I remove FV from the project, everything is working fine (i.e. I get only one error message per validation attribute per property). Just enabling FV in `WebApiConfig` introduces this error.

The package version is the latest one, FluentValidation.WebApi 8.2.0 in .NET Framework 4.6.1 project.

Thanks for the quick reply.

**Comment by JeremySkinner** [comment]
Can you put together a small/minimal sample project that reproduces the issue? I’ll then be able to take a look at it. Thanks.

**Comment by gpufreak** [comment]
https://www.dropbox.com/s/q1fh1bpr0jwmiyr/FVSample.rar?dl=0

Here you have a minimal sample. 

Uncomment in file Startup.cs at line 24 and the `POST /home` will yield two errors in the `ModelState` for the `Transaction` model property `Amount` (because of the standard `Range` validation).

**Comment by JeremySkinner** [comment]
Thanks - I'll let you know what I find.

**Comment by JeremySkinner** [comment]
I think I understand what's happening. 

By default, MVC's default validation runs in 2 phases. The first phase loops over each property, checks if the property has any validators (attributes), and invokes them. If all the properties pass validation, then a second phase is run that invokes model-level validators (which run against the entire model in one go). FluentValidation runs in this second phase.

This doesn't work well, as it prevents FluentValidation from running if any attributes on the model have failed. To get round this, FluentValidation inserts some code that allows the second phase to run even if the first phase fails. This has never been an issue before, but it looks like at some point during WebApi's development a model-level DataAnnotations validator was also introduced that re-runs all the attribute validation in the second phase. 

Normally this wouldn't happen because the first phase would prevent the second phase from running, but with FluentValidation enabled and the workaround in place, it means that DataAnnotations validation essentially runs twice, as they don't track duplicates. 

I think the solution will be to only invoke the workaround to run phase 2 when phase 1 fails in the case where there is a FluentValidation validator available for the type. So classes validated by DataAnnotations will still use the original behaviour. This does mean that you won't be able to mix DataAnnotations and FluentValidation in the same model, (but that's never been supported with WebApi anyway), but you will be able to mix them across different models. I'll try and get a hotfix out today with this. 

I'll also point out that this issue doesn't occur with ASP.NET Core WebApi - only legacy WebApi. ASP.NET Core has a much better api for external validation libraries to plug into - I would highly recommend using ASP.NET Core instead if you can as you'll get a much better experience when integrating with FluentValidation (and legacy WebApi won't be supported by FluentValidation from the next release).

**Comment by JeremySkinner** [comment]
I've pushed out 8.2.3 with the fix - it should appear in Nuget shortly. Could you give it a try and let me know if it looks ok for you?

Thanks for the help tracking this down.

**Comment by gpufreak** [comment]
Asap fixed! 
Thanks! :+1: :+1: :+1:
