### ISSUE TITLE
Email validation is different on client-side and server-side

### ISSUE THREAD

**Issue by rkapka** [JeremySkinner/FluentValidation#1131]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version: ASP.NET Core 2.2

### Issue Description

When validating an email address, typing `aaa@aaa` results in a valid value on the client-side, but the server-side validation fails. This can be confusing to end users.

**Comment by JeremySkinner** [comment]
Hi, FluentValidation's server-side validation uses a regex to perform email validation (the same regex used by the `[EmailAddress]` attribute on the full framework). 

The clientside check is not provided by FluentValidation, and just checks for the presence of a single @, which is why there's an inconsistency (which is the same behaviour as the Core version of the `[EmailAddress]` attribute).

**Comment by JeremySkinner** [comment]
What I could do for 8.x is expose an option on the email validator that allows switching between .net 4.x-style email validation and .net core-style email validation (with the default being .net 4.x), as this wouldn't then be a breaking change.

**Comment by JeremySkinner** [comment]
Implemented for 8.5

**Comment by JeremySkinner** [comment]
8.5-preview2 is now released with this change.

**Comment by rkapka** [comment]
Thank you!
