### ISSUE TITLE
ValidationException no working with ExceptionFilterAttribute

### ISSUE THREAD

**Issue by BrenMcM** [JeremySkinner/FluentValidation#1203]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):
ASP.NET Core 2.1

### Issue Description
ValidationException no working with ExceptionFilterAttribute

We have setup a CustomExceptionFilterAttribute on our .net core API to capture and handler exceptions. When our Abstract Validator fails on the controller we simply get a 400 bad request and the exception filter is missed completely  ->

    public class RegisterUserValidator : AbstractValidator<RegisterUserCommand>
    {
        public RegisterUserValidator()
        {
            RuleFor(x => x.FirstName)
                .NotEmpty();

            RuleFor(x => x.LastName)
                .NotEmpty();
    }

    public class CustomExceptionFilterAttribute : ExceptionFilterAttribute, IExceptionFilter
    {
        public override void OnException(ExceptionContext context)
        {
            if (context.Exception is ValidationException)
            {
                context.HttpContext.Response.ContentType = "application/json";
                context.HttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                context.Result = new JsonResult(
                    ((ValidationException)context.Exception).Errors);

                return;
            }
    }

When a model is send via POST request to the controller the exception filter does not fire at all unless we specifically specifiy .OnAnyFailure Rule for every single attribute

**Comment by JeremySkinner** [comment]
FluentValidation doesn't throw an exception when validation fails, which is why you can't catch it - there's nothing to catch.

FluentValidation just passes a list of validation errors to ASP.NET, which renders this as a 400 response. This is a feature of ASP.NET Core *not of FluentValidation*. If you want to turn it off or change the behavior then please read the asp.net documentation on this feature: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#automatic-http-400-responses
