### ISSUE TITLE
Bug when using OnFailure with When

### ISSUE THREAD

**Issue by DanAvni** [JeremySkinner/FluentValidation#1253]
Using version 8.5 on .NET 4.7.1 project, I have a rule that uses both a When operator and a OnFailure action. When the rule is evaluated the When operator is not executed but if I remove the OnFailure the When operator is executed.
At least on my test case then When operator evaluates to false which should have prevented the rule from running but the validation error I am getting i s referring to this rule

This was working in version 8.4

**Comment by JeremySkinner** [comment]
Please can you provide relevant code for me to reproduce the issue.

**Comment by DanAvni** [comment]
Here is a sample test
`    [Fact]
    public void WhenWithOnFailure() {
      bool shouldNotBeTrue = false;
      var validator = new TestValidator {
        v => v.RuleFor(x => x.Surname).NotEqual("foo").When(x => x.Id > 0).OnFailure(x=> shouldNotBeTrue=true)
      };

      Person p = new Person();
      p.Id = 0;
      p.Surname = "foo";
      var result = validator.Validate(p);
      result.Errors.Count.ShouldEqual(0);
      shouldNotBeTrue.ShouldBeFalse();
    }`

If you remove the call to OnFailure the test passes, if you add it back the test fails

**Comment by JeremySkinner** [comment]
Thanks. This is happening because calling `OnFailure` actually sets up a new validator that replaces (and wraps) the original `NotEqual` validator, but doing so ends up ignoring its condition. You can work around this by swapping the order of the `When` and the `OnFailure` calls, so the condition applies to the outer validator:

```
RuleFor(x => x.Surname)
  .NotEqual("foo")
  .OnFailure(x => shouldNotBeTrue = true)
  .When(x => x.Id > 0);
```

...and then it'll work as you expect. 

I'll get the other way fixed for a future release.

**Comment by DanAvni** [comment]
Note this is a breaking change from 8.4. I will wait for 8.5.1. Many thanks for all your hard work on this great library!

**Comment by JeremySkinner** [comment]
I’ve pushed out the release to nuget
