### ISSUE TITLE
Base Class Validations are not getting triggered.

### ISSUE THREAD

**Issue by fingers10** [JeremySkinner/FluentValidation#1258]
### System Details

- FluentValidation version: 8.5.1
- Web Framework version: ASP.NET Core 3.0 Razor Pages

### Issue Description

I have a class derived from base class as shown below:

```c#
public class BranchEditViewModel : BranchViewModel
{
    public Guid Id { get; set; }
    public bool Active { get; set; }
}
```

I'm trying to validate my derived class in my update method as shown below:

`public async Task<IActionResult> OnPutAsync([FromForm] BranchEditViewModel model)`

But this doesn't work for some reason.

When I create `AbstractValidator` for my base class as shown below, the validator is not getting called.

`public class BranchViewModelValidator : AbstractValidator<BranchViewModel>`

But if I create `AbstractValidator` for my dervied class as shown below, the validator is getting called.

`public class BranchViewModelValidator : AbstractValidator<BranchEditViewModel>`

Please can you assist on why this is not working with base class? Am I doing something wrong?

**Comment by JeremySkinner** [comment]
This is the expected behaviour. In your application startup when you register FluentValidation, calling `RegisterValidatorsFromAssemblyContaining` will automatically find and register validators that map one-to-one with a model type. It will not attempt to process inheritance hierarchies - you need to register these manually with the asp.net core service provider in your startup class's ConfigureServices method:

```csharp
services.AddTransient<IValidator<BranchEditViewModel>, BranchViewModelValidator>();
```

This adds the mapping, so when ASP.NET Core asks FluentValidation for a validator for the `BranchEditViewModel`, it will supply a  `BranchViewModelValidator` instead.
