### ISSUE TITLE
Handling F# option types

### ISSUE THREAD

**Issue by BrianVallelunga** [JeremySkinner/FluentValidation#1260]
### System Details
- FluentValidation version: 8.5.1

### Issue Description
I'm trying to figure out the best way to validate some of the built-in F# types such as Option. In my case I have a record with some option types, such as:

`type Model = { Name: string option }`

I want to be able to apply the standard string validators such as MaximumLength to the Name field, but I can't because the type of the field is `Option<String>` not `String`. I thought `Transform` might work, but it requires the end type to be the same as the starting type.

Similar to the the existing `When`  functionality, what I want is something like:

`base.WhenSome(fun model -> model.Name).MaximumLength(50)`

Any pointers on implementing this functionality or is there another option to achieve this?

**Comment by BrianVallelunga** [comment]
Unfortunately `x.Name.Value` will throw a null reference exception if `Name` is `None`. In the simple case of strings I can do the following, but it won't work for the general case (say a complex object that I want to add a validator for if it is not `None`).
```
base.RuleFor(fun model -> (Option.defaultValue "" model.Name))
    .MaximumLength(50).OverridePropertyName("Name")
```

I started trying to code something myself that makes use of the existing `When` functionality, but it's not quite right since it needs to take an expression instead of just an option. I'm going to keep at this, but I've never worked with expressions before. Here's the non-working code:

```
module FluentValidationExtensions
type FluentValidation.AbstractValidator<'T> with
    member xs.WhenSome<'T>(a: 'T option , b: 'T -> unit) =
        match a with
        | None -> xs.When((fun _ -> false), (fun () -> ()))
        | Some p -> xs.When((fun _ -> true), (fun () -> b p))
```

**Comment by JeremySkinner** [comment]
I can't help you with anything F#-syntax related I'm afraid, but you need to do the transformation inside the RuleFor, as this drives which validators are available on the type.

At the end of the day you need to keep in mind that FluentValidation rules can only act upon the type for which they're configured, so it's your responsibility to provide an object in the correct 'shape' to be validated. If the properties are actually of a different type or wrapped in `Option`, it's never going to work in exactly the way you want.

**Comment by BrianVallelunga** [comment]
Thanks for the pointers. I am going to pursue getting this to work and I'll happily share it if I can.

This would be significantly easier if there existed a TransformTo function such as the following completely arbitrary example:

`// Allow only numbers with a maximum length of 4`
`base.RuleFor(x => x.Number).TransformTo<string>(n => n.ToString()).MaximumLength(4);`

The trick would be to have validation fail if TransformTo itself failed and to prevent further rules from being run. I don't know what it would take to build something like this, but I'll dig into the source and take a look.

**Comment by JeremySkinner** [comment]
I wouldn't really recommend this approach. FluentValidation is explicitly built not to hide/swallow exceptions from the end user. It is intended to be used in a way that expects properties should always yield a value (or return null), but should never throw an exception.

That being said, you could implement the first bit of this easily (a TransformTo method) because the internal API is not strongly typed. The transformer is actually a `Func<object, object>` and is constrained only by the public API methods. 

```csharp
public static IRuleBuilderInitial<T, TNewType> TransformTo<T, TProperty, TNewType>(this IRuleBuilderInitial<T, TProperty> ruleBuilder, Func<TProperty, TNewType> transformer) {
	// Cast to extract the actual rule instance from the internal api.
	var actualRuleBuilder = (RuleBuilder<T, TProperty>) ruleBuilder;
	var rule = actualRuleBuilder.Rule;
	// Provide a transformation function. This is fine as the interal model requires a Func<object, object>
	rule.Transformer = value => transformer((TProperty) value);
	// Create a new RuleBuilder that has the new type as the destination.
	return new RuleBuilder<T, TNewType>(rule, actualRuleBuilder.ParentValidator);
}
```

Callable like this (you must explicitly declare all 3 generic type parameters. You can't omit T and TProperty like you did in the example):

```
RuleFor(x => x.Number).TransFormTo<ParentType, int, string>(num => num.ToString()).MaximumLength(4):
```

The issue is that if your callback throws an exception this will bubble up to the end user, halting *all* validation. In the case of null references, you'd be expected to handle it inside the callback (eg with the null coalescing operator), but at this point the example is no different to what I originally proposed (performing a null-coalescing transformation inside the initial RuleFor call).

At the end of the day it really comes down to this: FluentValidation requires you to define your rules as per their correct underlying type, and not to throw exceptions if the value can't be retrieved. If this doesn't work for you then I'd suggest that FluentValidation is probably not the right tool for you to be using.
