### ISSUE TITLE
Make email address pattern case insensitive

### ISSUE THREAD

**Issue by daniel-white** [JeremySkinner/FluentValidation#1268]
### System Details

- FluentValidation version: Any
- Web Framework version ASP.NET Core 2.1

### Issue Description

I'm using micro-elements/MicroElements.Swashbuckle.FluentValidation to bind my FluentValidation rules into a Swagger document. The OpenAPI spec says the patterns are defined to be case sensitive and it does not support flags. See: https://swagger.io/docs/specification/data-models/data-types/#pattern

The binding in the library only takes the `RegEx.Expression` property which indicates conformity with the Open API/Swagger spec. See: https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/blob/master/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationRules.cs#L177

However, FluentValidation uses the `RegexOptions.IgnoreCase` option. This is not surfaced to our Open API doc. 

I propose that the regex be changed to support upper case character classes (i.e. `[a-z]` -> `[a-zA-Z]`.

Aside, what's the motivation of changing the validator for ASP.NET Core to be a simple `@` check?

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion, but this isn't something we'll implement. 

The email address validation in FluentValidation is intentionally designed to match the behaviour of the `EmailAddressAttribute` that's part of System.ComponentModel.DataAnnotations. 

This is done for consistency, so that the two behave in the same way. For .NET 4.x, this was done with a regular expression, so FluentValidation uses essentially the same one (with a couple of minor fixes). At this point the regex in FluentValidation is not something that's going to change because a) this would diverge from the behaviour of the  .NET 4.x EmailAddressAttribute, and b) maintaining/updating/testing a regex like this is hard, complex and extremely time consuming. 

For .NET Core, the `EmailAddressAttribute` was changed to perform a simple @ check, so FluentValidation has done the same to match it for consistency. Validation of email addresses by regex is generally considered these days to be undesirable - [please see the discussion on the corefx repo.](https://github.com/dotnet/corefx/issues/32740#issuecomment-466578595)

If you *really* want to use a regex for email validation then you're still welcome to do so - you can use FluentValidation's `Matches` validator [to use whatever regex you like](https://fluentvalidation.net/built-in-validators#regular-expression-validator), but the standard email validator behaviour is not going to change at this point. 

Hope that makes sense.
