### ISSUE TITLE
Question: Is it possible to load validation rules from a configuration file?

### ISSUE THREAD

**Issue by swidz** [JeremySkinner/FluentValidation#1272]
Hi, I would like to add validation rules for `DataRows `in `DataTable`. The problem is that the table schema is not static. Users can define multiple sql queries which results are returned as `DataSet`/`DataTable`. I would like to create some sort of configuration file that would be created for each sql query. 
When running a validation i would loke to point to particular ruleset ID that would relate to a given sql query.

Could you guide me with some examples or just point me the direction how could I approach that?

The static solution example could be as follows, but I would like to load the rule sets from a json/xml file

```
using FluentValidation;
using System.Data;
using System.Linq;

namespace MyValidation
{
    public class MyDataTableValidator : AbstractValidator<DataTable>
    {
        public MyDataTableValidator()
        {
            //TODO Read Rule sets from confiuration file
            
            RuleSet("query1", () =>
            {
                RuleForEach(dt => dt.Rows.Cast<DataRow>())
                    .Must(row => (row["<columnName>"] as int?) > 0)
                    .WithName("Rows")
                    .WithMessage((dt, row) =>
                        {
                            return $"Row {row["<idcolumn>"]} Field {dt.Columns["<columnName>"].ColumnName}: Value must have amount greater than 0.";
                        });
            });

            RuleSet("query2", () =>
            {
                RuleForEach(dt => dt.Rows.Cast<DataRow>())
                    .Must(row => (row["<columnName>"] as int?) < 0)
                    .WithName("Rows")
                    .WithMessage((dt, row) =>
                    {
                        return $"Row {row["<idcolumn>"]} Field {dt.Columns["<columnName>"].ColumnName}: Value must have amount less than 0.";
                    });
            });
        }
    }
}

```

**Comment by JeremySkinner** [comment]
Hi there, FluentValidation is not the right tool to be using to solve this. 

The whole point of FluentValidation is to provide a way to build validation rules in a strongly-typed way at compile time. Dynamic generation of rules from an external source is outside the scope of this project, so you’d be better off using a different tool.

**Comment by swidz** [comment]
Hi, Thanks for explanation. I understand that this is not in scope, but is there any reason why this can't be done with the current design? Sorry, I have not dug into the code at all, I prefer to ask first.

**Comment by JeremySkinner** [comment]
You‘d need to dig into FluentValidation’s internal api. The main class is `PropertyRule` which represents an individual call to RuleFor. It essentially contains a reference to the lambda expression (passed to RuleFor) which is used to retrieve both the property value and the name of the property. It also contains a collection of validators to be applied to the property value (each inheriting from `PropertyValidator`)

To load rules dynamically you would have to manually construct an expression tree representing the property you want to validate and use this to create the PropertyRule instance. 

But I’ll reiterate that this is not an intended or supported use of the library. If you go down this route then you’ll have defeated the whole point of the library (strongly typed rules built with a fluent interface), as your rules are no longer strongly typed or built with a fluent interface. 

 I would again urge you to look elsewhere if this is an important requirement for you, rather than trying to hack FluentValidation to do something that’s the opposite of what it was intended to do.

**Comment by swidz** [comment]
Yes, you are right, I will need to find some other solution. Thanks again, hope there will be tones of projects I could use your solution as it looks really great! Best regards, Sebastian
