### ISSUE TITLE
Client-side validation will not generate for validators not attached to a particular property

### ISSUE THREAD

**Issue by pni-jkeyser** [JeremySkinner/FluentValidation#1281]
### System Details

- FluentValidation version: 8.6.0
- Web Framework version: ASP.NET Core 3.1

### Issue Description

I was using the example code found at https://ml-software.ch/posts/extending-client-side-validation-with-fluentvalidation-and-jquery-unobtrusive-in-an-asp-net-core-application to create my own custom validator with custom client-side validation. But no matter what I tried, the factory method that was registered using ConfigureClientsideValidation() to create my equivalent of the RequiredIfClientValidator object would never be called. After much investigation, I discovered the problem was because I was attaching my validator to the view model as a whole instead of to a particular property. For example, I was calling:

RuleFor(x => x).SetValidator(new RequiredIfValidator());

instead of:

RuleFor(x => x.PropertyName).SetValidator(new RequiredIfValidator());

This ultimately appears to have caused the calculation of shouldExecute in the method FluentValidationClientModelValidatorProvider.GetModelValidator() to always be false and the factory method to never be called.

The particular validator I am working on applies to multiple properties on the view model (the user must select at least one of X, Y and Z) and does not make sense being attached to a single property. But I will rework that in the short term to get this working.

Thanks.

**Comment by JeremySkinner** [comment]
Hi, I'm afraid that this is the expected behaviour.

This is one of the many limitations of integration with ASP.NET Core's client-side validation. Only a small subset of rules can be converted to client-side equivalents, and only when they're attached to specific properties. Anything that isn't attached to a property can't be converted to a client-side rule (this includes model-level rules like you're using, but also rules attached to method calls, or anything else where the expression passed to RuleFor is not a simple member access expression). 

Please keep in mind that FluentValidation is a server-side validation framework - that's its purpose and goal. We provide a limited integration with ASP.NET Core's clientside attribute generation, but it is far from perfect and is only suitable for simple use cases. If you are trying to do anything complex or more involved you will be much better off writing the clientside javascript yourself rather than trying to rely on this very limited translation layer. 

Hope that makes sense.

**Comment by pni-jkeyser** [comment]
I was afraid I might have to go down the route of completely custom client-side validation. OK, thanks for the insight.
