### ISSUE TITLE
DI

### ISSUE THREAD

**Issue by managerger** [JeremySkinner/FluentValidation#1286]
I've faced an issue, while trying to set a validator for collection of objects. I inject a validator for each instance in the following way:
`RuleForEach(m => m.Users).InjectValidator((sp, cntx) => sp.GetService<BaseUserValidator<BaseUser>>());`
But when I use `RuleForEach(m => m.Users).InjectValidator((sp, cntx) => new BaseUserValidator<BaseUser>());` then everything works just fine. My best guess was that framework could'nt register `BaseUserValidator<T>`, because it doesn't work with open generics. Do we have a way to fix that?

**Comment by JeremySkinner** [comment]
Hi, this isn’t really related to FluentValidation. It just means you havent registered it with the service provider, which you should do in your application’s ConfigureServices method. Just register it as an open generic and then you’ll be able to resolve it as necessary.

**Comment by managerger** [comment]
#1287

**Comment by JeremySkinner** [comment]
FluentValidation intentionally only registers validators with one to one mappings as the simple use case. 

Open generics are much less clear cut as it is not obvious what the default behaviour should be for these as they can be used in many different ways (which then becomes more complex when you take into account multiple type parameters, type constraints and covariant/contravariant constraints in genetics). Because of this FluentValidation intentionally does not handle them out of the box - it is your responsibility as the developer to express your intent how these should be used by registering them in the way that is most appropriate for your application. 

FluentValidation won’t be changed to auto register these.

**Comment by managerger** [comment]
Yeah, now I see your point. That make sense. Thanks)
