### ISSUE TITLE
Use property value instead of property name?

### ISSUE THREAD

**Issue by bdaniel7** [JeremySkinner/FluentValidation#1296]
I have an entity that contains a list:

```
RuleForEach(m => m.AffectedCountries)
	.SetValidator(new AffectedCountriesValidator());

```
```
public class AffectedCountriesValidator : AbstractValidator<AffectedCountryDto>
{
	public AffectedCountriesValidator()
	{
		RuleFor(mac => mac.ValidFrom)
			 .NotNull()
			 .NotEmpty()
			 .WithName(m => m.Name)
			 .WithMessage("Implementation Date is mandatory.");

		RuleFor(mac => mac.ValidTo)
			 .GreaterThan(m => m.ValidFrom)
			 .When(m => m.ValidTo.HasValue)
			 .WithName(m => m.Name)
			 .WithMessage("Repeal Date must be after Implementation Date.");
	}
}
```

In the error message that is displayed, I would like to have the actual Country name displayed instead of "Name" or "AffectedCountries[5].Name".

Is it possible?

**Comment by JeremySkinner** [comment]
Hi there, I'm struggling to understand what you're trying to do. I think you might have confused the difference between the *property name* and the *display name*. 

All rules are associated with a particular property (that is, the property that you specify with `RuleFor`). So for `RuleFor(mac => mac.ValidTo)` the *property name* will be "ValidTo" and the *display name* will be "Valid To" (with a space). The default message will be `'Valid To' must be greater than or equal to '<value>'` (using the *display name*). In the result list, it'll be associated with `AffectedCountries[5].ValidTo` (using the property name). 

In your example, you call `WithName`, which overrides the display name, but you also also call `WithMessage` to override the message. Because your new message doesn't use the display name placeholder, there isn't actually any point in calling `WithName` here. (remember WithName changes the display name, which is the version of the property name used in the error message. But your message doesn't contain the display name anymore). 

If you want to change the property that the error message is associated with in the results collection (ie change the property name, not the display name), then you can do this by calling `OverridePropertyName` (rather than WithName) but note that this must be the *name* of a property, not the *value* of a property. 

Hope that clears up the difference between the two. 

If you're still having issues perhaps you could provide some more detail on what exactly you're trying to see.

**Comment by bdaniel7** [comment]
Sorry, please ignore the ".WithName ()" call.
What I need is the value of a property, used instead of the property name.
Like **"Anguilla: Implementation date is mandatory."**, where "Anguilla" is the country name.

The end users are not computer savvy, but they do know their business, so "AffectedCountries[5].ImplementationDate: Implementation date is mandatory" would not make much sense to them.

**Comment by JeremySkinner** [comment]
I'm not sure where you're seeing a message like "AffectedCountries[5].ImplementationDate: Implementation date is mandatory" coming from. 

FluentValidation's messages don't include the property path as a prefix. The message from FluentValidation is just the "Implementation date is mandatory" part. I expect there's something in your application that's pre-pending the property name at the point it's displayed, but this isn't coming from FluentValidation.

**Comment by JeremySkinner** [comment]
Once you've found the code in your application that's pre-pending the property name, you'll then be able to modify the message in your validator to embed the country name, eg something like:

` .WithMessage(x => x.CountryName +  ": Repeal Date must be after Implementation Date.");`

Hope that helps

**Comment by bdaniel7** [comment]
Ok, thanks for the pointers.
