### ISSUE TITLE
Global OnFailure configuration

### ISSUE THREAD

**Issue by EdLorenzQAT** [JeremySkinner/FluentValidation#1311]
First thing, Great job with this library!
I'm wondering about being able to configure a failure type callback at a global level, for every rule.
As opposed to having to configure this at the individual rule-level as indicated here: https://fluentvalidation.net/start#callbacks
The idea is to be able to log all validation errors, or not, and not depend on the individual AbstractValidator instance to handle/code this.
Thanks,
Ed

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion.

If you want to do something global like this, the usual approach would be to use a base class that inherits from `AbstractValidator<T>` and overrides the `Validate` method. All your logging can take place in there, inspecting the validation results collection. All of your own validators can then inherit from this class instead of AbstractValidator directly. Would this work for you, or is there a specific reason why you'd need a global callback to do it?

**Comment by EdLorenzQAT** [comment]
Ah okay, that's a great idea and should work great for me :)
Thanks,
Ed
