### ISSUE TITLE
Client side validation for bool value

### ISSUE THREAD

**Issue by prince272** [JeremySkinner/FluentValidation#1314]
Please about this issue can you help me support asp core 3? There is a solution here. https://stackoverflow.com/questions/9808794/validate-checkbox-on-the-client-with-fluentvalidation-mvc-3

**Comment by prince272** [comment]
The implementations are different with asp.net mvc 3.

Here:
public class EqualToValueFluentValidationPropertyValidator : FluentValidationPropertyValidator
{
    public EqualToValueFluentValidationPropertyValidator(ModelMetadata metadata, ControllerContext controllerContext, PropertyRule rule, IPropertyValidator validator)
        : base(metadata, controllerContext, rule, validator)
    {
    }

    public override IEnumerable<ModelClientValidationRule> GetClientValidationRules()
    {
        if (!this.ShouldGenerateClientSideRules())
        {
            yield break;
        }
        var validator = (EqualValidator)Validator;

        var errorMessage = new MessageFormatter()
            .AppendPropertyName(Rule.GetDisplayName())
            .AppendArgument("ValueToCompare", validator.ValueToCompare)
            .BuildMessage(validator.ErrorMessageSource.GetString());

        var rule = new ModelClientValidationRule();
        rule.ErrorMessage = errorMessage;
        rule.ValidationType = "equaltovalue";
        rule.ValidationParameters["valuetocompare"] = validator.ValueToCompare;
        yield return rule;
    }
}

and then here too.
FluentValidationModelValidatorProvider.Configure(provider =>
{
    provider.AddImplicitRequiredValidator = false;
    provider.Add(typeof(EqualValidator), (metadata, context, description, validator) => new EqualToValueFluentValidationPropertyValidator(metadata, context, description, validator));
});

but i think this might work.
(function ($) {
    $.validator.unobtrusive.adapters.add('equaltovalue', ['valuetocompare'], function (options) {
        options.rules['equaltovalue'] = options.params;
        if (options.message != null) {
            options.messages['equaltovalue'] = options.message;
        }
    });

    $.validator.addMethod('equaltovalue', function (value, element, params) {
        if ($(element).is(':checkbox')) {
            if ($(element).is(':checked')) {
                return value.toLowerCase() === 'true';
            } else {
                return value.toLowerCase() === 'false';
            }
        }
        return params.valuetocompare.toLowerCase() === value.toLowerCase();
    });
})(jQuery);

**Comment by JeremySkinner** [comment]
Hi.

It's a bit of work, but definitely doable. The clientside validation API is different between MVC5 and ASP.NET Core, but the principles are similar.

Step 1: Create an implementation of `Microsoft.AspNetCore.Mvc.ModelBinding.Validation.IClientModelValidator` for your equal validator. You can use the `FluentValidation.AspNetCore.ClientValidatorBase` base class to get you started:

```csharp
public class EqualToValueClientValidator : FluentValidation.AspNetCore.ClientValidatorBase {
	private readonly IClientModelValidator _originalEqualValidator;

	public EqualToValueClientValidator(PropertyRule rule, IPropertyValidator validator, IClientModelValidator originalEqualValidator) : base(rule, validator) {
		_originalEqualValidator = originalEqualValidator;
	}

	public override void AddValidation(ClientModelValidationContext context) {
		var equalValidator = (EqualValidator) this.Validator;

		// Only want to generate clientside attributes if we're comparing with a boolean.
		if (equalValidator.ValueToCompare is bool comparisonValue) {
			MergeAttribute(context.Attributes, "data-val", "true");
			MergeAttribute(context.Attributes, "data-val-equaltovalue", GetErrorMessage(equalValidator, context));
			MergeAttribute(context.Attributes, "data-val-equaltovalue-value", comparisonValue.ToString().ToLower());
		}

		// Delegate the remaining tasks to the original equal to client validator.
		_originalEqualValidator.AddValidation(context);
	}

	private string GetErrorMessage(EqualValidator equalValidator, ClientModelValidationContext context) {
		var formatter = FluentValidation.ValidatorOptions.MessageFormatterFactory()
			.AppendPropertyName(Rule.GetDisplayName())
			.AppendArgument("ComparisonValue", equalValidator.ValueToCompare);

		string messageTemplate;
		try {
			messageTemplate = equalValidator.Options.ErrorMessageSource.GetString(null);
		}
		catch (FluentValidationMessageFormatException) {
			messageTemplate = FluentValidation.ValidatorOptions.LanguageManager.GetStringForValidator<EqualValidator>();
		}

		string message = formatter.BuildMessage(messageTemplate);
		return message;
	}
}
```

The main thing to note in here is implementing the `AddValidation` method. This retrieves the value you're comparing against (`true`) from the `EqualValidator` where the rule is defined, and adds the clientside validation attributes (the convention is slightly different from MVC5). I used `data-val-equaltovalue` to contain the error message and `data-val-equaltovalue-value` to contain the value you're comparing against (true/false)

The `GetErrorMessage` method is for building the default error message from your `RuleFor` definition, and handles generating a default message if your rule doesn't define one.

Note that we also accept an instance for the original clientside validator. That's because MVC supports generating clientside rules for "cross-property" comparisons (ie PropertyA == PropertyB), and we want to preserve this behaviour. 

Next, you'll need to add this to the validator providers list. This is done in your application's startup routine at the point where you already call `AddFluentValidation` (in `ConfigureServices`):

```csharp
services
	.AddMvc()
	.AddFluentValidation(fv => {
		fv.RegisterValidatorsFromAssemblyContaining<MyValidator>();

		// This is the new bit:
		fv.ConfigureClientsideValidation(clientside => {
			// Preserve the existing "EqualTo" clientside validator
			// as this handles cross-property comparisons, which is a supported scenario.
			var originalEqualFactory = clientside.ClientValidatorFactories[typeof(FluentValidation.Validators.EqualValidator)];
			// Now add in our new one.
			clientside.ClientValidatorFactories[typeof(FluentValidation.Validators.EqualValidator)] = (context, rule, validator) => {
				var originalClientsideValidator = originalEqualFactory(context, rule, validator);
				return new EqualToValueClientValidator(rule, validator, originalClientsideValidator);
			};
		});
	});
```
 
Finally, you'll need to update your javascript to check for the updated attributes. I'll leave that to you, as it's not related to FluentValidation. 

Hope that helps.

**Comment by prince272** [comment]
Okay. Thanks for your help. I realy appreciate it.
