### ISSUE TITLE
How to use FluentValidation with Web Api 2.0?

### ISSUE THREAD

**Issue by chobo2** [JeremySkinner/FluentValidation#157]
I am trying to use Fluent Validation in a web api 2 project but I can't get the Model State to work. I downloaded FluentValidation.WebAPI 5.6.2 and added this line to my Application_Start

      FluentValidationModelValidatorProvider.Configure(GlobalConfiguration.Configuration);

Then in my model I added

 [Validator(typeof(LotValidator))]

yet my ModelState.IsValid is always valid. I don't know what I am missing or if it the fact that I have my model in a different class project(though I do reference FluentValidation 5.6.2) in the project that contains my models.

**Comment by JeremySkinner** [comment]
That should be all you need to do...so I'm not sure why that wouldn't be working. What does your action look like?

**Comment by chobo2** [comment]
Hi

It was something like this:

    public IHttpActionResult Put(JToken lot)
        {
                     
            try
            {
                var lot = lotService.Update(lot);
                 if (ModelState.IsValid)
                    return BadRequest(ModelState));
					
                return Ok(lot);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

How can I debug it to figure out what is happening.

**Comment by chobo2** [comment]
I made a simple webapi project. Still getting this error maybe you can see what I did wrong.

http://1drv.ms/1Nn5qdZ

**Comment by JeremySkinner** [comment]
So in the sample project, you're invoking the validator manually. When you do that, the results won't be copied into the ModelState. 

ModelState is part of ASP.NET MVC/WebApi - it isn't something FluentValidation knows about when you invoke validator.Validate() 

However, if you're using FluentValidation's automatic MVC/WebApi integration (and not calling Validate), then the results will be populated automatically. To enable this, you'll need to make sure you rely on WebApi's automatic model binding and have the object passed in as a parameter. This way, the ValidatorFactory will then be asked to provide the validator, and validation will happen transparently. 

Take a look at this page - it's for MVC rather than WebApi, but the concepts are the same: 
https://github.com/JeremySkinner/FluentValidation/wiki/h.-MVC

**Comment by chobo2** [comment]
Cool. I will look into that. I need to manually validate due to rulesets I have but it seems like there might be a solution for that already(results.AddToModelState(modelstate, null);).

**Comment by JeremySkinner** [comment]
Yep, you can use AddToModelstate for that, although the currently released
version only has this for MVC projects (there is support for it in webapi
in git though, just not released yet - the code for it is very trivial so
you could just copy it into your project rather than rebuilding FV from
source)

**Comment by akamud** [comment]
@chobo2 as stated above by @JeremySkinner, the code is very trivial, you should just copy [this class](https://github.com/JeremySkinner/FluentValidation/blob/e35394de8e75ce5300555242b525818620b56be1/src/FluentValidation.WebApi/ValidationResultExtension.cs) to your project.
