### ISSUE TITLE
Question about the design / odd decision in the framework

### ISSUE THREAD

**Issue by avifatal** [JeremySkinner/FluentValidation#169]
Hi,
I am using this framework for 5 years and I always had something odd about it in my mind, so I decided to break the ice and ask.
Why do we have to go through NotEmpty at each validator / rule.
when you do this: 
```RuleFor(x => x.FullName).Length(5,60);```

Isnt not empty implicit in this example context? why empty FullName will be valid here?
Isnt that odd? even more, it looks like a potential future bug.... pitfally..
Do I have a point?

**Comment by JeremySkinner** [comment]
Good question....each validatator that's part of FluentValidation is
designed to do one job, and ideally mirrors the same way you'd write the
code if you were writing it procedurally.

In this case, the LengthValidator's only job is to measure the string's
length. If it's not able to do this (because of a null), then it should be
the responsibility of some other component to decide how the null should be
handled (ie the NotNullValidator or NotEmptyVLidator).

In the same way, if you were writing this procedurally, you'd need to
include a null-check, or you'd get a NullReferenceException when inspecting
string.Length.

Hope that makes sense.

**Comment by Lechus** [comment]
Hi @JeremySkinner 
TAken from example on your site:
..
RuleFor(customer => customer.Address).Length(20, 250); <-- There is no test for null or empty?

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
