### ISSUE TITLE
Need .NET 4.6 and 4.6.1 build

### ISSUE THREAD

**Issue by solset-ccochran** [JeremySkinner/FluentValidation#176]
.NET 4.6 and 4.6.1 should be represented in the NuGet package. January 12th is coming soon and developers are upgrading to supported .NET versions.  https://support.microsoft.com/en-us/gp/framework_faq/en-us

**Comment by JeremySkinner** [comment]
I'm afraid that I'm not going to have the time to implement this anytime soon - if you (or anyone else) would like to add support for this, then a pull request would be greatly appreciated.

**Comment by Kukkimonsuta** [comment]
I believe there is no need to build new packages. This message simply states, that only `.NET 4.5.2 / 4.6 / 4.6.1` are supported versions installed on your machines, but since they are just drop in replacements for `.NET 4.x` you don't have to rebuild libraries or apps that target any previous versions (see point 6.).

**Comment by JeremySkinner** [comment]
Thanks - that's good to know!

**Comment by solset-ccochran** [comment]
Thanks... I missed that.

I was having a severe performance problem that ended up being the logging provider. Thought it might be an incompatibility with FV on 4.6.1.






-------- Original message --------

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the issue appears to be resolved and there hasn't been any activity for a few months.
