### ISSUE TITLE
Using "WithName" and "WithMessage" in a RuleSet

### ISSUE THREAD

**Issue by justsayno** [JeremySkinner/FluentValidation#193]
Hi Jeremy,

From looking through the code and doing some testing it seems that when you use a RuleSet you cannot use the WithName or the WithMessage at all? You just get the default message for whatever it is. For example I have a rule like this:

```
RuleSet(ValidationRuleSets.PropertyCalculationsModelForProjectionsValidator.HAS_PROPERTY_VALUE, () =>
            {
                RuleFor(c => c.CurrentValue)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotNull()
                .Must(cr => cr.Error == false)
                .WithName("Current valuation")
                .WithMessage("No {PropertyName} found for the property");
            });
```

if the `c.CurrentValue` is null I get a "'CurrentValue' cannot be empty" error rather than what I have defined as the message. I looked into the source and see that the extension method that has the 'ruleSet' param calls the `validator.Validate(ValidationContext)` overload which then creates a `child` context...

Is there no way to use WithMessage and RuleSets? Or am I not understanding correctly.

**Comment by JeremySkinner** [comment]
WithName and WithMessage work just fine in rulesets.

However, In your example you're applying the name and the message to the Must validator, not the NotNull validator, so if the NotNull fails it'll have the default message. 

Messages are per validator. If you want them on the NotNull rather than the Must, then you need to put them directly after the call to NotNull.

**Comment by justsayno** [comment]
Ahh i did not realize that. Thanks a lot for being so helpful. This is a great library
