### ISSUE TITLE
Constructor injection in validators

### ISSUE THREAD

**Issue by Ibrahim-Islam** [JeremySkinner/FluentValidation#204]
Is it possible to do something like below:

```csharp
public class CustomerCreateValidator : AbstractValidator<CustomerViewModel>
{
    readonly ApplicationUserManager _userManager;
        
    public CustomerCreateValidator(ApplicationUserManager userManager)
    {
        _userManager = userManager;
            
        RuleFor(c => c.Email).Must(EmailExist).WithMessage("Email is already registered");
    }

    bool EmailExist(string email)
    {
        return _userManager.FindByEmail(email) != null;
    }
}
```
I have `ApplicationUserManager` registered in my UnityConfig.

**Comment by JeremySkinner** [comment]
Yes that's perfectly possible. FluentValidation  validators are no
different from any other class so you can inject whatever you like.

**Comment by Ibrahim-Islam** [comment]
@JeremySkinner  Actually, I get an exception saying that there were no parameterless constructor found. Once I added another parameterless constructor the validator fired as expected. I followed the MVC integration tutorial from the Wiki.

**Comment by JeremySkinner** [comment]
That'll be because you're using the built-in validator factory which relies
on attributes. You need to use a custom ValidatorFactory implementation
that calls into your container to instantiated the validator. Check this
page in the documentation:
https://github.com/JeremySkinner/FluentValidation/wiki/i.-IoC

**Comment by Ibrahim-Islam** [comment]
I think the doc says how to inject a validator but if you will see my code I want to actually inject something into the validator itself. I am not seeing any example to do this.

**Comment by JeremySkinner** [comment]
I think you misunderstood my last comment.

In order to inject something into your validator, you need to create the
validator *using the ioc container*. This means the validator must be
registered with the container. You then need a custom validator factory
that will call into your container to create the validator instance, which
is what the page I linked to explains how to do.

**Comment by SeanKilleen** [comment]
Maintenance / Cleanup: closing because the question appears to be answered and there hasn't been any activity in a few months.
