### ISSUE TITLE
Resolve<Validator>

### ISSUE THREAD

**Issue by StevenTCramer** [JeremySkinner/FluentValidation#207]
I have Commands that take Id's.  I want to validate that the Id exists in the Database. I am using a IOC container to instantiate my top level Validators.  If I use a `SetValidator` that needs parameters I have to either pollute the constructor of the CommandValidator to also take this dependency, or reference the IOC Container directly.  It would be great if I could use the same ValidatorFactory to resolve a down line Validator.

`RuleFor(aCommand => aCommand.ProjectId).ResolveValidator<ProjectIdMustExistValidator>()`

Or is there a better way to accomplish my goal?

Example
`        public class CommandValidator: AbstractValidator<Command>
        {
            public CommandValidator()
            {
                RuleFor(aCommand => aCommand.ProjectId)
                    .NotNull()
                    .SetValidator(new ProjectIdMustExistValidator(DbContext));
            }
        }`

**Comment by JeremySkinner** [comment]
There isn't really a way to do what you want I'm afraid. The validator has no way of knowing about the factory that created it, and this isn't something I'm keen to introduce as use of a validator factory is entirely optional (the only people who tend to use it are those relying on the automatic MVC integration). 

Also, the way that rule creation works, is that the rule builder has no knowledge of the validator that created it, so even if the validator had a way of knowing how it was created, the rulebuilder would still be isolated from this. 

Even if we did introduce a way of passing the factory down to the rulebuilder, syntatically it'd look pretty horrible. Due to the way that generic type inference works, a call to SetValidator(validator) means you can omit the 2 generic parameters (the type of the parent validator, and the type of the property being validated). A ResolveValidator<T> method would actually be defined as ResolveValidator<TRootValidator, TProperty, TChildValidator>, which would then look like this, as you can no longer rely on type inference:

```
RuleFor(aCommand => aCommand.ProjectId).ResolveValidator<CommandValidator, WhateverTheTypeOfProjectIdIs, ProjectIdMustExistValidator>()
```

Finally, this would introduce an inconsistency as IValidatorFactory is only used to create IValidator instances, but SetValidator can be used with both IValidator and IPropertyValidator (which is its primary purpose).

So overall I don't think this is something that is going to make it into the core...I'd really recommend sticking with the regular constructor injection approach, or if you really don't like that then your only other option is to reference the container directly inside the root validator.

**Comment by StevenTCramer** [comment]
Thanks for the well thought out response and excellent product.  I am leaning toward constructor pollution for now.  If it bothers me too much,  I will revisit later.  Thanks again.
