### ISSUE TITLE
Validate specific property with IValidator<T>

### ISSUE THREAD

**Issue by chrisklepeis** [JeremySkinner/FluentValidation#225]
In my WPF application, I have a base class with this:

```
public IValidator<T> Validator;

Validator.Validate(this, propertyName);
```

It's saying that Validate does not accept 2 parameters, even though intellisense is telling me otherwise.

How would I use a generic IValidator, which will be assigned at runtime to my base class and can validate specific properties?

**Comment by JeremySkinner** [comment]
The methods for validating individual properties are defined in an extension method, so you need to have the 'FluentValidation' namespace imported in order for the compiler to find them.

**Comment by chrisklepeis** [comment]
Yes, I have the `import FluentValidation;`

I may be SOL... there doesn't appear to be a way (to my knowledge) to utilize a generic IValidator that plays nice with INotifyPropertyChanged in a generic base class for my models. Here's what I have:

```
using FluentValidation;
using Prism.Mvvm;
using System;
using System.Collections;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace SO.Models
{
    public abstract class ValidatableBindableBase<T> : BindableBase, INotifyDataErrorInfo
    {
        public IValidator<T> Validator;

        public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;

        public bool HasErrors
        {
            get
            {
                throw new NotImplementedException();
            }
        }


        protected override bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)
        {
            var result = base.SetProperty(ref storage, value, propertyName);

            if (Validator != null && result && !string.IsNullOrEmpty(propertyName))
            {
                Validator.Validate(this, propertyName);
            }
            return result;
        }

        public IEnumerable GetErrors(string propertyName)
        {
            throw new NotImplementedException();
        }

        public void AttachValidator(IValidator<T> validate)
        {
            if (Validator != null)
                throw new InvalidOperationException("Validator already set");

            Validator = validate;
        }
    }
}
```

Be nice if I could use the non-generic IValidator, but I recall reading something on codeplex that it wasn't a direction FluentValidation wanted to go.

I'm trying to create a base class so that I don't have to customize each one of my models to get validation with IDataErrorInfo

**Comment by JeremySkinner** [comment]
So this is because of the generics. Your validator is defined as `IValidator<T>`, meaning it'll only accept a "T" to validate. However, in your SetProperty call, your're passing in "this" to the validator, which isn't an instance of T, but a `ValidatableBindableClass<T>`. The compiler won't like this.

I'm guessing your classes are defined as `class Foo : ValidatableBindableClass<Foo>` ?

If so, then you can probably just do a cast and it'll all be fine: validator.Validate((T)this)

**Comment by JeremySkinner** [comment]
Also, regarding the non-generic IValidator, you **can** do property validation with this. The extension methods aren't available on IValidator, because it's not part of the 'public' API, but you can still do it by passing in an IValidatorSelector. The extensions for property validation are just a wrapper around this. Check out the code for those extensions and it'll show you how:

https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/DefaultValidatorExtensions.cs#L814

**Comment by chrisklepeis** [comment]
Yes, that's exactly how I wanted to do it.

I've tried `Validator.Validate((T)this, propertyName);`

Says it can't convert ValidatableBindableBase<T> to T ... so I tried modifying the class with 

... ok stopping mid sentence... I may have it working

```
    public abstract class ValidatableBindableBase<T> : BindableBase, INotifyDataErrorInfo
        where T :ValidatableBindableBase<T>
```

`Validator.Validate((T)this, propertyName);`

Going to look into the extensions you linked to. Thanks!

**Comment by chrisklepeis** [comment]
For anyone coming across this thread, this is the extension method I created:

```
    public static class IValidatorExtensions
    {
        public static ValidationResult Validate<T>(this IValidator validator, T instance, params string[] properties)
        {
            var context = new ValidationContext<T>(instance, new PropertyChain(), ValidatorOptions.ValidatorSelectors.MemberNameValidatorSelectorFactory(properties));
            return validator.Validate(context);
        }
    }
```

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the question appears to be resolved.
