### ISSUE TITLE
Validations performance

### ISSUE THREAD

**Issue by davidop** [JeremySkinner/FluentValidation#228]
Hi.I have a fairly complex validator associated with an object. Then I have a list of the same object associated with a datagrid and by modifying one of the objects need to validate all objects from the list. This causes poor performance of my application. What can I do?

**Comment by JeremySkinner** [comment]
Hi

Have you done any tracing to see which part of the validation process is
slow?

Also, are you creating your validator as a singleton, of are you
instantiating it each time you're validating? Instantiating a validator is
slow, due to the expression tree parsing, so once they've been created they
should be cached and the instances reused.

**Comment by davidop** [comment]
How you can create the validator as a single product? How I can activate the cache validator level? This is the head of my validator:

`public class MyClassValidator : AbstractValidator<MyClassViewModel>`

**Comment by JeremySkinner** [comment]
I'd typically use an IoC container (eg structuremap) to instantiate my validators, and I'd have this handle the object lifetime as a singleton.

**Comment by davidop** [comment]
Thank you very much for the reply.
