### ISSUE TITLE
Null model handling in Web Api Validation

### ISSUE THREAD

**Issue by Amit1150** [JeremySkinner/FluentValidation#255]
How fire validate method when my model is null. 

I have tried to override validate method but it doesn't work. 
```
public class NullReferenceValidator<T> : AbstractValidator<T>
    {
        public override ValidationResult Validate(T instance)
        {
            return instance == null
                ? new ValidationResult(new[] { new ValidationFailure(instance.ToString(), "Entity can not be null.", "Error") })
                : base.Validate(instance);
        }
    }
```

Inherit me my `Validator `with above class. But It seems `Validate `method is not getting called in case of null model.

**Comment by JeremySkinner** [comment]
Hi,

That's actually the correct behaviour. FluentValidation is designed to
validate the properties of an object (eg a viewmodel/input model scenario
where the object represents the state of a screen), so it must be non-null
in order to run. You need to ensure the object is not null before passing
it to FluentValidation.

**Comment by Amit1150** [comment]
Hello Jeremy, 

Thanks for your quick response. As I'm using it with web API. so It might be possible, API action didn't receive the model object. So how can I initialize a model object(In case of null) before validation get fired, And `ModelState.Isvalid`  return `false`.

**Comment by JeremySkinner** [comment]
I can't really help you with webapi I'm afraid, as I don't have any experience with that...all I'd suggest is in the case where the model object comes into the controller as null, then manually add an error message to the ModelState instead of trying to use FV.

**Comment by waynebrantley** [comment]
Even if no data comes in for webapi, it construct the model object always - just like the MVC part.  How can your model be null?

**Comment by Amit1150** [comment]
@waynebrantley : In Web API, model object is null , when User doesn't pass any data. for e.g (**Postman**, a chrome extension for web api testing), When you send empty body then your model object will be null)

**Comment by nicklbailey** [comment]
@waynebrantley @Amit1150 is correct, WebApi will bind the default value of the model type (null for reference types), if it cannot parse the request body, url segment, or query string parameter (for example, if the user passes in malformed JSON.

@Amit1150 it seems like your problem is rather trivially solved by 
`
 if (model == null)
 {
      return BadRequest();
 }
`

**Comment by Amit1150** [comment]
@nicklbailey : I did the same. But I want is there any I construct an object, if it is null then again call the validate method or something like this .
