### ISSUE TITLE
Consider allowing arguments to be passed to IValidatorFactory.GetValidator

### ISSUE THREAD

**Issue by jedd-ahyoung** [JeremySkinner/FluentValidation#260]
Currently, `IValidatorFactory` looks like this:

```
public interface IValidatorFactory {
    IValidator<T> GetValidator<T>();
    IValidator GetValidator(Type type);
}
```

However, this makes it impossible to pass custom parameters to the underlying factory method. (For instance, Castle Windsor can resolve a component and pass additional parameters using a Dictionary or an anonymous object.) This can be necessary as there's no way to get outside values into an `IValidator` instance unless it's manually instantiated (which is not always feasible).

I propose that `IValidatorFactory` look more like this:

```
public interface IValidatorFactory {
    IValidator<T> GetValidator<T>();
    IValidator<T> GetValidator<T>(object params);
    IValidator GetValidator(Type type);
    IValidator GetValidator(Type type, object params);
}
```

We keep the original contract to preserve compatibility, but through the interface, we allow for new options.

My use case for this is validating a user object upon login; I want to validate that the user status is active, but I also want to validate that the login password (in plaintext) matches the User entity from our DB (the hashed version). I do not want to add a second "password" property to any of my entities just for validation purposes; instead, I'd like to be able to pass the value as a parameter to a rule. (Note that this is a business validation use case, not MVC or DTO validation; I'd like to be able to use this library exclusively for that purpose.)

Any thoughts? I think this would be a good option, opening up a lot of possibilities.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. 

Currently in FV, instantiation of validators is expensive due to the compilation of expression trees used in rule construction, which is why validators should typically only be instantiated once and then cached and reused (ie created as singletons). 

This approach encourages recreating the validator instances when you need to pass in additional context/arguments, which is something I'd highly recommend against. It's fine to pass in dependencies that can also be singleton-scoped, but anything that's specific to an individual call to Validate shouldn't really go in via the constructor, as you're then bypassing all the caching.

The usual way to do this is to pass the additional arguments in as properties on the object being validated (typically, FV is used against a viewmodel/inputmodel not a business entity). If you don't want to do this in your case, you can always introduce a validation-specific model that exposes both the entity to validate and the context, eg:

```
class MyValidationModel {
  public MyEntity EntityToValidate {get;set;}
  public string SomeContextualValue{get;set;}
}
```

This is the approach I'd recommend taking...I'm not comfortable introducing methods that encourage bypassing of the cache, unless we can find away to externalise the cache outside the validator.

Hope that makes sense

**Comment by jedd-ahyoung** [comment]
I understand the singleton lifecycle approach, and it makes sense from a performance standpoint. However, from a usability standpoint, this is a hindrance. Perhaps instead of instantiation, there could be a way to pass external values when you validate against a ruleset? This way, you could keep singleton references, but you could pass a defined value when you run the validation rules. The definition might look like this:

  public PersonValidator() {
     RuleSet("Names", (options) => {
        RuleFor(x => x.Surname).NotNull();
        RuleFor(x => x.Forename).NotNull();
        RuleFor(x => x.SomeProperty).Equals(options.SomeProperty);
     });

     RuleFor(x => x.Id).NotEqual(0);
  }

That way, we keep caching, avoid transients, and we only have to update the `IValidator` interfaces. What do you think?

As an aside, I'm aware that FluentValidation is usually used with MVC models or WebAPI validation, but I think it can be very useful in a business context as well (as there are few tools that target that spot). I'm trying to avoid having to roll my own, as I'd end up duplicating a lot of what already exists in this library.

**Comment by JeremySkinner** [comment]
This suffers from the same issue. Rules defined within a ruleset are still generated and cached when the validator is instantiated- they aren't lazily created. At the time the ruleset is created, the "options" variable wouldn't exist, as it happens during intialization not during validation.

**Comment by meggers** [comment]
@JeremySkinner for your validation-specific model approach, how would you approach passing parameters into child validators? I've tried 
`RuleFor(model =>new ValidationModel<propType>(model.property, params)).SetValidator(propValidator)` but obviously that doesn't work

**Comment by grokky1** [comment]
@jedd-ahyoung How did you eventually solve this for validating business objects, and passing in custom data?
