### ISSUE TITLE
Integrate with INotifyPropertyChanged and INotifyDataErrorInfo

### ISSUE THREAD

**Issue by bitbonk** [JeremySkinner/FluentValidation#267]
In the the various XAML implementations [INotifyDataErrorInfo](https://msdn.microsoft.com/en-us/library/system.componentmodel.inotifydataerrorinfo(v=vs.110).aspx) is used to report validation errors for databound properties or for the whole entity (i.e. the view model) to the UI. [INotifyPropertyChanged](https://msdn.microsoft.com/en-us/library/system.componentmodel.inotifypropertychanged(v=vs.110).aspx) is used to report to the UI that a databound property has changed.

I suggest, you provide an integration with these two interfaces. It would basically look like this:

- declare rules and messages for specific properties in the usual fluent fashion
- evaluate the rules for a property whenever the property changed (using `INotifyPropertyChanged`) 
- report the errors for the failed properties (using `INotifyDataErrorInfo`)

This way FluentValidation could easily be used with the various XAMLs of the world.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this isn't something that I'm planning on including as I consider it out of scope for the project. 

FluentValidation's purpose is to define and execute a set of rules against an object, and returns a collection of results...responding to notifications of property change etc is really the responsibility of your model not the validator. If you want to invoke the validator in response to a property change notification, then you can do so, but the validator shouldn't be the thing that listens for this change. 

Additionally, because INotifiyPropertyChanged notifies every time a property is changed, it encourages validation of a single property only. This goes against FluentValidation's approach of validation the entire object in one go (for example, once a submit button his pressed). While you certainly can use FV in the single-property approach, you do lose a lot of functionality that the library provides.  

I hope that makes sense, and I do appreciate the feedback, so thank you.

**Comment by bitbonk** [comment]
I didn't think it should be added to FV core. I was thinking more of an additional integration package. Just like the one that you provide for MVC. Currently there doesn't seem to be a reusable an comprehensive library out there that would help with the classic validation problems in the XAML/MVVM binding world. 

The fluent way of defining rules would work as well in MVVM and it would most likely look very similar to FV. It is just required that properties can be validated individually and that (by default) it could be automatically triggered when the property changes its value. 

The question now is, would FV have enough overlap in scope that it'd be worth trying to integrate with it or  would it make more sense that I build something separate.

Do you have some examples of functionality I would lose when validating properties individually?

How do I validate a single property only in FV?

**Comment by JeremySkinner** [comment]
There's an overload of Validate that accepts an array of property names to
include for validation (its defined in an extension method). This will only
execute rules for the specified properties.

Under the covers, this is implemented using a ValidatorSelector instance
(the MemberNameValidatorSelector I believe). Selectors are passed into the
ValidationContext and evaluate every rule definition to see if it should be
executed for the current run. This is also how rulesets are implemented.

Off the top of my head, you lose the following when validating individual
properties:
- cross-property rules
- rulesets
- model-level rules
- dependent rules
- anything defined using "Custom"

I'm not particularly keen on maintaining integration packages as they take
a lot of time and effort to support and update, which takes time away from
building core functionality (in fact, I hugely regret ever writing the MVC
integration). I think its better if integration packages can be maintained
externally to FV by those that actually use them (like how the Nancy
integration is maintained by the Nancy team). This helps reduce my workload
and allows me to focus on the core library.  If this is the approach you
want to take, then I'd be happy to help answer any questions you have about
writing such an integration, but I'm afraid I can't help support it.

Hope that makes sense
