### ISSUE TITLE
The rule that dependent on 2+ other rules

### ISSUE THREAD

**Issue by vitidev** [JeremySkinner/FluentValidation#272]
How to define the validation rule that will be executed only after 2+ early defined and successfully passed rules?

"When" does not allow refer to other rules

**Comment by JeremySkinner** [comment]
FluentValidation doesn't really work that way. Individual calls to RuleFor
are independent and have no knowledge of other rules defined within a
validator class.

That being said, there is the DependentRules feature that allows you to
define rules that will only execute if a specific other rule passes, but
these have to be explicitly defined as dependent rules rather than regular
RuleFor calls.

**Comment by vitidev** [comment]
Will you plan to provide this feature? For example to have an ability to set up rule name and then use this name in @when@ condition.

**Comment by JeremySkinner** [comment]
Currently no plans for this, sorry- you'll need to use the DependentRules
feature if you want to do this.
