### ISSUE TITLE
MVC6 RC2 Port

### ISSUE THREAD

**Issue by Nico-VanHaaster** [JeremySkinner/FluentValidation#273]
This is not an issue by a release port to MVC 6 RC2 (core & net framework).

I have put a simple repository at [FluentValidation.MVC6](https://github.com/Nico-VanHaaster/FluentValidation.Mvc6) that can be downloaded and reviewed. 

Not all the features are there but at this point I have got it to work as far as I needed it.

Mainly the resources system needs to be updated and managed.

Cheers,

Nico

**Comment by JeremySkinner** [comment]
Thanks for this, but the aim for the MVC6 integration is to switch over to using IObjectModelValidator rather than re-using the ValidatorProvider infrastructure from MVC5. Please see this post which documents the roadmap:

https://github.com/JeremySkinner/FluentValidation/issues/98#issuecomment-219080143
