### ISSUE TITLE
A github website for the project?

### ISSUE THREAD

**Issue by sunnykgupta** [JeremySkinner/FluentValidation#276]
I'd love to help out with that.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion...what do you imagine would go on the site, and what's the advantage over the existing github wiki?

**Comment by SeanKilleen** [comment]
I've been thinking about suggesting something like this as well.

A few arguments in favor, IMHO:

* A well-indexed, more searchable entry point for content for new users -- might cut down on some of the more basic GH issues we see submitted here, especially as its built up over time.
* A great place for FAQ / usage tips
* A nicely-branded place for this project to live (as such a great resource for devs, it's earned it)
* Documentation can be kept in a codebase as well and coordinated with releases, etc. 
 * ...and additionally, pull requests to help document more things.
* Github pages makes this sort of thing dead simple.

**Comment by sunnykgupta** [comment]
Yes,

Another thing to add would be, projects with their own websites somehow
tend to seem more "reliable/maintained" than those without. (At least when
I observed OSS during my initial days as a programmer.)


Sunny R Gupta
Lead Web Engineer
Wooplr Bangalore Development Team
+91 9974063202 / +91 8698368390
<http://www.linkedin.com/in/sunnykgupta>  <http://facebook.com/sunnykgupta>
<http://twitter.com/sunnykgupta>  <http://google.com/+SunnyKumarGupta> [image:
skype:sunnykgupta]

All information contained in this mail is confidential and proprietary
unless otherwise specified. If you have received this email in error,
please reply back with *'unsubscribe'* in the subject to be removed from
out database.The information and views reflected in the mail above are
solely those of the sender. The sender is not liable to any information
sent out using the email communication channel outside their network.

Unless absolutely necessary refrain from taking a printout of this email,
save the planet.

**Comment by SeanKilleen** [comment]
@sunnykgupta I'm not sure the library has to worry about legitimacy or obtaining new users :smile: :

![image](https://cloud.githubusercontent.com/assets/2148318/15966313/9db67a02-2ef0-11e6-80a0-2c85c641f732.png)

**Comment by JeremySkinner** [comment]
So my main concern is that it'd increase the maintenance overhead for the project, which is something I want to keep to a minimum as I don't get much time to work on it anyway. But if the overhead is minimal then I'm up for it. 

For documentation, I really like the github wiki because this can be edited both through the inline editor and through a git repo...would we lose the inline edit functionality if we went this route? I really like the idea of pull requests for docs. I did have the wiki set to allow public edits for a while, but I ended up having to undo most of these due to incorrect information so I closed it in the end. 

Branding doesn't particularly interest me, but if you wanted to have a go at creating somethign then I'd be happy to take a look. I wouldn't personally have much time to invest in this though.

**Comment by JeremySkinner** [comment]
@SeanKilleen oh sweet, it was still around 950k when I last looked (plus there's also the FV-signed packages and the old codeplex downloads)

**Comment by SeanKilleen** [comment]
@JeremySkinner Welcome to the million+ club! :tada: 

Basically:

:x: no in-line editing
:white_check_mark: still could use markdown to author content 
:white_check_mark: easy to convert existing content due to marketing.
:white_check_mark: more open; you control content but others could propose enhancements. Nice balance?
:white_check_mark: more visible, particularly to first-time users
:white_check_mark: can organize things how you want
:white_check_mark: could aim to cut down on a number of questions that new users tend to post

**Comment by SeanKilleen** [comment]
Another thing worth noting: if a web site does end up being in the project's best interest, it creates two repos affiliated with the same project. At that point, it might make sense to check whether a re-org to a `FluentValidation` GH org makes more sense (would also want to look into whether that would make things easier or not for @JeremySkinner).

**Comment by JeremySkinner** [comment]
Actually turns out you can edit markdown files inline within a repo:

![image](https://cloud.githubusercontent.com/assets/90130/15966849/cd029c42-2f1c-11e6-971b-df8ff2e658d2.png)

**Comment by SeanKilleen** [comment]
:+1: Nice! No worries on that end, then.

So next question -- would you be averse to creating a FluentValidation GitHub org where both the library and web site for docs would reside? This would be slightly more involved, but a one-time thing. 

It would bring both of them under one umbrella and allow you the ease of controlling things, but it would also mean that it was no longer located at `JeremySkinner/FluentValidation` (which I wouldn't blame you if you were attached to).

**Comment by JeremySkinner** [comment]
Let me have a think about that one

**Comment by JeremySkinner** [comment]
I think we'll keep the code where it is rather than having a separate FV organization. I've already gone through one repo move so not keen on breaking that again. 

I've created a gh-pages branch if either of you want to make a start on this. Currently it's available at http://www.jeremyskinner.co.uk/FluentValidation using the built in GH template, but will get a specific domain if we want to proceed with this.

**Comment by JeremySkinner** [comment]
Closing this as it never received any investment.
