### ISSUE TITLE
WebAPI Issue when using [Route] attribute in controller

### ISSUE THREAD

**Issue by johnway2** [JeremySkinner/FluentValidation#281]
See http://stackoverflow.com/questions/36924316/fluentvalidation-doesnt-work-when-using-webapi-route-attribute

**Comment by JeremySkinner** [comment]
This doesn't sound like a FluentValidation issue, but I don't have any experience with WebApi so can't really help with that. 

Some things to try:
- Does the same thing happen if you use an explict route mapping in the app startup, rather than an attribute?
- Does it behave the same way using DataAnnotations?
- In your app startup, Make sure you call configure on FluentValidationModelValidatorProvider,Configure(cfg)  before calling GlobalConfiguration.Configure(WebApiConfig.Register);
