### ISSUE TITLE
Testing PropertyValidators

### ISSUE THREAD

**Issue by kazper** [JeremySkinner/FluentValidation#314]
_ShouldHaveChildValidator_ test-helper does not seem to work for _PropertyValidators_. For example, it seems natural to do this `validator.ShouldHaveChildValidator(m => m.Email, typeof(EmailValidator));` for the built-in email _PropertyValidator_.

**Comment by JeremySkinner** [comment]
Yes, that's the correct behaviour. It's for testing the presence of a child
validator, not a PropertyValidator.

For testing property validators the usual approach is to test the result
not simply if the validator is present.

**Comment by kazper** [comment]
Would it be viable to create a helper for testing the presence of PropertyValidators? Seems tedious to test the correct behaviour of PropertyValidators every time I use them.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but I'm not keen on this.

The point of the TestHelper is to test the behaviour of your validator
classes when supplied with different inputs. Checking if a
PropertyValidator is present doesn't achieve this.

The one exception to this is child validators (which are themselves
derivatives of AbstractValidator, and so typically have their own
separate set of tests)

You can do this if want, but it's not the point of the TestHelper so it's
not something I want to bring into the core project (and I think it's
largely pointless as it doesn't actually test anything useful)

**Comment by kazper** [comment]
Thanks for the explanation.

> The one exception to this is child validators (which are themselves
derivatives of AbstractValidator, and so typically have their own
separate set of tests)

Wouldn't the same reasoning apply to PropertyValidators when the correct behaviour PropertyValidator is tested separately?

> You can do this if want, but it's not the point of the TestHelper so it's
not something I want to bring into the core project (and I think it's
largely pointless as it doesn't actually test anything useful)

It tests that the PropertyValidator is set in the parent Validator which seems pretty important to me. If it isn't set then it means that the functionality is missing. The test guarantees correctness and provides documentation. Having a test helper would make testing the behaviour of parent Validator a breeze. Using top-down design and TDD you could test fully the parent Validator and worry about smaller PropertyValidator implementation details later. Also having a test helper favours creating smaller reusable PropertyValidators (e.g. PhoneNumberValidator, PersonalCodeValidator, AddressValidator etc) that can be shared between Validators or just reused within Validator.

To me it seems a little bit of a discrepancy between preference of unit testing with [_behaviour verification_ versus _state verification_](https://hsidev.wordpress.com/2008/06/24/test-patterns-state-vs-behavior-verification/). 

Just my thoughts. I'm a bit inexperienced so I could be off. But I worked on a project where [specification pattern](https://en.wikipedia.org/wiki/Specification_pattern) was used and we always tested whether a correct type of specification was applied, which seems a similar situation here (i.e. a correct PropertyValidator type is used).

**Comment by JeremySkinner** [comment]
> Wouldn't the same reasoning apply to PropertyValidators when the correct behaviour PropertyValidator is tested separately?

No, because testing a property validator standalone can't account for how it's used within an AbstractValidator derivative. For example, the behaviour of a rule can change depend on how it's used within a rule chain (for example, you can apply a condition to it with a When clause). Testing a property validator by itself doesn't account for this. 

> It tests that the PropertyValidator is set in the parent Validator which seems pretty important to me

I disagree. The purpose of an abstractvalidator class is to define a set of rules that run against your objects. The important thing here is *how* the rules behave, not how they're composed internally. For example, you could have a business rule that an integer property must be between 1 and 10. This could be implemented in many different ways....an InclusiveBetween validator, an ExclusiveBetween validator, a Must call, a custom validator etc etc. It doesn't matter which of these is used. What matters is the rule works as expected. 

Testing for a specific implementation just leads to brittle tests.

**Comment by kazper** [comment]
Thanks for taking the time for answering so fast and thoroughly.

> No, because testing a property validator standalone can't account for how it's used within an AbstractValidator derivative. For example, the behaviour of a rule can change depend on how it's used within a rule chain (for example, you can apply a condition to it with a When clause). Testing a property validator by itself doesn't account for this.

Does not that apply to AbstractValidators as well (i.e. chaining additional When-clauses)? If it doesn't then I find the API to be bit misleading in the sense that they both use SetValidator calls that behave differently and have to be tested differently.

> Testing for a specific implementation just leads to brittle tests.

I feel like it's a matter of preference again. Yes, the tests are more brittle, but they are easier and cleaner to write. Think mocking... Tests with mocks are generally brittler than ones that test the state (i.e input and output). In a perfect world we'd [black-box test](https://en.wikipedia.org/wiki/Black-box_testing) everything but in the real world unit testing is generally [white-box testing](https://en.wikipedia.org/wiki/White-box_testing) anyways. To me it seems a bit ridiculous that there's a built-in EmailAddress PropertyValidator that I have to test with dummy e-mail data every time, if I understand correctly. 

I think I understand your point and agree to a point where we bar off the other way of doing. :)

So let's say I wanted to do it the other way with FluentValidations. I thought up a few solutions:

1. Create AbstractValidators for simple types. As I understand from a [previous issue](https://github.com/JeremySkinner/FluentValidation/issues/282) I'd have to do a NotNull check before SetValidator or the Validator doesn't apply. Are there any other drawbacks you can think of?
2. Wrap simple types in complex types. It would work, right? But I wouldn't want the ugly boilerplate...
3. Make a test helper for testing the presence of PropertyValidators.

I'd be hugely grateful if you took the time to review these options!

**Comment by JeremySkinner** [comment]
> Does not that apply to AbstractValidators as well

Sure...and in that situation you'd then want to be testing the condition etc, rather than using ShouldHaveChildValidator.

> I feel like it's a matter of preference again. Yes, the tests are more brittle, but they are easier and cleaner to write. Think mocking...

And that brittleness is why I usually avoid using mocks unless there's no other option. "Easier and cleaner" I disagree with...it's perfectly possible to have easy and clean tests that exercise the full system if the code is well designed. 

> To me it seems a bit ridiculous that there's a built-in EmailAddress PropertyValidator that I have to test with dummy e-mail data every time, if I understand correctly.

To me it seems ridiculous that you *wouldn't* want to do this. As FV is for building rules that validate data, not testing that the rules work with if your test doesn't actually exercise the rule with real data, then the test isn't useful. You're then only testing the configuration, not that the rules work as expected.

In the end, of course you're free to do what you like....I've tried to explain my reasons for why I think this is bad, but there's nothing stopping you for implementing this in your project if you want to. You'd need to use the ValidatorDescriptor to get all of the validators assigned to the property and loop through them. If you take a look at the code for how ShouldHaveChildValidator works, then this should give you a starting point. However, this won't be something that will be included in FV. 

Good luck with your project.

**Comment by kazper** [comment]
Thanks again for the thorough answers with your point of view!
