### ISSUE TITLE
enum_error not localized to dutch

### ISSUE THREAD

**Issue by NSchoemaker** [JeremySkinner/FluentValidation#315]
Hi there,

First of all FluentValidation is a great piece of work!

I noticed that the error message of an IsInEnum rule does not get localized.
Example: 

RuleFor((m) => m.Gender).IsInEnum().WithName(CommonStrings.RS_GENDER).WithState((m) => 20);
Message -> The value for 'Geslacht' is invalid.

TIA

**Comment by JeremySkinner** [comment]
Thanks!

The enum validator is a new addition, and I don't think anyone
has submitted any translations for it yet (I entirely rely on volunteers to
provide the translations into other languages). If you're able to provide a
translation I'll get it added into the next release.

**Comment by NSchoemaker** [comment]
Hi Jeremy,

The translation could be  "De waarde voor '{PropertyName}' is ongeldig."

Thanks !!

**Comment by JeremySkinner** [comment]
That doesn't actually look like one of FluentValidation's messages. The default enum message is: 

'{PropertyName}' has a range of values which does not include '{PropertyValue}'.

(See Messages.resx: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/Messages.resx)

Are you using FV within MVC? If so, the original message is probably coming from MVC's own validation infrastructure rather than FluentValidation.

**Comment by NSchoemaker** [comment]
Hi Jeremey,

I see what you mean and have no clue where that format is comming from.
The code is used in an asp.net core REST API project.
We are using request localization to set the culture.
I validate the domain objects by "hand" and return the resulting validation error messages (if any) in the response. Ie i'm not using any of MVC its validation infastructure.
I included a screenshot while debuging. The notempty_error is localized but the enum_error is not.

HTH,

![localizedenumfailure](https://cloud.githubusercontent.com/assets/16647347/18006071/18b2cb68-6b9e-11e6-9665-b26431e9d799.jpg)

**Comment by NSchoemaker** [comment]
BTW,

A translation to dutch could be  '{PropertyValue}' komt niet voor in het bereik van '{PropertyName}'.

Nico.

**Comment by JeremySkinner** [comment]
Thanks- I've added that in the latest commit.
