### ISSUE TITLE
Integrated MVC's ModelBinding validation differs from explicit FV validation

### ISSUE THREAD

**Issue by kazper** [JeremySkinner/FluentValidation#316]
Probably a known issue but I'm just gonna write it up to be sure.

I have integrated FluentValidations with MVC for the automatic ModelBinding validation. I did so by setting the provider in Global.asax and placing ValidatorAttributes on my ViewModels.

In my codebase, I have complex models which have child models. Both the models have validators. The complex parent model has a validator that uses SetValidator to set child model's validation with another validator. The problem arises when I specify a When-clause on the SetValidator. The integrated MVC's ModelBinder validates like there is no When-clause. But when I explicitly create the FluentValidation validator and run the Validate method then I get a result that respects the When-clause.

This has lead me to inject the FV validators into Controller actions that have a Model as a parameter, running the validation explicitly, clearing the ModelState and then re-adding the (actual) errors from FV's ValidationResult into the ModelState.

I can't remove the ValidatorAttributes which turn on the ModelBinding validation because I want the automatic client-side jQuery validation.

I hope I explained myself clearly. I can provide a code example, if needed.

Is it a known issue? Are there any better fixes?

**Comment by JeremySkinner** [comment]
Yes, that's a known issue. It's one of the (many) limitations of MVC's
validation infrastructure and there's no workaround. You have a choice of
either:

- decorating the child model with a validator attribute. Then you get
clientside validation, but MVC will always validate models of this type,
irrespective of conditions etc.

- do not decorate the model with a validator attribute. You remain in
control of when the child model gets validated but you lose clientside
validation.

Personally I don't use any of the automatic modelbinding integration or the
clientside support as MVC's validation api is incredibly limited and poorly
designed (asp.net core does a better job). Instead I invoke the validators
manually rather than during model binding, and I manually add clientside
validation when I need it using a separate clientside framework. Seems like
a bit more work up-front, but actually turns out much cleaner in the end.

**Comment by kazper** [comment]
Ok, that's what I thought. Thanks!

Mocked up a quick example for anyone else interested.

```
    [Validator(typeof(ParentClassValidator))]
    public class ParentClass
    {
        public ChildClass ChildClass { get; set; } = new ChildClass();
    }

    [Validator(typeof(ChildClassValidator))]
    public class ChildClass
    {
        public string Value { get; set; }
    }

    public class ParentClassValidator : AbstractValidator<ParentClass>
    {
        public ParentClassValidator()
        {
            RuleFor(x => x.ChildClass)
                .SetValidator(new ChildClassValidator()).When(x => false); // Should never be called.
        }
    }

    public class ChildClassValidator : AbstractValidator<ChildClass>
    {
        public ChildClassValidator()
        {
            RuleFor(x => x.Value)
                .NotEmpty().WithMessage("Should not see this message");
        }
    }

    public class TestController : Controller
    {
        public ActionResult TestAction(ParentClass parentClass)
        {
            if (!ModelState.IsValid)
            {
                // Logic comes here because parentClass.ChildClass.Value should not be empty in MVC's ModelBinding terms.
            }

            var fvValidator = new ParentClassValidator();
            var fvResult = fvValidator.Validate(parentClass);
            if (fvResult.IsValid)
            {
                // Logic comes here with FluentValdiation validation which respects the SetValidator's When-clause. (Notice different IsValid result.)
            }

            // Have to do this for wanted behaviour:
            ModelState.Clear();
            fvResult.AddToModelState(ModelState, prefix: null);
            return View();
        }
    }
```
