### ISSUE TITLE
Performance improvements to name resolution

### ISSUE THREAD

**Issue by batzen** [JeremySkinner/FluentValidation#331]
Hi,

i had to notice that name resolution for PropertyRule takes a considerable amount of time.

During our automated UI tests some validators/rules are called millions of times.

I got a modified version of FluenValidation to which i added caching.

My test:
- Validator consisting of two rules on different properties
- Running Validate 1 000 000 times

My results:
- No caching: 12 seconds
- Caching: 6 seconds

My question is:
Would you accept a PR adding said caching?

**Comment by JeremySkinner** [comment]
Yes that sounds very useful. If you'd be happy to submit a pull request
I'll happily review it. It might not be for a while though as I'm very busy
with other commitments at the moment, but I'd definitely like to get more
performance improvements in the project.

**Comment by batzen** [comment]
Ok, i will add a list of things i'd like to change to the issue itself and update it as i find more places that could be improved in regards of performance.
When i am finished with my list i will mention you here so that you can decide which things you'd like to be included in my PR.

One more question, do you prefer one PR or multiple PRs for each change?

**Comment by batzen** [comment]
With all my optimizations in place i currently get the following results using BenchmarkDotNet on my machine:

| Name | Median | StdDev
|---|---|---|
| Version from nuget (6.2.1.0) | 7.6984 us | 0.0473 us
| My version | 1.9282 us | 0.0438 us

I used the following validator:
```
new TestValidator
	{
		v => v.RuleFor(x => x.Address).NotNull(),
		v => v.RuleFor(x => x.Address.Country).NotNull().When(x => x.Address != null)
	};
```

The benchmark only calls `validator.Validate(person);` where person is the Person class from the FluentValidation.Test project.
The validator and person instances are only created once during the benchmark.

Performance could be further improved if there was a way to cache the strings obtained from the resources, but that's not on my list as i only used FluentValidation with a custom provided ResourceProvider which is not localized (my application is only provided in german).

On my machine calling BuildErrorMessage 1 000 000 times takes about 6 seconds.
2 of these 6 seconds account for GetString on LocalizedStringSource.

**Comment by JeremySkinner** [comment]
Looks good.

Regarding pull requests, it really depends on the size. If it's a huge
number of changes then several smaller ones might be better. I'll leave it
up to you to decide what you think's most appropriate.

Thanks!

**Comment by batzen** [comment]
Changing SplitPascalCase from using Regex to a specialized method using a StringBuilder i get the following results. 
That way we get a speed improvement of factor 6 till factor 24 and memory consumption lowered by factor 2 till factor 8 during that operation.

```ini

Host Process Environment Information:
BenchmarkDotNet.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-2600K CPU 3.40GHz, ProcessorCount=8
Frequency=3312791 ticks, Resolution=301.8603 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1586.0

Type=PascalCaseBenchmark  Mode=Throughput  

```
        Method |       input |        Median |      StdDev |  Gen 0 | Bytes Allocated/Op |
-------------- |------------ |-------------- |------------ |------- |------------------- |
         **Regex** | **DATEOFBIRTH** | **5,190.7061 ns** | **129.7787 ns** | **662.00** |             **840,87** |
 StringBuilder | DATEOFBIRTH |   216.4161 ns |   1.4757 ns |  80.93 |             102,18 |
         **Regex** | **DateOfBirth** | **1,889.1744 ns** |  **26.5558 ns** | **266.39** |           **337,73** |
 StringBuilder | DateOfBirth |   152.0023 ns |   0.6901 ns |  48.48 |           61,98 |
         **Regex** | **dateOfBirth** | **1,545.8766 ns** |  **61.3566 ns** | **199.93** |             **253,25** |
 StringBuilder | dateOfBirth |   130.6589 ns |   0.4345 ns |  34.82 |              43,99 |
         **Regex** | **dateofbirth** |   **654.4314 ns** |   **4.8212 ns** |  **63.62** |              **80,84** |
 StringBuilder | dateofbirth |   123.8501 ns |   1.7477 ns |  33.54 |              42,42 |

**Comment by JeremySkinner** [comment]
I'm surprised a regex is so much slower...I'm guessing using a compiled regex would make a big difference too?

**Comment by batzen** [comment]
It would, but the specialized method even beats a compiled regex.

**Comment by JeremySkinner** [comment]
Great, am happy to get that merged in.

**Comment by batzen** [comment]
I still got some trouble with flaky tests. Do you also encounter issues when running some tests where localized things are tested?
I if run those tests separately they work well, but testing everything in one run causes some tests to fail.

**Comment by JeremySkinner** [comment]
Yes, I have seen that before....it's usually because the culture is set
globally, which can cause issues if 2 tests require separate cultures but
don't properly clean themselves up.

>
2 things to check:
- your tests use CultureScope to set and reset the culture at the
beginning/end of the tests
- test parellization is turned off. The xunit runner parallelises tests by
default which isn't helpful if you have shared state.

If you're using my build script to run the tests it should automatically
turn off parellization, but if you're using any other runner you'll need to
explicitly turn it off.

**Comment by batzen** [comment]
Using the build script worked a lot better.
Except, that the netstandard projects failed.
I notice that they were called with "dotnet test --no-build" where they should be called with "dotnet test --no-build --configuration $(Configuration)".
The missing --configuration caused the tests to used the debug build instead of the current configuration.

Should i include that change in my PR or do you prefer a separate one for that?

**Comment by JeremySkinner** [comment]
Sure, that would be great. Thanks

**Comment by batzen** [comment]
Here we go #334

**Comment by sjancke** [comment]
There is a subtle bug in the AccessorCache for "complex" expressions used in rules:

RuleFor(x => x.A.Foo)... //(1)
RuleFor(x => x.B.Foo)... //(2)

are not differentiated in the AccessorCache and wrong expressions (1) are used for rule (2).

**Comment by sjancke** [comment]
Please merge pull request #366. Can you also create a current release of FluentValidation? We are heavily interested in these performance improvements.

**Comment by JeremySkinner** [comment]
I've merged the pull request. Will aim to put out a beta release this week (probably friday)

**Comment by sjancke** [comment]
Jeremy, what are your plans regarding a release?

**Comment by JeremySkinner** [comment]
Not for a while I'm afraid...I'm snowed under with work and moving house at the moment. Once things have settled down then I'll try and find a bit of time to work on FV again

**Comment by aschmider** [comment]
There's another problem with the AccessorCache if you access local variables in the expression and add the same rule more than once in a single session. Then only the first time the rule is added the local variable's value will be captured.

Here is a demonstration using a simple validator. The second assertion failes, but it should not.

	using System.Diagnostics;
	using FluentValidation;

	namespace fluent_validation_cache
	{
		internal class Foo
		{
			public int Bar { get; set; }
		}

		internal class Validator : AbstractValidator<Foo>
		{
			public Validator(int factor)
			{
				RuleFor(foo => More(foo, factor).Bar)
					.GreaterThanOrEqualTo(5);
			}

			private static Foo More(Foo foo, int factor)
			{
				return new Foo {Bar = foo.Bar * factor};
			}
		}

		internal class Program
		{
			private static void Main(string[] args)
			{
				var v1 = new Validator(3);
				var v2 = new Validator(2);

				var foo = new Foo {Bar = 2};

				Debug.Assert(v1.Validate(foo).IsValid);
				Debug.Assert(!v2.Validate(foo).IsValid);
			}
		}
	}

If writing

    RuleFor(foo => More(foo, factor).Bar + 0)

instead of

    RuleFor(foo => More(foo, factor).Bar)

the assertion succeeds because the expression is no member expression anymore and thus not cached. This behaviour can leed to hard to track bugs because it depends on the order in which rules are generated and tested. Introducing a per instance AccessorCache instead of using a static dictionary would at least allow to access members of the current validator instance without prolems. Another possible workaround is adding an option to disable caching.

I prefer a solution where I don't have to change anything in the rules or validators (some of our tests failed when upgrading from FluentValidation 6.2.1 to 6.4.0). But I don't know if it is, for example, possible to check if the expression reads local or instance symbols and include this information in the cache's key.

**Comment by JeremySkinner** [comment]
> Introducing a per instance AccessorCache instead of using a static dictionary would at least allow to access members of the current validator instance without prolems

Unfortunately that defeats the purpose of having the cache in place. The reason for adding this was so that expression tree compilation could be cached regardless of whether or not validator instances are singleton. 

I'd really recommend against using local variables inside RuleFor expressions, it's really not the intended usage of FV. That being said, I'll add an option to globally disable the cache. For now please stick with 6.2.1.

**Comment by aschmider** [comment]
Thanks for your input. I worked around this issue by overwriting RuleFor*() methods in a base class validator and checking if the expression would get cached although it should not. In that case I compile the expression myself and create a new wrapper expression like this:

    var func = expression.Compile();
    return instance => func(instance);

Maybe a redesign of rule creation to avoid using locals in the expressions is a good idea, but that could be a lot of work. So I'll probably wait for the disable-the-cache-option.

**Comment by JeremySkinner** [comment]
OK I think I've got a fix that should no longer cache expressions like these, and I've also added a global property on the ValidatorOptions class to disable all caching.

The changes are committed, so feel free to build from source or otherwise I'll try and do a beta release to nuget on monday.

**Comment by JeremySkinner** [comment]
OK I've pushed out 6.4.1-beta1 with this change.

**Comment by aschmider** [comment]
I tried 6.4.1-beta1 and all unit tests pass. Thanks for the patches!

**Comment by JeremySkinner** [comment]
That's great, glad it's working. I'll push it out as a non-beta release.

**Comment by JeremySkinner** [comment]
That's done.
