### ISSUE TITLE
Add overload of ShouldHaveChildValidator that takes a model

### ISSUE THREAD

**Issue by firedraco** [JeremySkinner/FluentValidation#336]
Current, ShouldHaveChildValidator only allows you to test for a specific property, e.g.:
`validator.ShouldHaveChildValidator(x => x.Address, typeof(AddressValidator));`

In some of my validators I have child validators that are added conditionally based on other properties like so:
```
When( model => model.HasUserAccount, () =>
{
     RuleFor( model => model.UsernameValidationInformation )
         .SetValidator( new UsernameValidationInformationValidator() );

     RuleFor( model => model.PasswordValidationInformation )
         .SetValidator( new PasswordValidationInformationValidator() );
} );
```

It would be nice to be able to do:
```
var model = new UserModel { /*...*/ };

validator.ShouldHaveChildValidator(x => x.UsernameValidationInformation,
    typeof(UsernameValidationInformationValidator),
    model);
```
in my tests, but right now ShouldHaveChildValidator doesn't have an overload that supports checking it against a specific model.

I've had to work around this by creating a particular model that will validate successfully against everything except some of the properties checked by the child validators, then manually checking the errors but this can be error-prone if someone updates the child validators in the future.

**Comment by JeremySkinner** [comment]
So the problem with this is that the child validator isn't actually being set conditionally....irrespective of the values in your model the call to When will always replace the child validator with a DelegateValidator that evaluates the model.HasUserAccount condition. 

This validator then delegates to the underlying childvalidator if the condition passes. So technically the test is actually correct in failing, because you don't actually have a UsernameValidationInformationValidator, but instead a DelegateValidator. 

In this case, I think it's much better to write your test based on the expected behaviour (which it sounds like you're doing already), rather than relying on the internal behaviour of how the child validator is wrapped by the condition.

**Comment by firedraco** [comment]
Aha, that makes sense why that was happening then.

The main reason why I wanted this functionality was that I was already testing the child validator's functionality in another set of unit tests and it felt weird to have to repeat some of them in the parent validator's tests.

I can deal with that though. Thanks!
