### ISSUE TITLE
Client side validation disappear after a while on IIS 8.5

### ISSUE THREAD

**Issue by Ashley44** [JeremySkinner/FluentValidation#351]
Hello Jeremy,

I have written a simple validation rule which gets validated on the client side. It works to start with and then the validation message disappears and comes with some generic message like "Made up Height must not be Empty". It seems that the rules I set up are being ignored.
Any idea why this is happening.
My rule 
 RuleFor(n => n.MadeUpHeight).GreaterThanOrEqualTo(1).WithMessage("_Please enter a height").NotNull().WithMessage("_Please enter a height");

**Comment by JeremySkinner** [comment]
My apologies, I never saw this issue when you originally opened it. I'm assuming you've solved it by now, but in case anyone else comes across this issue here's the explanation:

Assuming that the `MadeUpHeight` property is an integer, then if you leave the value blank you'll receive a generic required message as MVC does not allow blank/null values to be posted for non-nullable value types like integers. This is a limitation of MVC's validation process and is not related to validation. If blank values should be allowed for this property then you'd need to change it to be a nullable integer instead. Alternatively, if you don't want to allow blank values to be submitted but just want to get rid of the generic message, add a `.NotEmpty().WithMessage("my message")` validator to the rule.
