### ISSUE TITLE
Issue with OverridePropertyName Unit test

### ISSUE THREAD

**Issue by vp123456** [JeremySkinner/FluentValidation#359]
Here is the rule i am trying to test:

```
 RuleFor(m => m.Groups)
      .SetValidator(new MustContainAtLeastOne<AuthGroup>())
      .OverridePropertyName("Roles");
```

Test:

`validator.ShouldHaveValidationErrorFor(m => m.Groups,new List<AuthGroup>());`

Issue:

It fails when i have .OverridePropertyName("Roles") but when i remove it, test passes. 

I post a question on  [stackoverflow.com](http://stackoverflow.com/questions/40680930/fluent-validation-unit-testing)

**Comment by JeremySkinner** [comment]
I believe the TestHelper compares the name of the property specified in the lambda expression to the property name in the generated error message. In this case, because you've overridden the property name they won't match and so the assertion fails. You'll need to perform the assertion manually rather than using the TestHelper in this situation. 

I don't use stackoverflow, so will just leave this comment here.
