### ISSUE TITLE
What does IsInEnum actually do?

### ISSUE THREAD

**Issue by vaindil** [JeremySkinner/FluentValidation#381]
I'm sure this is a really stupid question, but I can't for the life of me figure out what `IsInEnum()` actually does, or how to use it. I need to accept a string and validate that it's one of the possible values in an enum. By name, it seems `IsInEnum()` would work. I don't know how to use it, however.

The only way my validator will compile is like this:

```csharp
RuleFor(m => m.Sort).IsInEnum();
```

No parameters or types are accepted. Am I supposed to use the enum as the base type that I'm validating against; i.e. `m.Sort` in the above example should be of the enum type and not a string? In that case, MVC wouldn't bind the value in the first place, making the validator pointless.

Am I misunderstanding the purpose of `IsInEnum()`? What am I missing?

**Comment by JeremySkinner** [comment]
Yes- the property would be the Enum type. It checks to see if the value assigned to the property Is valid for that enum type. 

This is a perfectly reaonsable thing to check for because you can assign any integer value to an enum property in c#. 

You're correct that the MVC binder wouldn't allow this, but FluentValidation isn't just for use with MVC, so outside of MVC this is a useful validator to have. 

In your case you'd need need to write a custom rule using Must.

**Comment by vaindil** [comment]
Ah, okay, that makes sense. I needed to take a step back and think not in terms of MVC, I apologize. Thank you so much, I greatly appreciate it!

**Comment by JeremySkinner** [comment]
I think what you're after sounds like a useful validator though...if you feel like contributing it to the project I'd happily take a pull request.

**Comment by VictorioBerra** [comment]
I would like to cast my vote for this feature too. I do not see a way to override the MVC validator for these situations. I want to have a friendly error set up if someone passes a string that does not match or an int that does not exist.
