### ISSUE TITLE
Show value of invalid item in list of PropertyValidator

### ISSUE THREAD

**Issue by nelisbraems** [JeremySkinner/FluentValidation#384]
I have made a DuplicateValidator, to check if a certain string occurs more than once in a list of strings. I would like to know how to configure my validator, in order to be able to display the string that is duplicate. The PropertyValue will display the entire List, I'm not sure if I can set this up using the PropertyValidator.

```
       public class DuplicateValidator<T> : PropertyValidator
       {
        public DuplicateValidator() : base("The {PropertyName} is duplicated for value {PropertyValue}")
        {
        }

        protected override bool IsValid(PropertyValidatorContext context)
        {
            List<T> values = (List<T>)context.PropertyValue;

            var allUnique = true;

            foreach (var item in values)
            {
                var number = values.Count(f => EqualityComparer<T>.Default.Equals(f, item));
                if (number > 1)
                    allUnique = false;
            }

            return allUnique;
            }
          }

```

**Comment by JeremySkinner** [comment]
Use a custom placeholder instead of {PropertyValue} and then add in the value you want to show within the  IsValid  method. You can see an example of using a custom placeholder inside the FV source. Here's an example: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/LengthValidator.cs#L68
