### ISSUE TITLE
Convert DTO attributes to ValidationRules

### ISSUE THREAD

**Issue by stannynuytkens** [JeremySkinner/FluentValidation#393]
I'm trying to re-use the already existing attributes on my DTO's to create validation rules.
I've tried something on this [Gist](https://gist.github.com/stannynuytkens/65ae46c8f35f33d1754510f82f741123) but I think it's not going to work because the compiler can't infer the property type from the expression. _The not working part is commented out._

Any ideas? Or is there already something implemented to do this?

**Comment by JeremySkinner** [comment]
You'd have to do it by constructing PropertyRule instances directly rather than trying to use expressions. Although FV's public api is strongly typed, internally it isn't so you can drop down to the internal api. 

Take a look at the code for how RuleFor is defined...it creates a RuleBuilder and from that create PropertyRule from the expression, and then uses AddRule to store this in the validator. You'd need to do something similar.

**Comment by stannynuytkens** [comment]
Ok, thanks @JeremySkinner, I'll look into that part and see if can contribute anything useful.
