### ISSUE TITLE
When not working with SetValidator on complex property

### ISSUE THREAD

**Issue by flower189** [JeremySkinner/FluentValidation#401]
I'd like to conditionally validate an address based on a customer's selection.

At the minute there is a `Customer` class a property of `Address`. I've only entered a snippet of the Address class.

```
public class Address
{
    public string AddressLine1 { get; set; }
    ...
}
```

```
public class Customer
{
    public string Name { get; set; }
    public bool NeedsInvoiceAddress { get; set; }
    public Address Address { get; set; }
    public Address InvoiceAddress { get; set; }
}
```

I have validators set up for each like this (I've just entered a snippet of AddressValidator):
```
public class AddressValidator: AbstractValidator<Address>
{
    public AddressValidator()
    {
        RuleFor(x => x.AddressLine1).NotEmpty();
        ...
    }
}
```

```
public class CustomerValidator: AbstractValidator<Customer>
{
    public CustomerValidator()
    {
        RuleFor(x => x.Name).NotEmpty();
        RuleFor(x => x.Address).SetValidator(new AddressValidator());
        RuleFor(x => x.InvoiceAddress).SetValidator(new AddressValidator()).When(x => x.NeedsInvoiceAddress);
    }
}
```

I'd like to only validate `InvoiceAddress` when `NeedsInvoiceAddress` is true but always to validate `Address` on the `Customer` class. Is this possible?

**Comment by JeremySkinner** [comment]
That should work just fine....what behaviour are you seeing?

**Comment by flower189** [comment]
The validation still gets executed on the InvoiceAddress regardless of whether NeedsInvoiceAddress is true or false.
It also seems to still be executed when SetValidator isn't specified. I probably should mention that this is being executed by the MVC extensions too, with the validators being injected.

**Comment by JeremySkinner** [comment]
Oh, right, it's probably the MVC integration causing problems.

If you're using SetValidator then you should make sure that the AddressValidator definitely isn't configured for MVC integration, otherwise it'll be instantiated and executed regardless in a completely separate process from the call to SetValidator. Remove the ValidatorAttribute from the AddressValidator (if you're using the AttributedValidatorFactory) or ensure it's not registered with your ioc container (if you're using container integration).

**Comment by flower189** [comment]
I've just excluded it and it does seem to be working as expected now.
Thanks for the explanation - I did start to suspect it might be involved.

Thanks for your help! 😄

**Comment by rjtan** [comment]
Hi @JeremySkinner , I know this issue is closed but i wanted to check if the issue will also happen in web.api without mvc? currently i have the same setup as @flower189 except for the MVC part

I have a web.api project with FluentValidation installed.

I call my validator like this

`PostParamValidator validator = new PostParamValidator();
            ValidationResult results = validator.Validate(param);
`

My Model is like this


```
    public class PostParam
    {
        public bool IsCreditCard { get; set; }
        public PostParamCreditCardDetail CreditCardInfo { get; set; }
    }
```

```
    public class PostParamCreditCardDetail
    {
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string CardName { get; set; }
    }
```

and my validator is like this :

```
    public class DepositOnlinePostParamValidator : AbstractValidator<DepositOnlinePostParam>
    {
        public DepositOnlinePostParamValidator()
        {
            RuleFor(x => x.CreditCardInfo).SetValidator(new DepositOnlinePostParamCreditCardDetailValidator());

        }
    }
```

```
public class DepositOnlinePostParamCreditCardDetailValidator : AbstractValidator<DepositOnlinePostParamCreditCardDetail>
    {
        public DepositOnlinePostParamCreditCardDetailValidator()
        {
            RuleFor(x => x.CardType).NotEmpty().NotNull();
            RuleFor(x => x.CardNumber).NotEmpty().NotNull();
            RuleFor(x => x.CardName).NotEmpty().NotNull();
        }

    }
```


You mentioned to 

> Remove the ValidatorAttribute from the AddressValidator

But i dont use the ValidatorAttribute and it still doesnt work.

Thanks,
Ruben
