### ISSUE TITLE
How do I manually register FluentValidation validators, in ASP.NET Core?

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#410]
I'm using ASP.NET Core, with the built-in container.

Registration is supposed to be done [like so](http://github.com/JeremySkinner/FluentValidation/blob/237ccfd581dcecf72209acdaabd4c41122fad98d/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs#L146):

    services
    .AddMvc()
    .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())

This automatically 1) configures FluentValidation, and 2) registers all validators found in the assembly.

But I want to register my validators manually, something like:

    services.AddTransient<IValidator<Foo>, FooValidator>();
    services.AddTransient<IValidator<Bar>, BarValidator>();
    // etc.

So can I simply register my validators, and that's it, or is there more setup for FV itself?

**Comment by JeremySkinner** [comment]
There's more involved with the FV setup- that's done by the call to AddFluentValidation. It registers the services necessary to hook FV into the validation pipeline.

If you want to register your validators manually, that's fine. Just call AddFluentValidation(fv => {}) and don't call RegisterValidatorsFromAssemblyContaining.

**Comment by grokky1** [comment]
Well that's something I didn't consider!

BTW, I tried it my way, and it seemed to work anyway. But I'll stick to your advice.

One more thing: if I register them manually, is it appropriate to use `.AddTransient`? Is that how your auto-registration works as well? Because I'm inclined to lean toward singleton, but unsure what the ramifications would be.

**Comment by JeremySkinner** [comment]
Until recently, I'd always recommend singleton as instantiating validators was extremely expensive (due to the lambda expression compilation), but I introduced some caching for expressions a while back which mitigates a lot of this.

Internally RegisterFromValidatorsContaining uses Transient, as it's simpler for users to understand...a lot of people who don't have much experience with IoC containers find it difficult to grasp why you can't have a singelton object with a transient dependency, so this removes that confusion. 

If your validators don't require transient dependencies I'd say register them as singleton.

**Comment by grokky1** [comment]
Yeah that sounds good. Thanks for this great library.
