### ISSUE TITLE
.OnlyLetters() API

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [JeremySkinner/FluentValidation#473]
What do you think about following extension?
```csharp
RuleFor(record => record.Name).OnlyLetters()`
```
Currently the only what to do it is using Must 
```csharp
RuleFor(record => record.Name).Must(BeAllLetters);
private bool BeAllLetters(string arg)
{
     return arg.All(char.IsLetter);
}
```

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. I don't think that's something that I'd want included in the core as it's easy enough to write an extension method of your own that does this (either using Must....you could in-line it rather than having a separate method) or alternatively using the Matches method with a Regex which is pretty concise. 

Thanks again though
