### ISSUE TITLE
Update EmailAddress regex?

### ISSUE THREAD

**Issue by MihaMarkic** [JeremySkinner/FluentValidation#491]
I see that the original email valdiation regex is a too forgiving probably.

For example it won't complain at #@£.com

Perhaps update it to something like [RFC 2822 Format](https://stackoverflow.com/questions/16167983/best-regular-expression-for-email-validation-in-c-sharp)?
I can do it if you agree.
`
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])`

**Comment by JeremySkinner** [comment]
To be honest I'd rather not change this. I've had a huge number of problems with the email regex in the past when we've looked at changing it, which has ended up making things worse (the previous version which was actually more robust could sometimes end up hanging the process because of a .net framework bug). I'd consider the current one "good enough" for most cases, and would recommend that use use the regex validator (Matches) if you want to use something different in your project.

**Comment by MihaMarkic** [comment]
Fair enough, isnt't hard to roll my own (actually did).
E-mail validation is really an incredibly tough problem... Who'd though that.
