### ISSUE TITLE
Feature request: WebApi - set default validator for child object and collections also allow to remove it

### ISSUE THREAD

**Issue by hidegh** [JeremySkinner/FluentValidation#515]
Current issue is, that I'm having person detail DTO with FV as address DTO's:

```
[Validator(typeof(EmployeeDetailsDtoValidator))]
public class EmployeeDetailsDto
{
	public EmployeeAddressDto HomeAddress { get; set; }
	public EmployeeAddressDto MailAddress { get; set; }
	...

[Validator(typeof(EmployeeAddressDtoValidator))]
public class EmployeeAddressDto
{
	...

public class EmployeeController : ApiController
{
	public IActionResult Register([FromBody] EmployeeDetailsDto details)
	{
		... [checking ModelState.IsValid]
```

In some cases, model validation might become complex, so will need dependencies from the container. The only way to safely build validators (IMO should be singletons) is to get them from the container...

```
public class EmployeeDetailsDtoValidator : AbstractValidator<EmployeeDetailsDto>
{
	public EmployeeDetailsDtoValidator(IValidator<EmployeeAddressDto> employeeAddressDtoValidator)
	{
		RuleFor(x => x.HomeAddress).SetValidator(employeeAddressDtoValidator);
		RuleFor(x => x.MailAddress).SetValidator(employeeAddressDtoValidator);
```

While the code above works and in overall the FV seems to have better infrastructure than the basic DataAnnotations and IValidatableObject (where a sub-class validation can't be turned on/off with When/Unless)... It'd be nice, if:

1.  the default validator based on the ValidatorAttribute would be appended automatically to a property/collection (if RuleBuilder would have access to the context...)
2. and if there would be a way to remove the defaultly assigned validator (1st one)
3. ...if there would be at least a parameterless SetValidator/SetCollectionValidator which would do No. 1 from the list, that'd be nice too...

**Comment by JeremySkinner** [comment]
Thanks for the feedback, a few comments:

> (IMO should be singletons)

Validator classes are designed to be singletons, and this is actually recommended most of the time. However, in a web context this can cause issues especially amongst inexperienced developers who don't understand the issues involved with dependency scoping (ie you can't have a singleton depend upon a request-scoped service). So the default behaviour (starting with the AspNetCore integration with v7) is to register them as transient as it's significantly safer. You can of course override this (and I believe the "legacy" web integration with MVC5 and WebAPI is still singleton by default if you're using the default attribute-based validator factory). 

>the default validator based on the ValidatorAttribute would be appended automatically to a property/collection

This does actually already happen (although I don't particularly like it) - it's part of the automatic MVC/WebApi integration. If you're using the ValidatorAttribute with the default validator factory (or the service provider in AspNetCore) then MVC/WebApi actually does this already for you. For each property on the model, the mvc validation infrastructure calls into FV's validator provider to obtain a validator for that type (if it can). This isn't really a feature of FV, but is just how the MVC/WebApi validation infrastructure works. However this *only* happens in a web context. 

> and if there would be a way to remove the defaultly assigned validator (1st one)

That isn't really possible as FluentValidation itself has no knowledge of MVC/WebApi's validation structure. Each time MVC asks for a validator, and executes it, this is a completely separate operation....it's not happening as part of a hierarcy. In fact, MVC instantiates and executes the child validators first - the parent validator hasn't even been run at this point. By the time the parent validator is run, the child validator execution has already happened, so there is no way to cancel it  short of preventing the child validator from being registered with the container in the first place. 

> if there would be at least a parameterless SetValidator/SetCollectionValidator which would do No. 1 from the list, that'd be nice too...

I'm not keen on this - this requires the validators themselves to have knowledge of how they were created and hold a reference back to the container. This means that there are now methods in the api that *require* the use of a container in order to work (which isn't something I want to force people to do), and it also introduces further lifecycle scoping problems as you're hanging onto a reference to the container. I think the it is better to be explicit and use constructor injection if you need the child validators to have their own services.

I know that's not really what you wanted to hear, but I hope it helps explain some of what's going on internally.

**Comment by hidegh** [comment]
Agree on not to use Singletons
