### ISSUE TITLE
The ASP.NET core integration instantiates validators per request

### ISSUE THREAD

**Issue by thedmi** [JeremySkinner/FluentValidation#529]
[According to the docs](https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#a-note-on-performance), validators should be instantiated as singletons. However, when using the [ASP.NET core integration](https://github.com/JeremySkinner/FluentValidation/wiki/i.-ASP.NET-Core-integration#integration-with-aspnet-core), the validators are instantiated per request.

I'm registering the validators like so:

    AddFluentValidation(c => c.RegisterValidatorsFromAssemblyContaining<SomeValidator>())

## Other approach

I also tried using the DI framework (Autofac in my case) directly and configure the validators as singletons there, but this doesn't work due to a chicken and egg problem in `ConfigureServices()`:

- Add MVC with fluent validation (requires custom DI registrations)
- Create DI container (requires MVC services already pre-registered in the `IServiceCollection`)
- Add custom DI registrations (requires DI container)

Some form of lazy evaluation in the validator lookup in `AddFluentValidation()` would solve this chicken and egg problem.

**Comment by JeremySkinner** [comment]
This is by design to avoid the lifecycle gotchas that come from having singleton-scoped objects with non singleton-scoped dependencies (eg depending on a request-scoped DbContext) - and actually in 7.1 they're transient, not per-request. 

These kind of lifecycle scoping issues are non-obvious to inexperienced developers, so making the validators transient by default makes it easier to get started. 

Since FV 6.4, there is expression tree caching that negates a lot of the performance issues that previously arose from having transient-scoped validators (although you are of course still free to register them as singletons if you prefer).

**Comment by thedmi** [comment]
Ah I was already wondering if you cache the expression trees, powerful technique :-) . Even better, then it won't matter to me that the validators are instantiated multiple times.

Thanks a lot for the quick response.

**Comment by JeremySkinner** [comment]
It's never going to be quite as performant as having the validators as singleton (which I still think is better), as not all expressions can easily be cached, but I think it's now good enough for most of the time.
