### ISSUE TITLE
GroupName property

### ISSUE THREAD

**Issue by flaviomarsili** [JeremySkinner/FluentValidation#553]
Hi,

Creating a abstractvalidator and the ruleset I would like to have a new WithGroupName extension that groups some properties. es
RuleSet (f => f.Name) .WithGroupName ("Person")
RuleSet (f => f.Surame) .WithGroupName ("Person")
And its GroupName property in ValidationFailure along with PropertyName, Message ...
Maybe by default GroupName = ParentName Es.
Public class Person
Name
Surname

GroupName = Person

Thanks

**Comment by JeremySkinner** [comment]
Hi, I don't really understand what you're asking. A RuleSet is just a grouping of rules - it doesn't have any properties associated with it, and you can't apply additional methods to it.

Did you mean a call to RuleFor instead of RuleSet?

You can associate any custom information with a failure using the `WithState` method. This then appears in the ValidationFailure inside the `CustomState` property. You can use this to store any custom information you need.

**Comment by flaviomarsili** [comment]
Sorry,
RuleFor(f => f.Name) .WithGroupName ( "Persona") 
RuleFor (f => f.Surame) .WithGroupName ( "Persona")

**Comment by flaviomarsili** [comment]
Ok,
i will use WithState
