### ISSUE TITLE
Stop validation on first failure with a specified severity level

### ISSUE THREAD

**Issue by draphyz** [JeremySkinner/FluentValidation#559]
Hello,

 I would like to be able to use the CascadeMode like this : 

  CascadeMode = CascadeMode.StopOnFirstError;

or

  CascadeMode = CascadeMode.StopOnFirstWarning;

**Comment by JeremySkinner** [comment]
That's not something that's supported, but I can try and look at adding it to a future version once 7.2 is done. 

Note that CascadeMode only applies to validators within the same RuleFor call, and the same would be try for any new options - is that what you intended?

**Comment by draphyz** [comment]
I think that the three current options are interesting (setting the cascade mode at the rule level, for all rules inside a single validator class or globally on the static ValidatorOptions class). It depends on how users want to control the validation process.  For my part, I need to stop globally (for all rules) the validation on the first failure with a severity level of error.

**Comment by JeremySkinner** [comment]
Ok, in that case CascadeMode is definitely not the feature that you should be using. Setting the Cascade on the validator or global level still only impacts validators within the same RuleFor chain. 

Separate calls to RuleFor remain completely independent - they cannot affect one another, or prevent each other from running. This is intentional and by design, so I'm not keen on adding a feature that changes this. 

However what I could do is add in a callback that's invoked each time a validator runs. FV currently has the "OnAnyFailure" callback (this is run at the end of each rule after all the validators in the same chain have finished), but I could add in another callback that allows you to 

Using the configuration api it'd look something like this:
```
RuleFor(x => x.Name).NotNull().WithSeverity(Severity.Error).NotEqual("Foo").Configure(cfg => {
   cfg.OnEachFailure(context => {
       if(context.Severity == Severity.Error) {
         context.ValidationCancelled = true; 
       }
   });
});
```

....you could wrap that in an extension method to make it easier to consume:

```
RuleFor(x => x.Name).NotNull().WithSeverity(Severity.Error).NotEqual("Foo").CancelValidationOnSeverity(Severity.Error)
```

But it would have to be applied to every rule in the validator like this. It'd also probably be possible to loop over all the rules once they've been created and apply this to each of them so you don't have to call the method on every rule. Would this work for you?

**Comment by draphyz** [comment]
OK, thank you for your explanations. Yes, this solution suits me perfectly.

**Comment by JeremySkinner** [comment]
Ok I'll try and get this added for the next version.

**Comment by draphyz** [comment]
Ok, thank you.

**Comment by JeremySkinner** [comment]
This won't make it into 7.3 as this release will focus on the rewrite of the aspnetcore integration. Aiming for 7.4 instead.

**Comment by JeremySkinner** [comment]
I've taken another look at this and I'm afraid this is not something that I'm going to implement. Unfortunately it completely breaks the async workflow, for which it's essential that rules are independent and cannot interact with each other directly.
