### ISSUE TITLE
IValidatorInterceptor for WebApi

### ISSUE THREAD

**Issue by jangert** [JeremySkinner/FluentValidation#58]
Hi,
I was hoping to find a IValidatorInterceptor interface in the FluentValidation.WebApi namespace. I can only find it in FluentValidation.Mvc name space.
I tried using the inteface from the FluentValidation.Mvc but the implemented methods won’t get invoked in my WebApi scenario.
Is the IValidatorInterceptor feature only supported for Mvc controllers?
Thanks, for a brilliant library

**Comment by JeremySkinner** [comment]
Hi, IValidatorInterecptor is not supported in WebApi. Sorry.

**Comment by jangert** [comment]
Ok, are there any plans to add this feature in the future?

**Comment by JeremySkinner** [comment]
Not currently I'm afraid. When I last looked, WebApi didn't have the extensibility points necessary to add this (this may have changed, but I don't actively work with WebApi so I haven't really got the desire to dig into this at the moment). With webapi and mvc being consolidated with asp.net 5, I'm hoping it'll be possible to have it for both, but this probably won't be for a while. Sorry.

**Comment by jangert** [comment]
No worries, thanks for info and quick replies Jeremy. We will find a way to work around this.

**Comment by abhay8** [comment]
Hi,

I found exactly the same problem. I only need interceptor because FluentValidation applies child validation rules automatically. If your parent object doesn't want validation to be applied, there is no other way to remove the child validator.
For example, I want to do something like this

[Validator(typeof(VehicleValidator)]
public class Vehicle
{
     ...
     Address VehicleAddress {get; set;}

     bool VehicleIsKeptAtHome {get; set;}
}

[Validator(typeof(AddressValidator)]
public class Address
{
    //
     String Address_Line_1 {get; set;}
     String Address_Line_2 {get; set;}
     ...



}

public class VehicleValidator : AbstractValidator<Parent>    {
        public VehicleValidator ()
        {
              ....
            RuleFor(x => x.VehicleAddress)
                .SetValidator(new IgnoreAddressValidator())
                .When(r => r.VehicleIsKeptAtHome == true);

            RuleFor(x => x.VehicleAddress)
                .SetValidator(new StandardAddressValidator())
                .When(r => r.VehicleIsKeptAtHome == false);
        }
    }

I want Vehicle Address to be validated only if vehicle is kept at home. Address model is also used in tons of other objects, such as HomeAddress, WorkAddress and in all other cases its absolutely mandatory field. I just needed to create exception just for the Vehicle model. But, FluentValidator always validates Address using AddressValidator and overrides the rules specified in the parent object's validator. This is why I wrote IValidatorInterceptor... But sadly, this only works on MVC project.. But, when the same model is validated on WebApi side, it ignores the interceptor and fails the validation. 

I think there should be an easy way to unset a default validator for child property and replace that with another custom validator... Or may be, when the parent validator sets a validator for its child property, the default validator for that child object shouldn't be invoked..In that case, there won't be any need for IValidatorInterceptor... Not sure about the best approach! 

For time being, I can easily work around this in the controller action code.. Please let me know if there is another way of dealing with this problem.

Regards,
