### ISSUE TITLE
Email validation. Turkish characters like ş İ ğ ç are accepted. (içŞöĞi@yourstore.com) 

### ISSUE THREAD

**Issue by AndreiMaz** [JeremySkinner/FluentValidation#580]
Found a problem today looking through logs. Turkish characters like ş İ ğ are accepted on most forms, which should not. Email providers not accepting these. I registered to demo store with içŞöĞi@yourstore.com.

**Comment by JeremySkinner** [comment]
Thanks for reporting this, but there are no plans to change this at the moment. 

Using regexes for email validation is never going to be fully comprehensive due to the complexity of the email address spec. The current regex being used is actually the same as the one used by the email attribute in the .net framework's EmailAddressAttribute (in DataAnnotations), and I plan to leave the FV validator using the same one for consistency. It works for most cases and is stable - in the past when I've tried switching to more comprehensive expressions you run into the problem of the regex timing out or consuming a lot of resources. A fully comprehensive regex is not practical, but this one is "good enough" most of the time. 

With email validation it's actually better to err in the side of letting input through rather than blocking (so you don't accidentally prevent a valid email address from getting through)

With .net core they ditched the regex completely and allow anything so long as it's in the (something)@(something) format. I'm not really sure how I feel about that! https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs#L37

You are of course welcome to use the `Matches` validator or another custom validator to do email validation if you don't want to use the regex built into the email validator.
