### ISSUE TITLE
null value ignored when using RuleFor and SetValidator

### ISSUE THREAD

**Issue by huysentruitw** [JeremySkinner/FluentValidation#582]
Could be related to #486 but I'm not getting any exception.

I've created an abstract validator that contains this rule:

```c#
RuleFor(x => x.Value).SetValidator(x => new BinaryFieldValueValidator((BinaryDataTypeInput) x.DataType)).When(x => x.DataType is BinaryDataTypeInput);
```

where `x.Value` is of type `object`. However, when `x.Value` is `null`, I'm not getting in the `BinaryFieldValueValidator` constructor, so the `SetValidator` lambda is not executed.

Any reason for that?

**Comment by JeremySkinner** [comment]
Hi, this isn’t related to that other issue you linked to. That’s to do with the root object being null, which isn’t allowed. 

Your rule looks fine to me - I tried it and couldn’t reproduce the problem. Could you put together a sample that reproduces the issue? Thanks.

**Comment by huysentruitw** [comment]
Sure, here you go:

**Sample code**

```c#
using System;
using FluentValidation;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Test true"); new ValueValidator().ValidateAndThrow(new BoolDataType { Value = true });
            Console.WriteLine("Test null"); new ValueValidator().ValidateAndThrow(new BoolDataType { Value = null });
            Console.WriteLine("Test false"); new ValueValidator().ValidateAndThrow(new BoolDataType { Value = false });
            Console.ReadKey();
        }
    }

    public class ValueValidator : AbstractValidator<DataType>
    {
        public ValueValidator()
        {
            RuleFor(x => x.Value).SetValidator(x => new BoolDataTypeValidator()).When(x => x is BoolDataType);
        }
    }

    public class BoolDataTypeValidator : AbstractValidator<object>
    {
        public BoolDataTypeValidator()
        {
            Console.WriteLine("BoolDataTypeValidator considered");
        }
    }

    public class DataType
    {
        public object Value { get; set; }
    }

    public class BoolDataType : DataType
    {
    }
}
```

**Output**

```
Test true
BoolDataTypeValidator considered
Test null
Test false
BoolDataTypeValidator considered
```

**Comment by JeremySkinner** [comment]
Ah, I see.

I'd assumed your BoolDataTypeValidator was a custom PropertyValidator implementation, but it's actually an AbstractValidator.

If you use SetValidator with an AbstractValidator derivative, then it will not be run if the property value is null. This is intentional behaviour as AbstractValidator derivatives are designed to validate the properties of a complex type, which cannot be done if the instance is null. If you want to check for null here, then you can precede the SetValidator call with a NotNull rule (although it doesn't seem like this is what you want in this case). 

You should probably switch to using a custom PropertyValidator. If the value is null this will then be passed to the validator where you can then run any kind of validation that you want. See the docs for custom property validators here: https://github.com/JeremySkinner/FluentValidation/wiki/e.-Custom-Validators#writing-a-custom-reusable-property-validator

**Comment by huysentruitw** [comment]
Thanks for your answer. A PropertyValidator doesn't really fit our use-case, but we've found a work-around for handling the null case.

**Comment by ivanabozhinova** [comment]
@huysentruitw could you please share your work-around?

**Comment by huysentruitw** [comment]
Because we do not allow nulls as a value, I could add an additional rule to fail when the value is null before even using the custom validators.
