### ISSUE TITLE
Build seems to require .NET 4.5, .NET 4.5.1 and .NET 4.52

### ISSUE THREAD

**Issue by wizofaus** [JeremySkinner/FluentValidation#597]
Various csproj files in the source target net45, net451 and net452 which seems to mean needing all 3 versions of the reference assemblies.
Is there any reason not to just pick one (preferably net452)? I modified all the csproj files to use net452 and it now seems to be building for me (I only have .NET 4.5.2 installed).

**Comment by JeremySkinner** [comment]
It's for backwards compatibility. FluentValidation was originally build to target 4.5, and the core assembly still does. There's no reason to exclude users running on older versions of the framework as it still works correctly. 

To maximize compatibility, each part FluentValidation will run on the oldest possible version that supports the features it needs. 

FluentValidation.dll:
- Targets netstandard1.0 (for modern nuget clients) 
- Targets net45 (for anyone still running older nuget clients or versions of VS that don't support netstandard). There is no need to impose a higher version requirement.

FluentValidation.Mvc5 and FluentValidation.WebApi
- Targets net45. There's no need to target a newer framework as it runs just fine on 4.5, and would be a breaking change for consumers. With the release of netcore, these 2 are now essentially legacy components that will receive no further updates. 

FluentValidation.AspNetCore
- Targets netstandard1.6 and net451. This is the minimum version requirement for AspNetCore 1.0. 

The test projects target a mixture of framework versions. Some of these are because I need to test on a specific framework (eg netcoreapp1 vs netcoreapp2). The main test projects target net452 as this makes the code slightly simpler in some places vs running on net45. 

No plans to change this I'm afraid.

**Comment by wizofaus** [comment]
That's the issue, I do have 4.5.2 installed and I couldn't build the projects that targeted 4.5 and 4.5.1, until I modified them to point to net452.

**Comment by JeremySkinner** [comment]
Visual Studio 2017 with the 15.4 update,
.net core 1.1 + SDK
.net core 2.0 + SDK

**Comment by wizofaus** [comment]
Is that documented anywhere? Anyway if you're happy for those to be the requirements then all good, but I can confirm it is possible to build for local development with just dotnet 2.0 and .net 4.52 with some tweaking.

**Comment by JeremySkinner** [comment]
Yes, I am happy for those to be the requirements as it’s still important to produce builds that will run on older framework versions. I’ll make sure it’s added to the documentation.
