### ISSUE TITLE
Will there be a DNX Core 5 version of this library created?

### ISSUE THREAD

**Issue by csaloio** [JeremySkinner/FluentValidation#60]
It would be great if this was useable w/ DNX core projects.

**Comment by JeremySkinner** [comment]
Yes, there will be.

**Comment by jrharmon** [comment]
Any rough time frame on when you are planning on this?

Thanks!

**Comment by JeremySkinner** [comment]
The initial work is done, but it was done against the VS2015 beta before the aspnetcore -> dnxcore rename, so that all still needs doing. 

All the automatic integration with ASP.NET MVC needs writing too, but this needs the new validation API in MVC6 to be finished first. 

I'd say this is still several months away from being finished, and I'm away for all of July, August and half of September, so it's unlikely to be until later in the year - sorry.

**Comment by SeanKilleen** [comment]
Cleanup: Closing this issue since it hasn't had activity in about a year.
