### ISSUE TITLE
Client side validation attributes for nested properties - AspNetCore

### ISSUE THREAD

**Issue by drewlsvern** [JeremySkinner/FluentValidation#622]
I am trying to use a nested model and still retain client side validation. I can only seem to get it to work if the Validator is not nested. I need it to be nested as I have conditional logic (.When()) between the models.

[Here ](https://gitlab.com/drewlsvern/TestFluentValidationAPI)is a sample project.

**Comment by JeremySkinner** [comment]
Thanks, I’ll try and look at it this week but might not be until Friday or Saturday.

**Comment by JeremySkinner** [comment]
I had a look at the sample project - you don't have all the validators wired up with the container which is why you're not seeing the clientside validation. 

MVC will only generate clientside validation attributes for models that it can locate a validator for, so you need to wire up all your validators in the app startup routine, not just the validator for the TestViewModel. 

Once I added the other 2 registrations the clientside attributes were all generated correctly. 

```
services.AddTransient<IValidator<TestViewModel>, TestViewModelValidator>();
services.AddTransient<IValidator<TestPersonViewModel>, TestPersonViewModelValidator>();
services.AddTransient<IValidator<TestAddressViewModel>, TestAddressViewModelValidator>();
```
