### ISSUE TITLE
Warnings during build .net core project

### ISSUE THREAD

**Issue by jincod** [JeremySkinner/FluentValidation#638]
Hi!

Thank you for your project.

I'm using `FluentValidation.AspNetCore 7.2.1`.

I have warnings during build:

```
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Win32.Registry" that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed. [d:\Projects\FluentValidationBuildWarnings\FluentValidationBuildWarnings.csproj]

C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "System.Security.Principal.Windows" that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed. [d:\Projects\FluentValidationBuildWarnings\FluentValidationBuildWarnings.csproj]
```
Issue demonstration: https://github.com/jincod/FluentValidationBuildWarnings

Unfortunately, I did find cause of this behavior.

**Comment by JeremySkinner** [comment]
Hi, that's not actually related to FluentValidation. 

As the message says, setting the build log to detailed will show you what's happening. Essentially it's complaining because you're targetting netstandard2.0 but you're bringing in Microsoft.AspNetCore.Mvc 1.1 which targets netstandard1.6 and the .net sdk it's getting confused between different version of mscorlib (the .net core build process is still pretty buggy) 

Nuget is bringing in microsoft.aspnetcore.mvc 1.1 because that's the minimum version supported by FluentValidation. But your project is targetting .NET Core 2.0, so you should be referencing microsoft.aspnetcore.mvc 2.0. Add the following to your project and you'll see the warning goes away:

```
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
```

**Comment by JeremySkinner** [comment]
Also; if you upgrade to FluentValidation 7.3-beta2 you’ll see this doesn’t happen as it’s metadata explicitly targets different versions of Microsoft.AspNetCore.Mvc depending on which netstandard version you’re running on. So going forward you won’t run into this.

**Comment by jincod** [comment]
`FluentValidation 7.3-beta2` works for me

Thanks a lot!
