### ISSUE TITLE
Exception thrown on startup in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by sid-6581** [JeremySkinner/FluentValidation#643]
In my ASP.NET Core MVC 2.0 project I get the following exception in FluentValidation 7.3 (it works fine in 7.2.1):

`MissingMethodException: Method not found: 'Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.ModelBindingMessageProvider Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.BindingMetadata.get_ModelBindingMessageProvider()'.`

This is thrown from `FluentValidation.AspNetCore.FluentValidationBindingMetadataProvider.CreateBindingMetadata(BindingMetadataProviderContext context)`.

I am targeting the full .NET Framework if that makes a difference.

**Comment by JeremySkinner** [comment]
Yes I believe this is related to running on full framework.

It looks like you're referencing the version of the dll that's compiled against net451 (which is compiled against asp.net core 1.1) instead of the netstandard2 build (which is compiled against asp.net core 2.0). It appears that nuget always adds a reference to the netXX version of the assembly rather than the netstandard verison if you're on the full framework. 

Simplest fix for now is for me to just remove the asp.net core 1.1 compatibility completely - I'll push out 7.3.1 shortly and post an update here when it's done.

**Comment by JeremySkinner** [comment]
I've just pushed out 7.3.1 - could you upgrade and try again? (It might take up to an hour before it shows in the nuget feed)

**Comment by sid-6581** [comment]
Thanks for getting that done so quickly! I've been trying to check NuGet for updates, but I'm still just seeing 7.3.0. Is it just NuGet being slow, or did something go wrong pushing it out?

**Comment by JeremySkinner** [comment]
Nuget’s being slow. Sadly pushing a package is no longer immediate. Hopefully it’ll show up today.

**Comment by sid-6581** [comment]
It showed up and worked like a charm! 7.3.1 fixed this issue and #644.

**Comment by JeremySkinner** [comment]
Great! I'll close this for now, let me know if you run into any other issues.
