### ISSUE TITLE
Classes of same interface type with different rules - cast error

### ISSUE THREAD

**Issue by totpero** [JeremySkinner/FluentValidation#690]
Hi,

I have one scenario and i don't know how to handle it.

I have one class with a collection property:
`RuleFor(o => o.MyCollection).SetCollectionValidator(new MyCollectionValidator());`

In `MyCollectionValidator: AbstractValidator<ElementOfCollection>`
I have one property of type `MyInterface (MyInterfaceProperty)`,
This property can be in some elements of `MyCollection` of type `Class1` and in other cases of type `Class2`.

I want something like this:
```
 When(o => o.MyInterfaceProperty is Class1, () =>
            {
                RuleFor(o => (Class1)o.MyInterfaceProperty).SetValidator(new Class1Validator());
            });

            When(o => o.MyInterfaceProperty is Class2, () =>
            {
                RuleFor(o => (Class2)o.MyInterfaceProperty).SetValidator(new Class2Validator());
            });
```

But when i try to validate i get InvalidCastException.

**Comment by JeremySkinner** [comment]
Hi,

This approach won't work. Calls to RuleFor are always invoked immediately - they are not lazily evaluated when inside a When block, so the cast will be happening every time which is why you're getting an InvalidCastException.

You have two options. The simplest is to use the as operator to do a safe cast and get rid of the When block:

```
RuleFor(x => x.MyInterfaceProperty as Class2).When(prop => prop != null).SetValidator(new Class2Validator()).OverridePropertyName("MyInterfaceProperty"); 
```

This is the easiest way to do this, but has a performance implication as it will bypass the expression tree cache, so the expression will be compiled in every instantiation of the validator (only simple property expressions are cached).

An alternative approach is to write a custom PropertyValidator implementation that can handle the polymorphism and will internally select whether or not to use the Class1Validator or the Class2Validator. This issue has an example of how to do this: https://github.com/JeremySkinner/FluentValidation/issues/111 In that post, the user was trying to handle validating polymorphic elements in a collection, which is not the same as what you're trying to achieve, but the approach would be very similar.

**Comment by totpero** [comment]
It works,
Thanks!
