### ISSUE TITLE
CustomizeValidatorAttribute for WebAPI

### ISSUE THREAD

**Issue by slgal** [JeremySkinner/FluentValidation#704]
Hi @JeremySkinner ! I know that CustomizeValidatorAttribute  is not supported by WebApi, but I really need it in my project. So I fork your  repo to https://github.com/slgal/FluentValidation. 
I have copied classes from MVC project but I have an issue that WebApi is not call CustomizeValidatorAttribute as a ModelBinder for my models. 
To be it called I need to use this style:

`public IHttpActionResult RulesetTestModel([ModelBinder(typeof(CustomizeValidatorAttribute)]RulesetTestModel model)`
instead of 
`public IHttpActionResult RulesetTestModel([CustomizeValidator(RuleSet = "Names")]RulesetTestModel model)`

But how to pass the rules in that case? I would like to ask your advice about how this can be fixed, since I have no idea about it.

Thanks in advance!

**Comment by JeremySkinner** [comment]
Hi, that's not going to work I'm afraid. 

Last time I checked, WebApi does not make attribute information available inside the ModelValidatorProvider, meaning it is not possible to implement the CustomizeValidatorAttribute in WebApi (which is why it's not been implemented before and is not supported). 

If you want to pass rulesets to the validator then you'll need to disable the automatic validation and instead instantiate the validator  and directly invoke its Validate method passing in the ruleset you want. 

Also just to clarify this is only an issue in 'legacy' WebApi. Modern versions of WebApi (part of asp.net Core) will work correctly with the CustomizeValidatorAttribute.

**Comment by osnoser1** [comment]
Hi @JeremySkinner, last year I made a small implementation taking part of the implementation of FluentValidation, I thought about doing a PR, but I do not know if you would be interested.

I do not know if you think the approach is right.

[ValidateAttribute.zip](https://github.com/JeremySkinner/FluentValidation/files/1783486/ValidateAttribute.zip)

**Comment by JeremySkinner** [comment]
Thanks for this, I’ll try and review it this week and see if it’s something we can build in.

**Comment by JeremySkinner** [comment]
I spent some more time digging through the WebApi source code today and believe I may have found a way to enable support for CustomizeValidator. I’ll post an update once I’ve done some more testing.

**Comment by JeremySkinner** [comment]
This is implemented in FluentValidation.WebApi 7.5.1
