### ISSUE TITLE
More .When overloads

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#710]
Would it be possible to have more .When overloads?

Currently there's only one, which contains the root object, however I would like one that includes the property, like the .Must overload which has both the root and the property.

That way I could create extensions that could target the TProperty instead of the root object.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. I'll add this to the backlog to look at for a future version. There are quite a few areas that would need to be modified to completely support this:

- Chained When
- Chained Unless
- Chained WhenAsync
- Chained UnlessAsync
- Top-level When (AbstractValidator.When)
- Top-level Unless
- Top-level WhenAsync
- Top-level UnlessAsync

If you want to have a go at submitting a pull request that adds the new overload for all these then I'd be happy to take a look at it, otherwise I'll try and get to it sometime after 7.6 is done.

**Comment by StefanHaug** [comment]
I'll keep this in mind Jeremy, but I got too much on my plate both professionally and privately :(

**Comment by JeremySkinner** [comment]
As do I.

**Comment by JeremySkinner** [comment]
After reviewing this, I'm not keen on adding so many new overloads for something that doesn't seem like a common scenario. However, what I will do is change the signature for `DelegatingValidator`'s constructor, and `PropertyRule.ApplyCondition` to make it easy to add these methods if you want them, eg you will be able to define an extension method like this:

```
public static IRuleBuilderOptions<T, TProperty> When<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, Func<T, TProperty, bool> predicate) {
	return rule.Configure(config => {
		config.ApplyCondition(ctx => predicate((T)ctx.Instance, (TProperty)ctx.PropertyValue));
	});
}
```

...which can then be used like this:

```
RuleFor(x => x.Surname).Must((x,surname) => surname.Length > 5).When((x, surname) => surname != null);
```

This committed in a34154f and will be in the 8.0 release.
