### ISSUE TITLE
Update to Nuget 7.5.0 fails.

### ISSUE THREAD

**Issue by anirbanbasu** [JeremySkinner/FluentValidation#711]
Currently, I am using version 7.3.4 in my Xamarin Forms PCL project, and it works fine. However, an attempt to update the Nuget package to 7.5.0 fails with the following error.

_Could not install package 'FluentValidation 7.5.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._

What has changed from 7.3.4 that is breaking this update?

**Comment by JeremySkinner** [comment]
Hi, as of 7.5 the minimum supported runtime version is now netstandard1.1 (previously it was netstandard1.0), 

You should be able to still use netstandard1.1 libraries in Xamarin but you’ll probably need to target a different PCL profile (or switch to netstandard if you can). You can find the platform mapping here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by anirbanbasu** [comment]
Thanks a lot. I changed to Profile111, and tried updating. This time, the problem is with another package, which is being installed/updated as part of the FluentValidation update process.

_Could not install package 'System.ComponentModel.Annotations 4.4.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._

Earlier, I tried a Profile151 and that did not go well because some of the other existing packages (rather critical ones for my project) were not targeted for that profile.

**Comment by JeremySkinner** [comment]
That's strange - System.ComponentModel.Annotations 4.4.1 targets netstandard1.1 so should be compatible with the old Profile111. Could you confirm which version of nuget you're using to install the packages?

**Comment by anirbanbasu** [comment]
NuGet Version: 4.3.0.4406. The list of the IDE extensions of my Visual Studio for Mac reports NuGet Package Management Version 7.4, which I suppose refers to the version of the extension as opposed to that of NuGet.

**Comment by JeremySkinner** [comment]
I'm not really sure what to say...it seems something is definitely wrong with the mappings between netstandard and legacy PCLs, but I don't know enough about this to suggest a workaround.  Are you definitely unable to move to netstandard in your project? If not then if all else fails then you may need to downgrade to FV 7.4.

**Comment by anirbanbasu** [comment]
Thanks, that's ok. I am currently on FV 7.3.4 and it seems to work fine. Nothing else is broken so far. I cannot change to netstandard -- tried already. I am not very clued up on the NuGet packages to try to find a workaround either. I will wait until the packages I use can be moved to netstandard.

**Comment by ainsophical** [comment]
coughing up the same "System.ComponentModel.Annotations 4.4.1" when trying to upgrade from 7.4 to 7.5 in xamarin.forms project.

**Comment by JeremySkinner** [comment]
@ainsophical What platform are you targeting? Is it a legacy PCL too or are you on netstandard?

**Comment by JeremySkinner** [comment]
Just a further update on this, it's not limited to Xamarin or VS For Mac - it also happens on Windows under legacy PCLs

**Comment by ainsophical** [comment]
@JeremySkinner Hey Jeremy. I'm on netstandard.

**Comment by JeremySkinner** [comment]
@ainsophical which version of netstandard? 1.1?

**Comment by JeremySkinner** [comment]
@anirbanbasu  Ok I think I understand what is happening with regards to PCLs. Although Profile111 supports netstandard1.1, the System.ComponentModel.Annotations package is not a "real" package - it just provides type forwarding information to underling framework assemblies (System.ComponentModel.DataAnnotations in this case). 

Unfortunately System.ComponentModel.DataAnnotations is NOT included as part of the PCL surface area, so the type forwarding can't work. 

So even though System.ComponentModel.Annotations targets netstandard1.1 and Profile111 is compatible with netstandard1.1, the two will not work together as System.ComponentModel.Annotations does not directly include any assemblies - it tries to provide type forwarding to something that doesn't exist.

The dependency on DataAnnotations was added because in previous version, FluentValidation would perform a reflection-based discovery of DisplayAttribute/DisplayNameAttribute, but this had several issues (performance and issues with attribute inheritance). The direct dependency removed these issues, but clearly it's introduced others.

It's particularly frustrating as this is only for 1 small area of the codebase, and according to Microsoft's own compatibility mappings it "should" work but obviously doesn't because of the limitations of APIs that are available in legacy PCLs. 

So the options are:
- Remove all support for legacy PCLs going forward. As much as I'd like to drop all support for legacy tech, there are definitely people still using them so I think this would be a shame. 
- Remove the direct DataAnnotations reference and go back to an alternative discovery method. 
- Provide explicit builds of FluentValidation for PCL targets (and possibly netstandard1.0) that do not include the data annotaitons reference and removes support for Display attributes. 

I'll need to take some time to think through the implications and will see what I can come up with.

**Comment by ainsophical** [comment]
@JeremySkinner Netstandard 2.01

**Comment by JeremySkinner** [comment]
@anirbanbasu Works fine for me under netstandard2. As far as I can tell at the moment the problem is limited to legacy PCLs. If you're seeing this under netstandard2 could you send me a small sample project that reproduces the issue? Thanks

**Comment by ainsophical** [comment]
@JeremySkinner I'll see what I can do. Its part of a huge project for a client.

**Comment by anirbanbasu** [comment]
@JeremySkinner thanks for the explanation. Let me know what you plan to do. I am on Profile111, netstandard1.1, not the netstandard2, so was your last message supposed to address @ainsophical instead of me? Regarding dropping PCL, I would also like to do so but some of the other critical packages I use do not quite support netstandard yet.

**Comment by JeremySkinner** [comment]
Yes sorry, I tagged you but mistake in that reply. 

I’ll try and spend some more time on this today and will see what I can come up with

**Comment by JeremySkinner** [comment]
@anirbanbasu In the end I decided to remove the direct DataAnnotations reference for netstandard1.1 builds, but keep it for net45 and netstandard2 builds, so PCLs won't include this behaviour and won't run into the issue. I also added a netstandard1.6 build so that any consumers targetting netcoreapp1 don't end up losing functionality.

I've released this to nuget as 7.5.1. It should show up in the package feed shortly. Could you give it a try?

**Comment by anirbanbasu** [comment]
Thanks a lot. FV updated to 7.5.1 but with warnings. Not sure if this is relevant to FV?

_One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'NETStandard.Library 2.0.1 constraint: System.Runtime.InteropServices.RuntimeInformation (>= 4.3.0)'_

**Comment by JeremySkinner** [comment]
I don’t think that’s related.

**Comment by anirbanbasu** [comment]
Thanks very much!
