### ISSUE TITLE
Modify / remove rule

### ISSUE THREAD

**Issue by qtty1234** [JeremySkinner/FluentValidation#713]
I have a common validator named CustomerValidator.
```
    public class CustomerValidator : AbstractValidator<Customer>
    {
        public CustomerValidator()
        {
            RuleFor(x => x.Salutation)
                .MaximumLength(50);

            RuleFor(x => x.Email)
                .NotNullOrWhiteSpace()
                .MaximumLength(Constants.EmailNumberMaxLength)
                .EmailAddress();

            RuleFor(x => x.FirstName)
                .NotNullOrWhiteSpace()
                .MaximumLength(40)
                .Matches(Constants.TagExclusionRegex);

            RuleFor(x => x.LastName)
                .NotNullOrWhiteSpace()
                .MaximumLength(40)
                .Matches(Constants.TagExclusionRegex);
        }
    }
```

I am going to modify a rule.

```
var validator = new CustomerValidator();
validator.RuleFor(x => x.Salutation).MaximumLength(10);
```

In this case I will have two validators (maxLength = 10 and maxLength = 50)

So, it would be nice to have ability to remove or overload the rule or rules. Something like

```
var validator = new CustomerValidator();
validator.RemoveRule(x => x.Email);
validator.OverloadRule(x => x.MaximumLength).MaximumLength(10);

```

Is there way to create the methods?

**Comment by JeremySkinner** [comment]
Validators are designed to be immutable so that they can be thread-safe. Because of this, runtime modification of validators (including removing or modifying rules) is not supported or recommended. 

That being said, it can be done, see this code: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/BackwardsCompatibility.cs#L242-L259

...but I really wouldn't recommend it. Instead I'd suggest either using separate validators or use something like the RuleSets feature to explicitly select which rules you want to run.
