### ISSUE TITLE
MVC Guid indices and IIndexedCollectionItem

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#715]
Couldn't really see how to use this interface, as you've stated in another post the GUID isn't exactly available.

However, I've been thinking a little about this problem, and would like your thoughts on the issue.

When a model is posted to a controller all the indices are guid's when using BeginCollectionItem. The ModelState will already contain all the models in sorted order.

E.g. 
MyCollection[aa80df46-2475-4c6f-9503-a15dbdbba45a].Description
MyCollection[0c00f4b4-f7ce-42b2-afc9-e5f706afd814].Description

When using FV the indices are integers.

Wouldn't it be possible to map the indices from the ModelState to the indices in FV?

MyCollection[0] would belong to MyCollection[aa80df46-2475-4c6f-9503-a15dbdbba45a] etc.

**Comment by JeremySkinner** [comment]
> Couldn't really see how to use this interface

It's a very simple interface - you implement it within the item inside the collection, and it just allows you to supply a value that should be used as the indexer when building the property name (for example, you could return the value of a different property to use as the indexer). It's not useful for BeginCollectionItem though, as BeginCollectionItem doesn't actually use the value of any property on the model to generate its guids. 

> Wouldn't it be possible to map the indices from the ModelState to the indices in FV?

How would you suggest doing that?

**Comment by StefanHaug** [comment]
I haven't written any code to do it but if I would proceed with it I would loop thought the ModelState dictionary, parse the keys, breaking them up by property name with index and adding them to a temporary dictionary of sorts.

Since the items in the ModelState is chronological it makes sense to say that it could be mapped - the first occurence of MyCollection with a GUID could be said to have index 0. 

Building the indexed would have to be recursive though, as property names could be repeated inside the graph.

**Comment by JeremySkinner** [comment]
I'm not sure how feasible this would be as the information in ModelState isn't present when the validator is being executed. I'm also not sure how you'd determine whether to perform the processing or not. 

Personally I don't think this is something worth investing time in, but if you decide to put together a prototype I'll take a look.

**Comment by StefanHaug** [comment]
I'm thinking this'll be something that occurs after the validator has been manually executed - not using FV's MVC integration.

I'll see if i'll be able to put together a prototype.

**Comment by JeremySkinner** [comment]
Thanks, sounds good. Let me know if you have any questions about the MVC integration internals.

**Comment by StefanHaug** [comment]
I don't use the MVC integration as I often work with partial models - which fails validation :)

**Comment by JeremySkinner** [comment]
Sorry not sure I understand. I thought this post was about the automatic integration between MVC and FluentValidation?

**Comment by StefanHaug** [comment]
Not directly - it's about the reported difficulties in mapping validation errors to collections using BeginCollectionItem which as you know uses GUID for indices. I'm sorry for not being more clear in the original posting.

**Comment by JeremySkinner** [comment]
Right, but those issues are specifically related to using the automatic integration with MVC as FluentValidation's interaction with ModelState values happen via the ModelValidatorProvider API. Any solution for working with BeginCollectionItem would need to work within the confines of the ModelValidatorProvider api in order to be included in FluentValidation.

**Comment by StefanHaug** [comment]
Doesn't handle nesting but I guess you can see the essence of it. I call it in the controller action before returning the view. It seems to work.

		public static void AddToModelState(this ValidationResult result, ModelStateDictionary modelState)
		{
			void decode(string prop, out string name, out string indice)
			{
				var indiceStart = prop.IndexOf('[');
				var indiceEnd = prop.IndexOf(']', indiceStart);
				name = prop.Substring(0, indiceStart);
				indice = prop.Substring(indiceStart + 1, indiceEnd - indiceStart - 1);
			}
			// TODO: Convert indexes to guids
			Dictionary<string, List<string>> lists = new Dictionary<string, List<string>>();

			// Parse modelState
			foreach (var kvp in modelState)
			{
				var properties = kvp.Key.Split('.');
				foreach (var prop in properties)
					if (prop.EndsWith("]"))
					{
						decode(prop, out string name, out string indice);
						if (!lists.ContainsKey(name))
							lists.Add(name, new List<string>());
						if (!lists[name].Contains(indice))
							lists[name].Add(indice);
					}

			}


			foreach (var error in result.Errors)
			{
				var propertyName = string.Empty;
				foreach (var prop in error.PropertyName.Split('.'))
				{
					var temp = prop;
					if (temp.EndsWith("]"))
					{
						decode(temp, out string name, out string indice);
						if (lists.ContainsKey(name))
							temp = $"{name}[{lists[name][int.Parse(indice)]}]";
					}
					propertyName += string.IsNullOrEmpty(propertyName) ? temp : $".{temp}";
				}

				modelState.AddModelError(propertyName, error.ErrorMessage);
			}
		}

**Comment by JeremySkinner** [comment]
Thanks for this. As I mentioned before, to get something like this included in FluentValidation it would need to be modified to work as part of the automatic MVC integration as this is the primary way users use FluentValidation within an MVC project (as well as the AddToModelstate call). I think the following would need to be done:

- For asp.net core, this would need to take place within the custom ObjectModelValidator. The issue here is that the ValidationResult does not exist at this point - the conversion between FluentValidation's ValidationResult and ModelState has already been done, and MVC has populated the ModelState dictionary.

- I think there should be some way of explictly specifying which ModelState entries to process rather parsing all entries. For the automatic MVC integration, this could be specified with an attribute on the controller action. This could help mitigate the issue above

- We'd need appropriate tests to be added to cover the functionality

It'd also be worth thinking about whether this should actually be in the core FluentValidation packages at all, or if it should be somewhere else as BeginCollectionItem is not actually part of MVC.

**Comment by StefanHaug** [comment]
I cannot see a place for this in FV really, i just thought to share my thoughts on the matter as i observed some issues being reported on the matter. 

I’m curious as to how people use MVC and collections without BeginCollectionItem.
