### ISSUE TITLE
Extremely bizzare Fluent Validation behaviour

### ISSUE THREAD

**Issue by Eclipse-Computing** [JeremySkinner/FluentValidation#765]
Using a Database-first project on an extremely old Web Forms database with inappropriate field types (`nchar`, ftw), I am experiencing wildly bizzare Fluent Validation behaviour, with almost no client-side validation working and inconsistent server-side validation working.

A full write-up is at https://stackoverflow.com/questions/50538392/extremely-bizarre-fluent-validation-behaviour

I don’t know if the problems arise from my implementation, or if there really is something wrong with FV. Posting here as I am desperate for anything that might help.

**Comment by JeremySkinner** [comment]
Hi, this really doesn’t sound like a problem with FluentValiation. It’s most likely something else in the project that’s causing the weirdness.

Firstly I’d suggest completely lacking client side validation out of the picture. FluentValidation doesnt provide any client side validation by itself (only metadata) so I’d first suggest disabling client side validation to eliminate a moving part. In fact, I’d completely disable JavaScript to eliminate anything client side that might be doing something weird with the form. 

Next I’d try and remove as many fields as possible from the model and the UI so you’ve got as simple a repro as possible. 

Next I’d suggest trying to reproduce the problem with DataAnnotations attributes instead of FluentValidation. If the problems only occur with FV then I can help dig into it further. If not then we know that MVC itself is going wrong somewhere.  

Let me know if you make any progress.

**Comment by Eclipse-Computing** [comment]
I am working off of a pre-existing database, which is currently powering a Web Forms site. What I am building is a subdomain under a completely different domain from the Web Forms site that is supposed to only *insert* data into that database, and is supposed to be otherwise completely separate from the Web Forms site (which is why it is not built into the Web Forms site).

Because the DB already existed, I did a Database-First build, which created all of my data models, but made no Fluent-style configuration files as Code-First _prefers_ to have (and which I create when I do code-first). As such, the data models only have your basic data types, and a `string` is only defined as such even though all string fields in the DB are `nchar` (why this was done, I have no clue, as nvarchar was available in MSSQL server long before the site got built). As such, I cannot see how the `nchar` type of the string fields in the DB could possibly be affecting how Fluent Validation is behaving (the failure for `.NotEmpty()` and `.NotNull()` to function on either client-side or server-side except under extremely specific circumstances).

With that said, I have turned off client-side JS entirely, and server-side validation still fails to trigger on anything other than the drop-down menus.

If I comment out everything except for the first and last names (the only two *required* pieces of information in the DB), server-side validation fails to kick in at all, and the system throws an exception because null values are being passed to fields that are required content.

When I comment out any and all Fluent Validation (the model decoration as well as everything within the namespace of the validation file associated with the model decoration), and fall back to Data Annotations:

```
  public class MoreInfoViewModel {
    [DisplayName(@"First Name")]
    [Required(AllowEmptyStrings = false)]
    [DisplayFormat(ConvertEmptyStringToNull = false)]
    public string FirstName { get; set; } = string.Empty;
    [DisplayName(@"Last Name")]
    [Required(AllowEmptyStrings = false)]
    [DisplayFormat(ConvertEmptyStringToNull = false)]
    public string LastName { get; set; } = string.Empty;
  }
```

The data annotations _do_ work. They _do_ catch the blank fields before things get shipped off to the DB.

So according to your breakdown, this _appears_ to be a FV issue. Suggestions?

**Comment by Eclipse-Computing** [comment]
I have gone a step further, and have confirmed that only certain types of server-side validation is currently functional under Fluent Validation.

I backed up to your step 1: disabling all client-side JS. Everything was back to original except for the JS.

Then I did a plain submit without entering any data: as before, only the three drop-down menus were caught by any validation. All text fields failed to have their `.NotEmpty()` validators triggered.

Then I reloaded the page and tried to test those fields with minimum length validators _in addition to_ the `.NotEmpty()` validators. Since the First Name and Last Name needed at least two characters, I put only one character into each… and their validators failed to fire.

I then went through every text field, and tested their validator for every string variation that would fire one of its validators. For example, for the eMail field I tried using only a partial eMail. For the phone number, an incomplete (7-digit) phone number. For every combination I tried, all server-side validation failed to fire on all text fields.

This was confirmed by selecting values for all three drop-down menus, and I got a “Object reference not set to an instance of an object.” data insertion exception again, even with some text fields partially (but inadequately) filled: the form was being validated _only_ for the drop-down menus, and all validation for anything else was being ignored.

So FV _works_, it’s just not working for anything beyond drop-down menus. Which is really weird, because the only validation firing on those is the `.NotEmpty()` which is failing to fire everywhere else.

**Comment by Eclipse-Computing** [comment]
Holy hell -- I just turned all drop-down select menus into nullable `int?` fields, _and no fluent validation fired at all._

Please understand that as non-nullable `int` fields, fluent validation _did_ fire, as I got the custom error messages that I put into FV. Which is why I considered FV to be “up and running” to _some_ degree, just not fully functional.

So:

Fluent Validation only fires on drop-down select menus for which the model field is an `int` data type. Changing it to an `int?` data type causes FV to not fire at all, anywhere.

**Comment by JeremySkinner** [comment]
This definitely sounds like something wrong in MVC rather than FluentValidation. Can you put together a small/cutdown sample project that reproduces the issue and send it to me?

**Comment by Eclipse-Computing** [comment]
Would this include the database? Because unfortunately that is a 12-year old monster currently in MSSQL 2012 format and clocking in at almost 700Mb even when compressed.

**Comment by JeremySkinner** [comment]
No, just a web project that I can run to see what happens.

**Comment by Eclipse-Computing** [comment]
How would you like to receive it?

**Comment by Eclipse-Computing** [comment]
It has been uploaded and shared. Thank you so very much for taking your Sunday to help me, it really does mean a lot, as this is the first project in over a dozen where FV has failed to function out of the box.

When you look at it, you can technically mess with any form you want, but I was using the “More Info” one as my primary example.

Also, another WTF: the login page works flawlessly, at least server-side with JS turned off. And I believe it was working client-side as well. Notice how the error messages are identical to what I have in the login page’s validator, and the username field is a pure text field which I only use a `.NotEmpty()` on. However, this field in the DB is an `int`, and this text field is totally disconnected from the DB because I convert it’s contents to an `int` and assign it to a variable before I go search the DB for that value.

Maybe that’s the trick -- pull all the items out of the ViewModel and assign them to variables before stuffing those variables into an empty Data Model to update the DB with. Essentially “air gap” the data. Turn it into a sneakernet so the destination cannot screw with the source.

**Comment by Eclipse-Computing** [comment]
I am in British Columbia, Canada, so it’s almost 2AM here -- I am going to crash and check this thread first thing in the morning. Give me at least 6hrs to reply.

**Comment by JeremySkinner** [comment]
Thanks for sending the project through. I think I understand what is happening, and it is actually part of the design of MVC5 - it is considered "correct", although unintuitive and frustrating. 

Basically it comes to this: MVC's validation infrastructure is written in such a way that non-nullable value types (such as ints/datetimes) must have a value specified, or they will not be passed to the validation provider (in this case, FluentValidation). 

The long explanation:

MVC's validation infrastructure is designed to validate values a field at a time. It works by validating each field value. If validation passes, then the property value is set to the supplied value from the field.  This is the complete opposite of how FluentValidation works, which requires all the property values to be set on the object, then it validates the entire object in one go. FluentValidation's approach has the advantage of supporting cross-property validation. 

MVC's internal validation works in 4 main phases:
1) Checks that all non-nullable value types (such as ints/datetimes) have had a value specified.
2) if so, invokes any validators for that property against the value provided (eg DataAnnotation attributes)
3) If 1 and 2 pass, then the property value is set. 
4) If 1 and 2 both pass for *all properties* then model-level validators are run (ie FluentValidation)

The problem is that if stage 1 fails because no value was supplied for a non-nullable value type, then MVC will *never invoke model-level rules*, and so FluentValidation never gets executed. MVC doesn't provide any way to override this behaviour - the only customization that can be done is to hook in and change the message that's generated. 

So with your specific project, because the dropdowns are mapped to `int` properties, MVC is expecting you to supply a value. If you leave them blank, these fail the phase 1 check, so MVC never invokes model-level rules, and FluentValidation doesn't run. The same also applies to the date of birth field as it's mapped to a non-nulllable datetime. 

This is unfortunately one of the many limitations of MVC's validation infrastructure that cannot be worked around. Newer versions of MVC (part of asp.net core) don't have this limitation as I worked with the asp.net team to come up with an approach that was better for third party libraries to integrate with. Sadly these changes were never back-ported to MVC 5, so we're stuck with this limitation for projects using legacy versions of MVC (5 or older). 

However there are 2 workarounds:
1) As you already partially discovered, the behaviour with nullable value types is different. If you switch all of your value types to nullables (ints, longs, DateTimes etc) then MVC will completely skip phase 1 of its validation, and everything will be handled by FluentValidation. However you will have to change all value types in the model, there can't be some nullable and some not-nullable. They must all be nullable.

2) Supply a default value for non-nullable value types. So for those 3 dropdowns, send 0 instead of blank as the default value. FV's `NotEmpty` rules will still handle this. Same goes for dates (eg use DateTime.MinValue) 

My personal preference would be option 1.

When working with MVC5, you need to treat your view-model as a direct representation of the screen. So if the screen allows you to physically leave a value blank, the model property must do the same (ie with a nullable). Even if your validation rules disallow this, the data type needs to allow it. 

Hope that makes sense. Let me know if there's anything you'd like me to clarify.

**Comment by Eclipse-Computing** [comment]
I have read through your reply very carefully, and I think there might be a misunderstanding.

> So with your specific project, because the dropdowns are mapped to int properties, MVC is expecting you to supply a value. If you leave them blank, these fail the phase 1 check, so MVC never invokes model-level rules, and FluentValidation doesn't run. The same also applies to the date of birth field as it's mapped to a non-nulllable datetime.

Actually, from what I saw the opposite was happening. When I had an `int`, and tried to submit a completely empty form, FV _did_ fire, because I got the desired (and expected) error messages from the validation for those three drop-downs. To be specific: I got validation messages that only existed in my FV validation classes.

It was when I turned them into `int?` that FV failed to fire at all, which was _undesired_ behaviour.

So when I have non-nullable data types, FV behaves as expected and desired: submitting an `int` with a null value _does_ get FV to fire.

The problem is that, aside from the three drop-down select menus, there are no more non-nullable data types available in my form - they are all `string` data types. I do not know of any way to turn a `string` into a non-nullable data type, as a `string` can _always_ return an empty string. And in fact, this is my biggest struggle -- I _need_ FV to validate empty string fields, in order to throw errors upon form submission (most string fields cannot be empty!!), and it does not do so.

**Comment by JeremySkinner** [comment]
> Actually, from what I saw the opposite was happening. When I had an int, and tried to submit a completely empty form, FV did fire, because I got the desired (and expected) error messages from the validation for those three drop-downs. To be specific: I got validation messages that only existed in my FV validation classes.

That's not actually the case, but I can see why you'd think that. FluentValidation itself is not executing. What's happening is MVC is reading metadata from the validator and using that to build the messages that you're seeing. So the messages are coming from FV, but only from metadata. The validator is not actually being executed. These messages are coming from MVC's "validatate non-nullable value type" phase, but it just happens to be reading the messages out of FV's metadata when it generates them.

> It was when I turned them into int? that FV failed to fire at all, which was undesired behaviour because those drop-down select menus are requried submissions: a choice must be chosen for them.

This is not what I'm seeing when I run your project. When I convert the ints to `int?`, the validator is executed correctly. 

> So when I have non-nullable data types, FV behaves as expected and desired: submitting an int with a null value does get FV to fire.

No, honestly it doesn't :)

> And in fact, this is my biggest struggle -- I need FV to validate empty string fields

strings are reference types and are already nullable. You don't need to do anything special here. Once you change your ints to nullable, the validators on strings will all execute correctly as MVC will no longer abort the validation pipeline before FV is executed.

**Comment by JeremySkinner** [comment]
Just to clarify, these are the steps I took to get your sample working:

- Changed CountryId, HowHeardId and TrainingSiteId to int? 
- Removed the calls to .Trim() inside RuleFor for first/lastname (RuleFor calls should reference properties directly)

![image](https://user-images.githubusercontent.com/90130/40588047-9e7bbaf6-61cf-11e8-8050-3a8f593aa706.png)

**Comment by Eclipse-Computing** [comment]
>This is not what I'm seeing when I run your project. When I convert the ints to int?, the validator is executed correctly.

Then there is already a critical difference between our two projects, which currently are code-identical.

When I run my own project locally - _with_ a connection to the DB - only `int` values get triggered at all. And your explanation for that does sound logical, so I will defer to your authority.

When I turn them into `int?`, _nothing_ gets triggered, and I get data insertion exceptions.

The screenshot you just posted is something I have _never_ been able to achieve, and is _exactly_ what is desired.

**Comment by JeremySkinner** [comment]
What happens when you run it without the database like I'm doing?

**Comment by JeremySkinner** [comment]
Also, just to check, as well as changing the ints to int?, you did also remove the calls to .Trim() in the firstname/lastname rules?

**Comment by Eclipse-Computing** [comment]
>What happens when you run it without the database like I'm doing?

How did you modify the site to allow it to do so? The drop-down select menus are auto-filling menus, so just commenting out the `connectionString` in the Web.Config causes issues. Never had to do something like this before…

>Also, just to check, as well as changing the ints to int?, you did also remove the calls to .Trim() in the firstname/lastname rules?

Yes, forgot to do so before I sent you the package. Sorry. Changed that afterwards.

**Comment by JeremySkinner** [comment]
> How did you modify the site to allow it to do so?

I just changed the methods to return a fixed list of items, rather than calling into the datacontext. Eg 

```
public static IEnumerable<SelectListItem> HowHeadList() {
  yield return new SelectListItem { Value = "1", Text = "Test1" };
  yield return new SelectListItem { Value = "2", Text = "Test2" };
  //etc
}
```

**Comment by Eclipse-Computing** [comment]
Completely different result on my end, when trying to submit a blank form:

![image](https://user-images.githubusercontent.com/20525324/40588215-df5d4cce-618e-11e8-9e44-397bdd379e3d.png)

**Comment by Eclipse-Computing** [comment]
As you can see, all required text fields fail to fire.

Now I have fully cut out the DB in the `connectionString`, so there is definitely no more connection between the DB and the project, but this issue persists. **confused**

**Comment by JeremySkinner** [comment]
That means it's still seeing those 3 dropdowns as non-nullable value types. You definitely recompiled after changing from int to int?

**Comment by Eclipse-Computing** [comment]
Don't have skype. Teamviewer, perhaps?

**Comment by Eclipse-Computing** [comment]
Downloading Skype.

**Comment by JeremySkinner** [comment]
Sure teamviewer works too if you want to start a session

**Comment by Eclipse-Computing** [comment]
Just messaged you on Skype.

**Comment by Eclipse-Computing** [comment]
Come to think of it, I think I now know where a conceptual problem might have snuck in.

Since before I started using Fluent Validation, I have used `GUID`s in my primary keys. And `GUID`s are, well… `GUID`s. I handle them as `GUID`s throughout the entire data lifecycle, all the way out to the View through the ViewModel and back. And they have _always_ been non-nullable when they act as required foreign keys… and FV has validated as expected. But because this project made use of a database that pre-dated my tenure at my current place of employment, it made use of plain integers as primary keys instead.

As such, since GUIDs can be non-nullable and still fire FV, I made the assumption - however wrong - that `int` could do the same. When it fact, this case shows it could not. So now even though the database field is an `int`, I need to build the drop-down select menu with an `int?`, catch any null value through FV, and then use a null-coalescing operator to cast to an `int` (with a default value in case FV fails to catch a null) when passing that value from the ViewModel to the Data Model.

Once again, my deepest appreciation on your assistance on a Sunday. You could have easily blown me off until business hours, but you didn’t. You have shown your quality, Sir - the very highest.

**Comment by JeremySkinner** [comment]
You’re welcome - glad it’s working.
