### ISSUE TITLE
Multiple validations for one property

### ISSUE THREAD

**Issue by Kunze** [JeremySkinner/FluentValidation#777]
I have one property named FederalTaxIdOrSSN, so, I would to make it validation if it is either a tax id or ssn. How can I make it work?

**Comment by JeremySkinner** [comment]
Simplest thing to do is probably call `Must`, and then perform both checks in the delegate: https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#predicate-validator

**Comment by Kunze** [comment]
Is there any way to use custom rules inside Must? I have already two custom rules for Federal Tax Id and SSN. I wouln't like to duplicate the code just to use in such situations. I mean, something like that:

`
RuleFor(x => FederalTaxIdOrSSN).Must(ruleBuilder => {
     return ruleBuilder.FederalTaxId() ^ ruleBuilder.SSN()
})
`

**Comment by JeremySkinner** [comment]
Not like that I'm afraid. A call to `Must` needs to return a boolean, but custom rules return a collection of ValidationResults, which require full context in order to build. 

If you want to reuse the logic then I'd suggest having both the Must call and the custom rules internally call into simple methods that perform the work.

**Comment by Kunze** [comment]
Makes sense, thank you very much.
