### ISSUE TITLE
Async deadlock in CollectionPropertyRule

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#779]
From #759:

Hello,

The line introduced with this fix now causes async deadlocks:
https://github.com/JeremySkinner/FluentValidation/blob/976b198207b9e6b53b07af46bc21af203b0712a0/src/FluentValidation/Internal/CollectionPropertyRule.cs#L103

The issue appeared after updating FluentValidation from 7.5.0 to 7.6.0.

Observed in the following circumstances:
- Validator for an item is passed to RuleForEach()
- The validator has overridden ValidateAsync method from where a DB call is made
- Right after DB query is issued the execution never returns, the thread hangs forever

The described conditions are a bit weird and under refactoring at the moment extracting the data loading responsibility out of the validation flow. 

Thank you!

**Comment by AdemCatamak** [comment]
RuleFor(obj => obj.XValue).NotNull()
                              .WhenAsync((obj, t) =>
                              {
                                  while (true){ }
                                  return Task.FromResult(true);
                              });

As in the situation above, if ‘WhenAsync’ method never returns a result, deadlock occurs. Does Issue-779 mean this situation?

If my understanding is correct, there was no issues in the previous version. The reason for this is that when ‘Validate’ method was called, ‘Task’ in ‘WhenAsync’ method was not called. ‘Task’ answer is always accepted as ‘true’.

A possible solution: a timeout period that user can override can be given.

    void WhenAsync(Func<T, CancellationToken, Task<bool>> predicate, Action action)

can be overload

    void WhenAsync(Func<T, CancellationToken, TimeSpan,  Task<bool>> predicate, Action action)

I would like to try to solve this issue. If you have any other solution advice, I will take notice.

**Comment by JeremySkinner** [comment]
The issue is the explicit use of `validationTask.Result` as the task may not have completed by the time you're accessing the result. I've pushed up a change that should fix it. See https://github.com/JeremySkinner/FluentValidation/commit/537f65662fb383954a833901bf8f8fe9b10d5a47

**Comment by JeremySkinner** [comment]
I'll try and get a new published this evening, feel free to build from source and give it a try before then.

**Comment by JeremySkinner** [comment]
//cc @matrosovalexei

**Comment by AdemCatamak** [comment]
I forgot about the discouragement against usage of `.Result`. I should have used `await` to solve the problem. I will keep this in mind for the future. I am sorry that the code I wrote caused the bug

Thanks for the quick response and action against the bug

**Comment by JeremySkinner** [comment]
No problem, I should've caught it during review! 

I'll get the new build out in an hour or so.

**Comment by JeremySkinner** [comment]
I've pushed out the 7.6.101 release. Should show up on nuget shortly.

@matrosovalexei @AdemCatamak Please give it a try and let me know if it all seems to be working OK.

**Comment by matrosovalexei** [comment]
@JeremySkinner @AdemCatamak 
Thank you for the operative response!

I've just tested 7.6.101 in our project, the issue is gone. However another one popped up.

Validation tasks used to be created and run synchronously. I suppose it was a design decision, that's been there for a long time.
Used to be:
https://github.com/JeremySkinner/FluentValidation/blob/4d3e4e7123ce5ca65c80b54fde1030e7d2635a38/src/FluentValidation/Internal/CollectionPropertyRule.cs#L80-L96
The not-yet-iterated `validators` `IEnumerable<>` goes to `TaskHelpers.Iterate()`. Tasks are spawned and run one after another.

Now I see:
https://github.com/JeremySkinner/FluentValidation/blob/f54266ba1472eddc57c9d1e53b2caf03c1fb7417/src/FluentValidation/Internal/CollectionPropertyRule.cs#L87-L103
Tasks are spawned right away, put to `validationTasks` list, all alive already, all competing to complete.

EntityFramework, the least to say, dislikes parallel actions on its context and throws `NotSupportedException`. That's how I spotted.

Is it now intentional to have parallel validation tasks execution?

Thank you!

**Comment by JeremySkinner** [comment]
I think if it's causing problems then I'd prefer to go back to the original approach. I'll have another play with this later today and try and get an update for you in a few hours.

**Comment by matrosovalexei** [comment]
Thank you! I tested with version 7.6.102, things work as expected now!

I once needed to implement similar tests to check that given tasks are executed synchronously. Short delays are involved, though works reliably.
Here's a bit simplified representation of the idea I implemented:
https://gist.github.com/matrosovalexei/c52abd75cab41a555c281a0f89843767

**Comment by JeremySkinner** [comment]
That's great! I'm glad it's working. Thanks again for reporting this and for using FluentValidation. I'll close this for now but let me know if you run into any further issues.

**Comment by JeremySkinner** [comment]
@matrosovalexei that code snippet worked nicely btw. Here's the resulting test:

https://github.com/JeremySkinner/FluentValidation/blob/9d2ed3ff629b811f4ca8fd8115dbf5ac538e7c40/src/FluentValidation.Tests/ForEachRuleTests.cs#L155-L171

**Comment by matrosovalexei** [comment]
Thank you! I'm happy to help :)
