### ISSUE TITLE
Best validator design?

### ISSUE THREAD

**Issue by flodpanter** [JeremySkinner/FluentValidation#78]
Hi there.

Im having design issues related to making a standardized way of using fluent validation in my development team. Let me try and explain my problem:

1, In my team we will be making over 100 different validators
2. I want it to be easy for new team members to start coding validators. At the same time I want the validator design to be consistent so I have defined a base class which every validator must inherit from. This way I can keep my concrete validators very small (and DRY) as the only code needed is the validation rule definition code.
3. I would prefer to keep all rule definitions in the constructors of my validators to separate rule definition and rule execution and make sure that the rule definition are only added once. Sometimes I need to perform custom validation on some data which is not available to me before I execute the validation. Therefore I currently dont have my rule definition in my constructor, but in a method defined as abstract on my base validator. It smells, but it works. I think there may be a better way of doing this, hence this question.

Any help appreciated.

public abstract class ValidatorBase<T> : AbstractValidator<T>
{
  public abstract void InitValidationRules();
  protected T ItemToValidate;
  
  public void Validate(T itemToValidate)
 {	
       ItemToValidate = itemToValidate;
       InitValidationRules();
	var result = Validate(itemToValidate);
        ...
}

public class CustomerValidator : ValidatorBase<ICustomer>
{
   public override void InitValidationRules()
   {
     //problem here is that my custom validator expects a concrete value rather than a lambda
     RuleFor(x => ItemToValidate.Aktuelle).MustNotContain(ItemToValidate.Opret.Kred).
   }
}

public static class FluentValidationExtensions
{

        public static IRuleBuilderOptions<T, IList<TElement>> MustNotContain<T, TElement>(this IRuleBuilder<T, IList<TElement>> ruleBuilder, TElement value)
	{
	  return ruleBuilder.SetValidator(new MustNotContain<TElement>(value));
	}
}

public class MustNotContain<T> : PropertyValidator
{
	private readonly T _value;

	public MustNotContain(T value)
			: base(string.Format("Value {0} for {{PropertyName}} is illegal, as it exists!",value))
	{
	  _value = value;
	}

	protected override bool IsValid(PropertyValidatorContext context)
	{
		var list = context.PropertyValue as IList<T>;
		return (list == null || !list.Contains(_value));
	}
}

**Comment by flodpanter** [comment]
I just noticed that some of the code I pasted was formatted wrongly. Hopefully you get the idea. Otherwise I will upload the working code.

**Comment by JeremySkinner** [comment]
So there's a few problems with this approach that I can see:

The rules themselves are designed to be created when the validator is instantiated - there shouldn't be any reason to create new rules during validation. This is to keep them thread safe, and also avoid the performance hit of parsing expression trees at runtime. So you can cache a validator instance (eg in an IoC container) and re-use it across threads (eg across web requests)

Storing the current item in the ItemToValidate property breaks this, as does adding rules at runtime. 

Also, your rules should access the property within the lambda directly, so `RuleFor(x => x.SomeProperty)` not `RuleFor(x => ItemToValidate.SomeProperty)`.

> "Sometimes I need to perform custom validation on some data which is not available to me before I execute the validation"

There shouldn't ever be a reason for this - it's better to design the validators to obtain any data they need lazily, rather than up-front. I've re-written your MustNotContain rule as an example - you can then hopefully apply the same principle to any other validators you have:

```
public class MustNotContain<TModel, TElement> : PropertyValidator
{
	private readonly Func<TModel, TElement> _valueFunc;

	public MustNotContain(Func<TModel, TElement> valueFunc)
		: base("Value {ComparisonValue} for {PropertyName} is illegal, as it exists!")
	{
		_valueFunc = valueFunc;
	}

	protected override bool IsValid(PropertyValidatorContext context) {
		var comparisonValue = _valueFunc((TModel) context.Instance);
		var list = context.PropertyValue as IList<TElement>;
		var valid = (list == null || !list.Contains(comparisonValue));

		if (!valid) {
			// Rplace the {ComparisonValue} placeholder for the error message
			context.MessageFormatter.AppendArgument("ComparisonValue", comparisonValue); 
		}

		return valid;
	}
}

public static class FluentValidationExtensions
{
	public static IRuleBuilderOptions<T, IList<TElement>> MustNotContain<T, TElement>(this IRuleBuilder<T, IList<TElement>> ruleBuilder, Func<T, TElement> value)
	{
		return ruleBuilder.SetValidator(new MustNotContain<T, TElement>(value));
	}
}

```
...Useable like this:
```
public class CustomerValidator : AbstractValidator<Foo> {
	public CustomerValidator() {
		RuleFor(x => x.Aktuelle).MustNotContain(x => x.Opret.Kred);
	}
}
```

So it now uses a delegate to obtain the comparison value lazily, and also uses custom placeholders in the error message to avoid you needing the comparison value in the constructor. 

Hope this makes sense.

**Comment by flodpanter** [comment]
HI Jeremy. 

First of all I want you to know that I am very grateful for your help. The question was maybe more related to the proper use of func and this concept is rather new to me. I replaced my MustContain with yours and it works as expected.

Your points make sense to me. My validation is often tied to data contained in a database. I am now using your approach enabling me to separate validation definitions and execution.

Many thanks
