### ISSUE TITLE
Email Validator to match with ASP.Net

### ISSUE THREAD

**Issue by Nness** [JeremySkinner/FluentValidation#784]
From issues #769 and #766 you have stated that `FluentValidation` is intentionally match with ASP.NET's implementation, While ever since ASP.NET core 1.0, [EmailAddressAttribute](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs) no longer uses Regex. 

What is your plan for Email Validator to match with latest implementation of ASP.NET core? Since FluentValidation have different behaviour than ASP.NET now.

**Comment by Nness** [comment]
There are several discussions on ASP.NET core regarding their current approach.

https://github.com/dotnet/corefx/issues/4923
https://github.com/dotnet/corefx/issues/28501

**Comment by Nness** [comment]
Eilon said in https://github.com/dotnet/corefx/issues/4923
> yup that's totally how I look at this. The value of parsing an RFC-valid email address is close to zero for me.

I have read several article regarding Email Address validation, email address spec is very complex, there is no way to validate with Regex. The best approach is to send email and see if they receive it. Syntax validation can only go up to certain level to avoid fat finger.

I believe that's the reason why ASP.NET team changed their approach. during rewrite.

**Comment by JeremySkinner** [comment]
Hi, I don't have any plans to change this.

Although asp.net core does indeed use a similer check, the attribute that ships as part of the full framework continues to use the same regex, and for backwards compatibility FluentValidation will continue to use this.

**Comment by Nness** [comment]
That's all good. I will write custom validator like what other people did. Thanks for explain.

**Comment by lukos** [comment]
Please can you clarify this point @JeremySkinner? We have just realised that after porting a project from dotnet to dotnet core, our unit tests are broken because emails that used to validate correctly with regex are now literally checking that there is exactly one @ symbol in the text to pass validation, which is basically worthless. Even though the regex was complicated, it did not have to be perfect and could easily have a property that could enable "simple checking" if people were reporting too many false negatives for edge cases.

It seems like a strange suggestion to write a custom validator to do what the attribute has done for years in dotnet fx and mvc? Thx

**Comment by JeremySkinner** [comment]
@lukos The behaviour in FluentValidation has not changed. FluentValidation continues to use the same regex it always has done, even when using AspNetCore.

It's the *ASP.NET Core EmailAddressAttribute* that's changed its behaviour (part of DataAnnotations) to just check for an @. That's nothing to do with FluentValidation. 

If you continue to use FluentValidation, the behaviour will remain the same.

**Comment by lukos** [comment]
Thanks! I just realised that this issue was clicked through from the corefx project, which is why I was confused. #awkward
