### ISSUE TITLE
Error when use custom datatypes and Fluent Validation

### ISSUE THREAD

**Issue by nuwa4u** [JeremySkinner/FluentValidation#811]
I am getting following error when we use model attributes which has our own custom datatypes. Tried different ways, but still have no luck of fixing this error. Please help 

### [NotImplementedException: The method or operation is not implemented.]
   System.Web.HttpContextBase.get_Items() +39
   FluentValidation.Mvc.RuleSetForClientSideMessagesAttribute.GetRuleSetsForClientValidation(HttpContextBase context) +14
   FluentValidation.Mvc.FluentValidationPropertyValidator.ShouldGenerateClientSideRules() +32
   FluentValidation.Mvc.<GetClientValidationRules>d__1.MoveNext() +82
   DevExtreme.AspNet.Mvc.DataAnnotationsHelper.GetValidationRules(String propertyName, ModelMetadata modelMetadata, ViewContext viewContext) +254
   DevExtreme.AspNet.Mvc.<>c__DisplayClass4_0`2.<AddFor>b__0(IHtmlHelperAdapter html, DataGridColumnBuilder`1 item) +276
   DevExtreme.AspNet.Mvc.Factories.CollectionFactory`1.Add(Action`2 configurator) +42

**Comment by JeremySkinner** [comment]
Hi, could you confirm which version of ASP.NET you're running?

This message isn't coming from FluentValidation itself, but it's saying that `HttpContext.Items` is missing, which suggests you're not running a supported version of asp.net (FluentValidation supports Core 2.1, MVC5 and WebApi 2)

**Comment by nuwa4u** [comment]
Hi Jeremy, We are using MVC5 and WebApi 2. Issue happend when View Model is use in DevExtream Data Grid. Below is a sample code where exactly error happen. 

   case CustomDataTypes.Boolean:
                            itemBuilder = factory.AddFor(property)**.DataType(GridColumnDataType.Boolean);**

**Comment by JeremySkinner** [comment]
It sounds like a problem with the grid rather than FluentValidation - it looks like they're essentially buidling a fake `HttpContext` internally that doesn't support `HttpContext.Items`. 

The only workaround I can think of is to try turning off fluentValidation's clientside validation (as this is where HttpContext.Items is being used), and remove any `RuleSetForClientSideMessagesAttributes` (if you're using them)

As to why this is happening, you'd need to ask the developers of the grid why they are throwing an exception when trying to access HttpContext.Items.

**Comment by nuwa4u** [comment]
Thanks Jeremy. We found that this is due to the way we create our controls in Dev Extreme. We have found a work around for that. So this issue was not related to the Fluent Validation. Thanks
