### ISSUE TITLE
What happened to ValidatorBase<T>?

### ISSUE THREAD

**Issue by Arash-Sabet** [JeremySkinner/FluentValidation#839]
### System Details

- FluentValidation version: **8.0.0-preview3**
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): 
**ASP.NET Core 2.1**

### Issue Description
There was a compiler warning recommending us to replace AbstractValidator<T> with ValidatorBase<T> as of version 8.x moving forward. To do away from this warning and brace for future releases, we replaced all AbstractValidator with Validator<T>. Upgrading to preview-3 broke the code compilation due to the unavailability of ValidatorBase<T>. Obviously, we should rollback all changes to reuse AbstractValidator<T> again! Why did such a change happen and how we should plan accordingly? Thanks.

**Comment by JeremySkinner** [comment]
I had to revert the move to ValidatorBase due to some major issues with the new rule cache. Please stick with AbstractValidator for now. 

Note that these are preview builds that are likely to change between now and the 8.0 release. If you’re not currently in a position to handle breaking changes then I’d  recommend sticking with 7.x until a RC build becomes available. 

Apologies for any inconvenience this has caused.

**Comment by JeremySkinner** [comment]
After playing with this more over the weekend this won't be re-introduced for 8.x as there are too many issues.
