### ISSUE TITLE
Async Documentation

### ISSUE THREAD

**Issue by waynebrantley** [JeremySkinner/FluentValidation#873]
Your new documentation site is great - nice start.
I noticed (because I was looking), there is not any mention of how to do async.

- It appears you need to do
``RuleFor( x=>x).MustAsync(x=>...)``

Also appears you have to use ``ValidateAsync`` at the top instead of ``Validate'.
Is that correct.

Why isn't there a ``RuleForAsync``?  This this we could do
``RuleForAsync( async x=>x.Something()).NotNull()`` 
instead of 
``RuleForAsync( pointless=>pointless).MustAsync(async x=>(await x.Something())!=null)``

**Comment by JeremySkinner** [comment]
I noticed (because I was looking), there is not any mention of how to do async.

I just haven't got around to writing it yet :)

> Also appears you have to use ValidateAsync at the top instead of `Validate`. Is that correct.

If you use async validators within your rules, then you should call `ValidateAsync` at the top level. If you do not use async validators inside your rules, then you you should use `Validate` at the top level, ie be consistent in whichever one you need.

> Why isn't there a RuleForAsync?

Asynchronisity is controlled at the validator level, rather than the rule level as it's the validators that are actually doing the work. Ie, the async workflow is always "should the validator be run asynchronously against the value" rather than what you're proposing which is "the value should be obtained asynchronosly". That's very different and has very large implications for the codebase. Also, defining a rule against a method is a bad idea as you lose the benfit of rule caching - `RuleFor` is designed to be called on a property (or the model itself). I like the idea though, but not sure how feasible this would be. Can look at it for a future version.

**Comment by waynebrantley** [comment]
>> f you use async validators within your rules, then you should call ValidateAsync at the top level. If you do not use async validators inside your rules, then you you should use Validate at the top level, ie be consistent in whichever one you need. 

We are using FV as a decorator in CQRS pattern.  We do not use it for model validation on MVC, etc.    Being it is a decorator - I have to either call ``Validate`` or ``ValidateAsync`` for a given validator and would not know which one to call.   So, I suppose I would just call ``ValidateAsync`` as it does everything validate does, PLUS async - right?

What is the reason for having to switch between ``validate`` and ``validateAsync`` from the top level?  I suppose if I had to - I could create an interface or something that was attached to the validator so I would know which one to call...but that seems messy.

**Comment by JeremySkinner** [comment]
>  So, I suppose I would just call ValidateAsync as it does everything validate does, PLUS async - right?

Yes, although you are incurring an unnecessary overhead if there are no async validators defined. 

> What is the reason for having to switch between validate and validateAsync from the top level

It's the same as with all other .NET apis that use async. Essentially there are 2 completely separate code paths - the non-async path calls all methods directly, while the async code path one uses `Task`s that represent the validation calls for use with `await` and `async`. The two apis are completely separate and have very different behaviour, in the same way that eg the .NET HTTP apis offer both sync and async APIs. You as the developer need to be the one who decides which approach you want to take - this is not a decision that the framework can make for you.

**Comment by waynebrantley** [comment]
Ok, thanks for the clarification.  
I guess I could use different classes derived from AbstractValidator...one for Async and one for regular - then validate based on the chain, etc...
