### ISSUE TITLE
Customize ModelState Values

### ISSUE THREAD

**Issue by WarpSpideR** [JeremySkinner/FluentValidation#885]
I'm currently developing an Asp.Net Core API app and have integrated FluentValidation to the MVC validation pipeline and this is all working great.

However, I've got my validators setup so that they return error codes for each type of validation error and I'd like to be able to pass this on to the ModelsStateDictionary so I can use these codes in my response messages but I don't see any way to do this.  Firstly, is it possible? Then if this is not possible is there any way to add an adapter that can shape the data as it's passing from FluentValidation to ModelState? Or is there a better approach to what I want to achieve?

**Comment by JeremySkinner** [comment]
Are you using the automatic integration with MVC, or are you invoking the validators manually?

If you're using the automatic integration then you can use the `IValidatorInterceptor` interface to do this. [There's a section in the docs on how to use an interceptor](https://fluentvalidation.net/aspnet#validator-interceptors) but essentially what you want to do is use the `AfterMvcValidation` method to reconstruct a new `ValidationResult` instead of using the usual one.

Internally, FluentValidation's `ValidationFailure`'s are mapped to MVC's `ModelValidationResult` by using the failure's `PropertyName` and `ErrorMessage`, so when you reconstruct the result, you should copy the `ErrorCode` from the source to the `ErrorMessage` on the destination, and now the error code will be passed to MVC instead of the message. Quick example (untested);

```csharp
public class UseErrorCodeInterceptor : IValidatorInterceptor {
  public ValidationContext BeforeMvcValidation(ControllerContext controllerContext, ValidationContext validationContext) {
    return validationContext; 
  }

  public ValidationResult AfterMvcValidation(ControllerContext controllerContext, ValidationContext validationContext, ValidationResult result) {
    var projection = result.Errors.Select(failure => new ValidationFailure(failure.PropertyName, failure.ErrorCode)));
    return new ValidationResult(projection);
  }
}
```

You can then wire it up to your controller:

```csharp
public ActionResult MyAction([CustomizeValidator(Interceptor=typeof(UseErrorCodeInterceptor))] MyModel model) { 
 // etc
}
```

You can implement `IValidatorInterceptor` directly on your validator if you don't want to use the attribute.

**Comment by WarpSpideR** [comment]
Yes, I was using the automatic integration to MVC and I added the IValidatorInterceptor interface to my base validator class and that has worked perfectly.

Thanks for the quick reply Jeremy much appreciated!
