### ISSUE TITLE
"When" runs multiple times (once for each validator) instead of just once.

### ISSUE THREAD

**Issue by samwong1976** [JeremySkinner/FluentValidation#900]
Is there a way to have the When condition run only once no matter how many validators a rule has?

When(SomeCondition, () => // Runs twice. Once for each validator :(
 {
    RuleFor(m => m.Prop1)
           .NotEmpty().WithMessage("Please fill out this field.")
           .Must(BeValidProp1).WithMessage("This field is invalid.");
 });

**Comment by JeremySkinner** [comment]
Hi, no that is the normal behaviour. A call to `When` like this is essentially applying the condition to each validator in the chain. The end result is essentially this:

"Prop 1 must not be empty when some conditon is true" followed by "Prop 1 Must (BeValid) when some condition is true". Each validator in the `RuleFor` chain is standalone, so the condition must be applied to each validator to get the expected behaviour.

The inline version of the `When` method has an alternative method of operating which can be specified by the `ApplyConditionTo` enum.

For example, this is exactly the same as your example above:

```
RuleFor(m => m.Prop1)
.NotEmpty().WithMessage("Please fill out this field.")
.Must(BeValidProp1).WithMessage("This field is invalid.")
.When(SomeCondition);
```

When you define a condition inline, the default behaviour is to apply the condition to *all previous validators in the rule chain*. You can change this so it only applied to the one that directly precedes it like this:

```
RuleFor(m => m.Prop1)
.NotEmpty().WithMessage("Please fill out this field.")
.Must(BeValidProp1).WithMessage("This field is invalid.")
.When(SomeCondition, ApplyConditionTo.CurrentValidator);
```

Now the condition will only apply to the `Must`, and will not apply to the `NotEmpty`. 

But if you want the condition to apply to both validators, then it must be run twice. There is no way around this.
