### ISSUE TITLE
Even Better DI Support - Bind "Open Generic" IValidator, based on Controller Actions

### ISSUE THREAD

**Issue by jzabroski** [JeremySkinner/FluentValidation#911]
Registering Model Validators in ASP.NET Core DI should allow for binding open generic model validators.

For example, I want to write the following:

```
    public class ModelValidatorBase<TModel, TEntity> : AbstractValidator<TModel>
        where TModel : ModelBase
        where TEntity : class, IEntity
    {
        protected const string Create = "Create";
        protected const string Update = "Update";
        protected const string Delete = "Delete";
        protected const string CreateOrUpdate = "CreateOrUpdate";

        public static string EntityNotFound(TModel model)
        {
            return $"No {typeof(TEntity).Name} found matching Id [{model.Id}]";
        }

        public static string EntityNotFound<TEntityNotFound>(long id) where TEntityNotFound : class, IEntity
        {
            return $"No {typeof(TEntityNotFound).Name} found matching Id [{id}]";
        }

        public static string DuplicateEntity(TModel model)
        {
            return $"Duplicate entity. {typeof(TEntity).Name} already exists: Id [{model.Id}].";
        }
    }
```
where `ModelBase` is simply:
```
    public abstract class ModelBase
    {
        public long Id { get; set; }
    }
```
and `IEntity` is a marker interface: `public interface IEntity { }`

And I have a `DeleteValidator` as so:
```
   public class DeleteValidator<TModel, TEntity> : ModelValidatorBase<EntityDeleteRequest<TModel, TEntity>, TEntity>
        where TModel : ModelBase
        where TEntity : class, IEntity
    {
        public EntityDeleteRequestValidator(
            IRepository<TEntity> repository)
        {
            RuleSet(Delete, () =>
            {
                RuleFor(x => x.Id)
                    .NotEmpty();

                RuleFor(x => x.Id)
                    .Must(x => repository.FindById(x) != null)
                    .WithMessage(EntityNotFound);
            }
        }
    }
```
where `EntityDeleteRequest` is defined as:
```
    public class EntityDeleteRequest<TModel, TEntity> : ModelBase
        where TModel : ModelBase
        where TEntity : class, IEntity
    {
    }
```

The problem is that this is an open generic, and there is no way I can see to close the generic when registering the container in ASP.NET Core MVC:

The generics are always closed, but they're closed at the point of the Controller Action - there is no standalone type that closes it.

While I can write the boilerplate to close these generics, it would be nice if FluentValidation.AspNetCore module first looked at my models on my actions, and then resolved those models' run-time type information, and *then* used that to close the open generic types *for me*.

This request is largely inspired by a series of academic computer science papers called *Scrap Your Boilerplate* (SYB), which discusses how to avoid closing types just to have a concrete data representation.

**Comment by jzabroski** [comment]
@JeremySkinner I'll try to take this on, but it's much less likely I'll get to this in the next few weeks.

**Comment by JeremySkinner** [comment]
I'd like to have a think about this before you do any work on it. It's not a common use case, and is likely to be a fair amount of code to maintain so I'm currently thinking this may not be something that I want in the core project

**Comment by jzabroski** [comment]
It's probably not a common use case because most programmers don't spend the time to do abstraction.

When you say a fair amount of code to maintain, how do you measure?  I would guess under 50 lines of code, but there is other ways to define quantity of code than just lines.

**Comment by JeremySkinner** [comment]
> It's probably not a common use case because most programmers don't spend the time to do abstraction.

No, It’s not a common use case because it is unnessarily complex for the majority of scenarios where FluentValidation is used. 

> Good libraries should encourage programmers to learn that abstraction and data modeling is easier than it seems.

The priority for a good library is to provide value and solve a specific problem for developers. For FluentValidation, this is providing a way to build strongly typed validation rules - that’s the goal of this project. 

Any code that is contributed to FluentValidation ends up being something that I have to support and maintain for many years.  As I have limited time available, I try to be careful with what ends up being included because I don’t have the time or desire to maintain code that is not core to FluentValidation’s core goals, especially if I feel a feature is not going to be used by the vast majority of users compared to other feature requests. 

You might find this disappointing but prioritisation like this is necessary a library like FluentValidarion which has a huge number of users, but a single maintainer. It keeps the product focused and it keeps me sane. 

This particular feature is:
- not core to the problem domain
- not a common scenario (in the 10 years that I’ve worked on this project you are the second person to ask for this) 
- something that can be implemented outside of FluentValidation easily enough for those who actually need this. 

So as I said before, I’m going to take some time to think on this one before deciding if it’s something I want in the core project.

**Comment by jzabroski** [comment]
> This particular feature is:
> 
> * not requested often (only twice in 10 years)

Who else requested it? Thanks.

Is this it? https://github.com/JeremySkinner/FluentValidation/issues/590

**Comment by JeremySkinner** [comment]
Yes, although that was a slightly different issue as the validator was already closed over an interface type.

**Comment by JeremySkinner** [comment]
Decided against implementing as out of scope. Closing.
