### ISSUE TITLE
Version 5.4 is giving an Error that version 3.6 didn´t gave. 

### ISSUE THREAD

**Issue by lopez175** [JeremySkinner/FluentValidation#941]
### System Details

- FluentValidation version: 5.4
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): MVC5

### Issue Description
Hello,

 I know that FluentValidation only sends metadata to Jquery validator to perform Client-Side validation (#936). However, this error didn´t occured when I had the FluentValidation version number: 3.6. So is there any changes in version 5.4 that you can think of that may have caused this error to occur?

Model:

```
public class Cuenta
{
    ...
    public DateTime? HoraInicio { get; set; }
    ...
} 
```

View:

```
    ...
	<td>
		@Html.Kendo().TimePickerFor(model.Cuenta =>model.HoraInicio).Min("8:00").Max("22:00").Format("HH:mm").Interval(30)
                @Html.ValidationMessageFor(model => model.HoraInicio)
	</td>
    ...
```

Error: 

 Jquery Validator is treating the time as a datetime, so it is giving the error "The field HoraInicio must be a date."

**Comment by JeremySkinner** [comment]
I can’t really help with issues related to jquery Validate I’m afraid - only FluentValidation itself - but maybe you could compare the generated metadata between the 2 versions to see if there’s a difference?

Note that version 5.4 is an old release from 2014. It is no longer recommended or supported. There have been many fixes and improvements since then. I would highly recommend using a modern version (8.0 is the latest). You may find this works better.

**Comment by lopez175** [comment]
I tried using version 8.0 but I got this error #936 that I could´t resolve. Downgrading to 5.4 got rid of it.

The metadata is sent in the "data-val" attribute? or which one?

Thanks!

**Comment by JeremySkinner** [comment]
Yes, the data-val attributes are how MVC passes validation metadata to jquery. I’ll emphasise again that 5.4 is an obsolete version and I do not recommend that you use it.
