### ISSUE TITLE
SetValidator(Func<T, IPropertyValidator> propertyValidator) method

### ISSUE THREAD

**Issue by AlexSandilands** [JeremySkinner/FluentValidation#955]
### System Details

- FluentValidation version: 8.0.1

### Issue Description
Do you think you will add a SetValidator(Func<T, IPropertyValidator> propertyValidator) method at some point?
I've tried the solution suggested in [#467](https://github.com/JeremySkinner/FluentValidation/issues/467) but I'm doing some weird stuff with some nested property validators so it doesn't work for me because the original object of the Func isn't available when the result is needed down in a bottom validator.

For the meantime I'm just implementing IValidator in a new class and trying to duplicate the logic from the PropertyValidator over to that so I can use the SetValidator<TValidator>(Func<T, TValidator> ...) method.
Have you seen reasonable examples of implementing IValidator or would you generally recommend not doing that?

Cheers

**Comment by JeremySkinner** [comment]
This isn't something that I'm planning on adding at the moment. `PropertyValidator` implementations are the lowest level of validation worker in FluentValidation, so they are responsible for resolving other things further up the chain (the `SetValidator(Func<T,TValidator>)` overload is internally implemented as a property validator), so there isn't actually anything currently that would be able to resolve a property validator this way. The only way that it could be done is having another property validator that wraps the func and then delegates to the resolved validator.

I wouldn't recommend implementing `IValidator` to try and recreate PropertyValidator just for the sake of using this overload. The two aren't designed to be compatible (it's why there are adapters in place) and you'll end up duplicating a lot of what's in the library, which will be bad for future compatibility. I also don't think this is something that you should need to do really.

It's very rare that you should need to implement `PropertyValidator`s yourself, they're really FV's internal building blocks. You can usually achieve the same result without having to go down to this level. For example, anything that you'd do with a PropertyValidator could be done with an `AbstractValidator` derivative combined with a `Custom` rule, which means you'd then be able to use `SetValidator(Func<T,TValidator)` as usual. Eg imaine you wanted a custom property validator that acted on `string` properties. Instead of using PropertyValidator you could do the following:

```
public class MyCustomStringValidator : AbstractValidator<string> {
   public MyCustomStringValidator() {
      RuleFor(x => x).Custom(context => {
          bool valid = ... //some conditional check.
          if (!valid) { 
            context.AddFailure("Validation failed....");
          }
      });
   }
}
```
...which you could then use with `SetValidator` overloads that take an IValidator. 

Perhaps you could provide some more details on what you're trying to achieve?

**Comment by AlexSandilands** [comment]
Ah that Custom method is very cool, I'll definitely look to use that in the future (although I was very confused at first until I realised it had two parameters: Custom( (instance, context) => { } )).

That does kind of work for my scenario but I found another approach that does the trick okay.

I'm trying to validate a polymorphic tree structure.
Nodes have a list of Nodes, and there a several different sub-types of Node. I'm using something similar to your Polymorphic validator from [#111](https://github.com/JeremySkinner/FluentValidation/issues/111), passing the original polymorphic validator down to the sub-validators to avoid an infinite recursion when setting up.

It's kind of silly and over the top maybe but it's a fun challenge and I kind of want to see it through now :)

It's been working fine so far but I found that some types of the child nodes need contextual data from the top Tree class in order to validate properly. What I was hoping to be able to do was pass it down through the constructors of the sub-validators so it would look something like this:

```
public class TreeValidator : AbstractValidator<Tree>
{
    public TreeValidator()
    {
        RuleForEach(x => x.Nodes)
            .SetValidator(x => NodeHelper.NewPolymorphicValidator(new TreeContextData { x.Data, x.OtherData }))
    }
}
```
NodeHelper.NewPolymorphicValidator is a static helper method that creates the new PolymorphicValdator (which is a PropertyValidator), injects all of the sub-validators and passes the context data down through the constructors.

I did get a solution though, I sort of followed what you did and made another validator that sits on top, makes a rule for itself and passes the context to the constructor of the next one down, like this:

```
public class TreeValidator : AbstractValidator<Tree>
{
    public TreeValidator()
    {
        RuleFor(x => x)
            .SetValidator(x => new TreeValidatorWithContext(new TreeContextData { x.Data, x.OtherData }))
    }
}

public class TreeValidatorWithContext : AbstractValidator<Tree>
{
    public TreeValidator(TreeContextData treeContextData)
    {
        RuleForEach(x => x.Nodes)
            .SetValidator(NodeHelper.NewPolymorphicValidator(treeContextData))
    }
}
```
It can be done without a second class I believe using the Custom method, but that requires creating a new PropertyValidatorContext from the CustomContext and I'm not super confident with doing that correctly, or if it is even possible.
