### ISSUE TITLE
Bug at .EmailAddress() using FluentValidation

### ISSUE THREAD

**Issue by abdallahn** [JeremySkinner/FluentValidation#961]
### System Details

- FluentValidation version: 8.0.101
- Web Framework version ( ASP.NET Core 2.1 ):

### Issue Description
I try to validate Email Address Using EmailAddress function and my code like this :
RuleFor(x => x.Email).EmailAddress().WithMessage("Email should be like 'example@example.com'");
The problem is :
when you write an email like this "example" it`s work fine and displays the message.
but when you wire this "example@example" the message did not display and submit button not work.

**Comment by JeremySkinner** [comment]
Hi. Do you have client-side validation enabled? I’m assuming so, as the client-side validation provided by MVC is much more permissive than the server side validation providdd by FluentValidation.

**Comment by abdallahn** [comment]
Like this :
 <div class="form-group">
            <label>Email</label>
            <input asp-for="Test.Email" class="form-control" />
            <span asp-validation-for="Test.Email"></span>
        </div>
the validation is work but if you write "JeremySkinner" at email text box the message displays.
but if you write this "JeremySkinner@" the message not displaied and con not submit the form.
please try it and you will see what I am talking about .

**Comment by JeremySkinner** [comment]
Yes I do understand what you're saying but I think you misunderstood my response.

This behaviour is not coming from FluentValidation - it is coming from MVC's client-side validation ( jQuery Validate).

When you have client-side validation enabled, then rules are executed twice. Once on the clientside, using javascript (with jQuery Validate) and once on the server (with FluentValidation). The client-side javascript rules are generated by MVC by reading metadata from FluentValidation.

The issue is that jQuery.Validate (clientside) executes email address rules differently to FluentValidation's native rules (server-side). If you use only server-side validation, then this input will be correctly marked as invalid. The issue is that jQuery Validate is not handling "foo@" in the same way as FluentValidation's server-side rules.

FluentValidation is not the issue here.

**Comment by JeremySkinner** [comment]
So just to clarify further:

> if you write "JeremySkinner" at email text box the message displays

This will be coming from the client-side validation.

>  if you write this "JeremySkinner@" the message not displayed and can not submit the form

This should be coming from the serverside validation. As to why the message is not displaying, this is probably an issue with your view. Some things to check:
- Double check that the error is correctly being stored  in the `ModelState` dictionary. If so then  FluentValidation is definitely being executed correctly.
- Make sure your validation message label has a closing tag, and if you're using a validation summary make sure it's defined correctly. See https://github.com/JeremySkinner/FluentValidation/issues/387#issuecomment-275642915

**Comment by abdallahn** [comment]
it is work now, sorry it is my fault  thanks for the help .
