### ISSUE TITLE
Check for whether a ruleset was found/applied

### ISSUE THREAD

**Issue by Switch386** [JeremySkinner/FluentValidation#962]
Using the default extension methods, IValidate<T>.Validate(obj, ruleSet: "abc") will return a ValidationResult object. The issue I'm seeing is that the validation returns as True (successful) even if you're trying to execute a specific rule set and it is not found. It doesn't look like there's any feedback on that.

I'd like to propose either having an error thrownif the rule set is not found and/or adding a property on the ValidationResult that shows whether the specific ruleset was actually located and executed.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. Throwing an exception if the ruleset isn't found is a breaking change so that isn't something that would be included outside of a major release (9.0 isn't due until sometime mid next year), but adding a `RuleSetsExecuted` property on the ValidationResult is probably something that can be done fairly easily. I'll take a look at adding that for the next version.

**Comment by Switch386** [comment]
Much appreciated!

**Comment by JeremySkinner** [comment]
This is in the 8.1.1 release which is now on nuget.

**Comment by Switch386** [comment]
Thank you for your responsiveness!
